import { useEffect, useState } from "react";
import { BrainCircuit, Building2, ChevronLeft, ChevronRight, Download, Loader2, Mail, Save, Search, Trash2 } from "lucide-react";
import { adminApi } from "../lib/api";
import type { VendorRegistration, VendorStatus } from "../lib/types";
import { Button } from "@/components/ui/button";
import { toast } from "sonner";

const statuses: VendorStatus[] = ["registered", "approved", "hold", "rejected"];

export default function Vendors() {
  const [items, setItems] = useState<VendorRegistration[]>([]); const [total, setTotal] = useState(0); const [page, setPage] = useState(1);
  const [status, setStatus] = useState("all"); const [search, setSearch] = useState(""); const [query, setQuery] = useState(""); const [loading, setLoading] = useState(true); const [smart, setSmart] = useState(false);
  const load = async () => { setLoading(true); try { const data = await adminApi.listVendors({ status, q: search, page, pageSize: 15 }); setItems(data.items); setTotal(data.total); setSmart(false); } catch { toast.error("Could not load vendors"); } finally { setLoading(false); } };
  useEffect(() => { const timer = setTimeout(load, 300); return () => clearTimeout(timer); }, [page, search, status]); // eslint-disable-line react-hooks/exhaustive-deps
  const filter = async (event: React.FormEvent) => { event.preventDefault(); if (!query.trim()) return; setLoading(true); try { const data = await adminApi.smartFilterVendors(query); setItems(data.items); setTotal(data.total); setSmart(true); } catch { toast.error("AI filter could not complete"); } finally { setLoading(false); } };
  const update = async (record: VendorRegistration, patch: { status?: VendorStatus; internalNotes?: string; statusMessage?: string }) => { try { const saved = await adminApi.updateVendor(record.id, patch); setItems((current) => current.map((item) => item.id === record.id ? saved : item)); toast.success("Vendor record updated"); } catch (cause) { toast.error(cause instanceof Error ? cause.message : "Could not update vendor"); } };
  const remove = async (record: VendorRegistration) => { if (!confirm(`Permanently delete ${record.companyName} and all uploaded verification documents? This cannot be undone.`)) return; try { await adminApi.deleteVendor(record.id); setItems((current) => current.filter((item) => item.id !== record.id)); setTotal((value) => value - 1); toast.success("Vendor record and documents deleted"); } catch (cause) { toast.error(cause instanceof Error ? cause.message : "Could not delete vendor"); } };
  return <div className="space-y-6"><header><h1 className="flex items-center gap-2 text-2xl font-bold"><Building2 className="h-6 w-6 text-primary" />Vendor verification</h1><p className="mt-1 text-sm text-muted-foreground">{total} company registrations with due-diligence documents and review history.</p></header>
    <form onSubmit={filter} className="flex gap-2 rounded-xl border bg-card p-3"><BrainCircuit className="mt-2.5 h-5 w-5 text-primary" /><input value={query} onChange={(event) => setQuery(event.target.value)} className="min-w-0 flex-1 bg-transparent px-2 text-sm outline-none" placeholder="Ask AI: Show approved localization vendors in Southeast Asia with 5+ years’ experience" /><Button disabled={loading}>Smart filter</Button></form>
    <div className="flex flex-col gap-3 sm:flex-row"><label className="relative flex-1"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground" /><input value={search} onChange={(event) => { setSearch(event.target.value); setPage(1); }} className="w-full rounded-lg border bg-background py-2.5 pl-9 pr-3 text-sm" placeholder="Search company, country, service, registration…" /></label><select value={status} onChange={(event) => { setStatus(event.target.value); setPage(1); }} className="rounded-lg border bg-background px-4 py-2 text-sm"><option value="all">All statuses</option>{statuses.map((value) => <option key={value}>{value}</option>)}</select>{smart && <Button variant="outline" onClick={load}>Clear AI filter</Button>}</div>
    {loading ? <Loader2 className="mx-auto my-20 h-8 w-8 animate-spin text-primary" /> : items.length === 0 ? <div className="rounded-xl border bg-card py-16 text-center text-muted-foreground">No matching vendor records.</div> : <div className="space-y-4">{items.map((record) => <VendorCard key={record.id} record={record} onUpdate={update} onDelete={remove} />)}</div>}
    {!smart && total > 15 && <div className="flex items-center justify-end gap-3"><Button variant="outline" size="sm" disabled={page === 1} onClick={() => setPage((value) => value - 1)}><ChevronLeft className="h-4 w-4" />Previous</Button><span className="text-sm">Page {page} of {Math.ceil(total / 15)}</span><Button variant="outline" size="sm" disabled={page >= Math.ceil(total / 15)} onClick={() => setPage((value) => value + 1)}>Next<ChevronRight className="h-4 w-4" /></Button></div>}
  </div>;
}

function VendorCard({ record, onUpdate, onDelete }: { record: VendorRegistration; onUpdate: (record: VendorRegistration, patch: { status?: VendorStatus; internalNotes?: string; statusMessage?: string }) => void; onDelete: (record: VendorRegistration) => void }) {
  const [notes, setNotes] = useState(record.internalNotes);
  const download = async (kind: "registration" | "tax", index: number | undefined, filename: string) => { try { await adminApi.downloadVendorDocument(record.id, kind, index, filename); } catch (cause) { toast.error(cause instanceof Error ? cause.message : "Could not download document"); } };
  const changeStatus = (next: VendorStatus) => { const statusMessage = next === "hold" ? prompt("Why is this registration on hold? This message will be emailed to the company.", record.statusMessage || "") : ""; if (next === "hold" && !statusMessage?.trim()) return; onUpdate(record, { status: next, statusMessage: statusMessage || "" }); };
  return <article className="rounded-xl border bg-card p-5 shadow-sm"><div className="flex flex-col justify-between gap-5 lg:flex-row"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-3"><h2 className="text-lg font-bold">{record.companyName}</h2><span className="rounded-full bg-primary/10 px-2.5 py-1 text-xs font-semibold capitalize text-primary">{record.status}</span><span className="font-mono text-xs text-muted-foreground">{record.receiptId}</span></div><a className="mt-3 flex items-center gap-1 text-sm text-muted-foreground hover:text-primary" href={`mailto:${record.email}`}><Mail className="h-4 w-4" />{record.contactName} · {record.email}</a><dl className="mt-5 grid gap-4 text-sm sm:grid-cols-2 lg:grid-cols-3"><Info label="Country" value={record.country} /><Info label="Registration" value={record.registrationNumber} /><Info label="Tax ID" value={record.taxNumber} /><Info label="Years / team" value={`${record.yearsInBusiness || 0} years · ${record.teamSize || "Not stated"}`} /><Info label="Services" value={record.services.join(", ")} /><Info label="Capabilities" value={record.capabilitySummary} /></dl></div>
      <div className="w-full space-y-3 border-t pt-4 lg:w-80 lg:border-l lg:border-t-0 lg:pl-5 lg:pt-0"><button type="button" onClick={() => download("registration", undefined, record.registrationDocument.originalName || "registration-document")} className="flex w-full items-center gap-2 rounded-lg border px-3 py-2 text-sm hover:bg-muted"><Download className="h-4 w-4" />Registration document</button>{record.taxReturns.map((file, index) => <button type="button" key={file.url} onClick={() => download("tax", index, file.originalName || `tax-document-${index + 1}`)} className="flex w-full items-center gap-2 rounded-lg border px-3 py-2 text-sm hover:bg-muted"><Download className="h-4 w-4" />Tax document {index + 1}</button>)}<select value={record.status} onChange={(event) => changeStatus(event.target.value as VendorStatus)} className="w-full rounded-lg border bg-background px-3 py-2 text-sm">{statuses.map((value) => <option key={value}>{value}</option>)}</select><textarea value={notes} onChange={(event) => setNotes(event.target.value)} className="min-h-24 w-full resize-y rounded-lg border bg-background p-3 text-sm" placeholder="Private review remark" /><Button variant="outline" className="w-full" onClick={() => onUpdate(record, { internalNotes: notes })}><Save className="mr-2 h-4 w-4" />Save remark</Button>{record.status === "rejected" && <Button variant="ghost" className="w-full text-red-600 hover:bg-red-50 hover:text-red-700" onClick={() => onDelete(record)}><Trash2 className="mr-2 h-4 w-4" />Delete permanently</Button>}</div></div></article>;
}
function Info({ label, value }: { label: string; value?: string }) { return value ? <div><dt className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">{label}</dt><dd className="mt-1 leading-6">{value}</dd></div> : null; }
