import { useQuery } from '@tanstack/react-query';
import { Link } from 'react-router-dom';
import { Helmet } from 'react-helmet-async';
import { fetchEventPhotos } from '@/admin/lib/eventMediaApi';
import type { EventData } from './eventsData';
export default function CountryEventGallery({event,heading,intro,eyebrow}:{event:EventData;heading?:string;intro?:string;eyebrow?:string}){
 const {data:photos=[],isLoading,isError}=useQuery({queryKey:['event-photos',event.slug],queryFn:()=>fetchEventPhotos(event.slug),staleTime:30000,retry:false});
 return <section id="event-gallery" className="events-section events-shell event-country-gallery"><p className="events-eyebrow">{eyebrow || `${heading ? '04 / ' : ''}MOMENTS FROM ${event.country.toUpperCase()}`}</p><h2>{heading || `${event.title} Photos & Stories`}</h2><p className="text-sm text-slate-500 mt-4 mb-8">{intro || 'Published photos and stories from this tour.'}</p>{photos.length?<><Helmet><script type="application/ld+json">{JSON.stringify({'@context':'https://schema.org','@type':'ImageGallery',name:`${event.title} Photos`,associatedMedia:photos.map(p=>({'@type':'ImageObject',name:p.title,description:p.description,caption:p.imageAlt,contentUrl:p.imageUrl,url:`https://www.eqourse.com/events/${event.slug}/highlights/${p.slug}`,width:p.width,height:p.height,datePublished:p.publishedAt}))}).replace(/</g,'\\u003c')}</script></Helmet><div className="events-gallery">{photos.map(photo=><article key={photo.id}><Link to={`/events/${event.slug}/highlights/${photo.slug}`} className="gallery-frame block"><img src={photo.imageUrl} alt={photo.imageAlt} title={photo.imageTitle} loading="lazy" decoding="async" width={photo.width||800} height={photo.height||600}/></Link><div className="event-photo-caption"><h3><Link to={`/events/${event.slug}/highlights/${photo.slug}`}>{photo.title}</Link></h3><p>{photo.description}</p></div></article>)}</div></>:<div className="event-gallery-empty" role="status">{isLoading?'Loading tour highlights…':isError?'Tour highlights are temporarily unavailable. Please check back shortly.':'Verified photos and stories will appear here when published for this tour.'}</div>}</section>;
}
