export interface PrivacySection {
  id: string;
  number: string;
  title: string;
  content: string[];
}

export const LAST_UPDATED = "April 2026";

export const privacySections: PrivacySection[] = [
  {
    id: "introduction",
    number: "1",
    title: "Introduction",
    content: [
      'This Privacy Policy explains how eQOURSE ("we", "us", "our") collects, uses, stores, shares, and protects personal information when you use our website (https://www.eqourse.com), our services, our platforms, and any related applications.',
      "eQOURSE operates as two legal entities:",
      "• **eQOURSE (India)** — Registered office: C-29, Indra Vihar, Shiv Jyoti School Road, Kota, Rajasthan, India — 324005. A DPIIT-recognised startup registered under the laws of India.",
      "• **eQOURSE PTE LTD (Singapore)** — Registered office: 760 Bedok Reservoir Road, #04-13, Waterfront Waves, Singapore — 479245. Registered under the laws of Singapore.",
      "We are certified under **ISO 9001:2015** (Quality Management) and **ISO 27001:2022** (Information Security Management). This policy applies to all personal data processed by both entities across our two service verticals: EdTech Solutions and AI Data Services.",
      "By using our website or engaging our services, you acknowledge that you have read, understood, and agree to the practices described in this Privacy Policy. If you do not agree, please do not use our website or services.",
    ],
  },
  {
    id: "definitions",
    number: "2",
    title: "Definitions",
    content: [
      '**"Personal Data"** means any information that identifies or can be used to identify an individual, including but not limited to name, email address, phone number, IP address, device identifiers, and any other information defined as personal data under applicable data protection laws.',
      '**"Client Data"** means any data, content, files, datasets, or materials provided by our clients for the purpose of receiving EdTech content or AI Data services. Client data is owned by the client and processed by eQOURSE solely under the client\'s instructions.',
      '**"Contributor Data"** means data provided by individuals who participate in our data collection activities (e.g., providing speech recordings, handwriting samples, or text contributions for AI training datasets). Contributors provide explicit consent before participation.',
      '**"Annotation Data"** means labeling, tagging, or classification metadata added to client datasets by our annotation team as part of AI Data Services.',
      '**"TuTrain Data"** means interaction data generated when users test AI models through our TuTrain real-world model testing platform.',
      '**"Website Visitor Data"** means data collected when individuals visit our website, including IP addresses, browser information, pages viewed, and form submissions.',
    ],
  },
  {
    id: "information-we-collect",
    number: "3",
    title: "Information We Collect",
    content: [
      "### 3.1 Information You Provide Directly",
      "We collect personal information that you voluntarily provide when you interact with us:",
      "• **Contact Form Submissions:** full name, email address, phone number, company name, designation, service interest, project description, and preferred call date/time.",
      "• **Free Pilot Requests:** full name, work email, company name, designation, pilot type, service detail, language requirements, project description, and uploaded reference files.",
      "• **Newsletter Subscriptions:** email address.",
      "• **Career Applications:** full name, email, phone, resume/CV, cover letter, department preference, and any information included in your application.",
      "• **Client Onboarding:** company details, billing information, project specifications, NDA signatures, and authorised contact details.",
      "### 3.2 Information Collected Automatically",
      "When you visit our website, we automatically collect certain information through cookies and similar technologies:",
      "• **Log Data:** IP address, browser type and version, operating system, referring URL, pages visited, time spent on pages, date and time of visit.",
      "• **Device Information:** device type (desktop, mobile, tablet), screen resolution, language settings.",
      "• **Cookies and Tracking Technologies:** session cookies (for website functionality), persistent cookies (for analytics and preferences), and third-party cookies (Google Analytics). See Section 8 for full cookie details.",
      "### 3.3 Client Data (EdTech Services)",
      "When clients engage our EdTech services, they may provide us with educational content, curriculum materials, assessment data, student performance data, or other educational materials for the purpose of content development, localisation, or LMS integration. This data is processed solely on the client's behalf and under the client's instructions.",
      "### 3.4 Client Data (AI Data Services)",
      "When clients engage our AI Data Services, they may provide us with datasets (text, images, audio, video) for annotation, labeling, cleaning, or validation. This data may contain personal information. We process this data solely on the client's behalf, under the client's instructions, and in accordance with data processing agreements (DPAs) signed with each client.",
      "### 3.5 Contributor Data (Data Collection Services)",
      "When individuals participate in our data collection activities, we collect:",
      "• **Consent documentation:** informed consent forms signed before participation.",
      "• **Demographic metadata:** age range, gender, geographic region, education level, and language/dialect — collected for dataset diversity and AI model fairness.",
      "• **Contribution data:** the speech recordings, handwriting images, text contributions, or other data provided by the contributor.",
      "All contributor data is collected with explicit, informed consent. Contributors are informed of the purpose of data collection, how their data will be used, and their rights to withdraw consent at any time.",
      "### 3.6 TuTrain Platform Data",
      "When users interact with AI models on our TuTrain real-world model testing platform, we collect interaction logs (queries submitted, responses received, task completion metrics, and user feedback). Personal identifiers are separated from interaction data before being shared with clients.",
    ],
  },
  {
    id: "how-we-use-information",
    number: "4",
    title: "How We Use Your Information",
    content: [
      "We use the information we collect for the following purposes:",
      "• To respond to your inquiries and provide customer support (contact form and pilot request submissions).",
      "• To deliver contracted EdTech content services (curriculum development, content creation, localisation, video production, assessment development, LMS integration, and SME services).",
      "• To deliver contracted AI Data services (data collection, annotation, labeling, cleaning, validation, and real-world model testing).",
      "• To process career applications and recruitment.",
      "• To send newsletters and marketing communications (only with your explicit opt-in consent; you can unsubscribe at any time).",
      "• To improve our website, services, and user experience through analytics.",
      "• To comply with legal obligations, resolve disputes, and enforce our agreements.",
      "• To maintain information security and prevent fraud.",
    ],
  },
  {
    id: "lawful-basis",
    number: "5",
    title: "Lawful Basis for Processing",
    content: [
      "We process personal data on the following lawful bases:",
      "• **Consent:** for newsletter subscriptions, marketing communications, contributor data collection, and TuTrain participation. You may withdraw consent at any time by contacting us at info@eqourse.com.",
      "• **Contractual Necessity:** for processing data necessary to deliver our services to clients under signed agreements and SOWs.",
      "• **Legitimate Interests:** for website analytics, service improvement, and security monitoring, where our interests do not override your rights.",
      "• **Legal Obligation:** for compliance with tax, regulatory, and legal requirements in India and Singapore.",
    ],
  },
  {
    id: "information-sharing",
    number: "6",
    title: "Information Sharing and Disclosure",
    content: [
      "We do not sell, rent, trade, or otherwise disclose your personal information to third parties for their marketing purposes. We share information only in the following circumstances:",
      "### 6.1 With Service Providers",
      "We use a limited number of third-party service providers to support our operations:",
      "• **Google Analytics:** for website analytics (anonymised IP, usage data).",
      "• **Email service providers:** for sending transactional emails and newsletters.",
      "• **Cloud infrastructure providers:** for secure data storage and processing.",
      "• **Payment processors:** for billing and invoicing (we do not store credit card numbers directly).",
      "All service providers are bound by data processing agreements and are prohibited from using your data for any purpose other than providing services to eQOURSE.",
      "### 6.2 With Clients (AI Data Services Only)",
      "When we deliver annotated datasets or model testing results to our AI Data Services clients, we share the processed data as specified in the client's data processing agreement. Personal identifiers from contributor or TuTrain data are separated from delivered datasets unless the client's project specifically requires demographic metadata, in which case contributors have provided explicit consent.",
      "### 6.3 Legal Requirements",
      "We may disclose your information if required to do so by law, regulation, legal process, or governmental request.",
      "### 6.4 Business Transfers",
      "In the event of a merger, acquisition, or sale of all or a portion of our assets, your personal information may be transferred as part of the transaction. We will notify you of any such change in ownership or control.",
    ],
  },
  {
    id: "data-security",
    number: "7",
    title: "Data Security",
    content: [
      "We take data security seriously and implement comprehensive technical and organisational measures to protect your personal information:",
      "• **ISO 27001:2022 Certification:** our information security management system is certified and audited annually.",
      "• **Encryption:** all data in transit is encrypted using TLS 1.2 or higher. Data at rest is encrypted using AES-256 encryption.",
      "• **Access Controls:** role-based access controls ensure that only authorised personnel can access personal data.",
      "• **NDA Protection:** all employees, contractors, and annotators sign non-disclosure agreements before accessing any client or personal data.",
      "• **Network Security:** firewalls, intrusion detection systems, and regular vulnerability assessments protect our infrastructure.",
      "• **Client Data Isolation:** client datasets are logically separated. Data from one client is never accessible to another client's project team.",
      "• **PII Detection and Redaction:** automated and manual PII detection and redaction protocols are applied to AI training datasets where required.",
      "• **Audit Trails:** full audit logs are maintained for data access, modification, and deletion activities.",
      "• **Employee Training:** all team members receive regular training on data protection, information security, and privacy awareness.",
    ],
  },
  {
    id: "cookies",
    number: "8",
    title: "Cookies and Tracking Technologies",
    content: [
      "Our website uses cookies and similar tracking technologies. A cookie is a small text file stored on your device when you visit our website.",
      "### 8.1 Types of Cookies We Use",
      "• **Strictly Necessary Cookies:** required for the website to function (e.g., session management, security). These cannot be disabled.",
      "• **Analytics Cookies:** Google Analytics cookies that collect anonymised usage data (pages visited, time on site, traffic sources). Your IP address is anonymised before processing.",
      "• **Functional Cookies:** remember your preferences (e.g., language, region) for a better user experience.",
      "• **Marketing Cookies:** used only if you opt in, to measure the effectiveness of our advertising campaigns.",
      "### 8.2 Managing Cookies",
      "You can manage or disable cookies through your browser settings. Most browsers allow you to block or delete cookies. However, disabling cookies may affect the functionality of our website. You can also opt out of Google Analytics by installing the Google Analytics Opt-Out Browser Add-on.",
    ],
  },
  {
    id: "data-retention",
    number: "9",
    title: "Data Retention",
    content: [
      "We retain personal data only for as long as necessary to fulfil the purposes described in this policy:",
      "• **Contact form and pilot request data:** retained for 24 months after the last interaction, then deleted.",
      "• **Newsletter subscriber data:** retained until you unsubscribe, then deleted within 30 days.",
      "• **Career application data:** retained for 12 months after the application date, then deleted unless you request earlier deletion.",
      "• **Client project data (EdTech):** retained for the duration of the client engagement plus 12 months, then securely deleted unless the client requests extended retention.",
      "• **Client project data (AI Data):** retained for the duration of the client engagement. Upon project completion, all client data is securely deleted within 30 days unless the client requests extended retention or earlier deletion.",
      "• **Contributor data:** retained for the duration specified in the contributor's consent agreement. Contributors may request deletion at any time.",
      "• **TuTrain interaction data:** de-identified interaction logs may be retained for service improvement. Personal identifiers are deleted within 90 days of project completion.",
      "• **Website analytics data:** anonymised analytics data is retained for 26 months (Google Analytics default), then automatically deleted.",
    ],
  },
  {
    id: "your-rights",
    number: "10",
    title: "Your Rights",
    content: [
      "Depending on your location and applicable laws, you may have the following rights regarding your personal data:",
      "• **Right of Access:** you can request a copy of the personal data we hold about you.",
      "• **Right to Rectification:** you can request that we correct inaccurate or incomplete personal data.",
      "• **Right to Erasure (Right to Be Forgotten):** you can request that we delete your personal data, subject to legal retention obligations.",
      "• **Right to Restriction:** you can request that we restrict the processing of your personal data in certain circumstances.",
      "• **Right to Data Portability:** you can request a copy of your personal data in a structured, commonly used, machine-readable format.",
      "• **Right to Object:** you can object to the processing of your personal data based on legitimate interests or for direct marketing purposes.",
      "• **Right to Withdraw Consent:** where processing is based on consent, you can withdraw consent at any time without affecting the lawfulness of prior processing.",
      "To exercise any of these rights, contact us at **info@eqourse.com**. We will respond to your request within 30 days.",
    ],
  },
  {
    id: "international-transfers",
    number: "11",
    title: "International Data Transfers",
    content: [
      "As eQOURSE operates across India and Singapore, your personal data may be transferred between our offices in these countries. We ensure that all cross-border transfers are protected by:",
      "• Data processing agreements with standard contractual clauses where required.",
      "• ISO 27001-certified security controls applied uniformly across all offices.",
      "• Encryption of data in transit between jurisdictions.",
      "• Compliance with applicable data protection laws in both India (IT Act 2000, DPDP Act 2023) and Singapore (PDPA).",
    ],
  },
  {
    id: "childrens-privacy",
    number: "12",
    title: "Children's Privacy",
    content: [
      "Our website and services are not directed to children under the age of 16. We do not knowingly collect personal information from children under 16. If we become aware that we have collected personal data from a child under 16 without parental consent, we will delete that information promptly. If you believe we have inadvertently collected information from a child, please contact us at **info@eqourse.com**.",
      "**Note:** While our EdTech services create educational content for K-12 students, the content is created for and delivered to our institutional clients (schools, platforms, publishers) — not directly to students. We do not interact with or collect data from students directly.",
    ],
  },
  {
    id: "data-breach",
    number: "13",
    title: "Data Breach Notification",
    content: [
      "In the event of a personal data breach that poses a risk to the rights and freedoms of individuals, eQOURSE will:",
      "• Notify the affected individuals within 72 hours of becoming aware of the breach.",
      "• Notify the relevant supervisory authority as required by applicable law.",
      "• Notify affected clients within 48 hours if the breach involves client data.",
      "• Document the breach, its effects, and the remedial actions taken.",
      "• Conduct a post-breach review and implement measures to prevent recurrence.",
    ],
  },
  {
    id: "third-party-links",
    number: "14",
    title: "Third-Party Links",
    content: [
      "Our website may contain links to third-party websites, services, or platforms. We are not responsible for the privacy practices or content of these third-party sites. We encourage you to read the privacy policies of any third-party websites you visit. Links to third-party sites do not constitute endorsement by eQOURSE.",
    ],
  },
  {
    id: "changes",
    number: "15",
    title: "Changes to This Privacy Policy",
    content: [
      "eQOURSE reserves the right to update or modify this Privacy Policy at any time. When we make material changes, we will:",
      '• Update the "Last Updated" date at the top of this page.',
      "• Post a notice on our website for 30 days after any material change.",
      "• Notify registered users by email if the change materially affects how we handle their data.",
      "We encourage you to review this page periodically to stay informed about how we protect your information.",
    ],
  },
  {
    id: "contact-us",
    number: "16",
    title: "Contact Us",
    content: [
      "If you have questions, concerns, or complaints about this Privacy Policy or our data practices, please contact us:",
      "**Email:** info@eqourse.com",
      "**Phone:** +91 92144-45870",
      "**India Office:** eQOURSE, C-29, Indra Vihar, Shiv Jyoti School Road, Kota, Rajasthan, India — 324005",
      "**Singapore Office:** eQOURSE PTE LTD, 760 Bedok Reservoir Road, #04-13, Waterfront Waves, Singapore — 479245",
      "We aim to resolve all privacy-related inquiries within 30 days of receipt.",
    ],
  },
];
