import { Helmet } from "react-helmet-async";
import RelatedBlogs from "@/components/blog/RelatedBlogs";
import { HeartHandshake, Scale, ShieldCheck } from "lucide-react";
import AIDataServicesLayout from "../../shared/AIDataServicesLayout";
import SEOHead from "../../shared/SEOHead";
import ServiceHero from "../../shared/ServiceHero";
import FAQSection from "../../shared/FAQSection";
import ServiceCTA from "../../shared/ServiceCTA";
import { ContextAppeals, DeclinedWork, HumanAutomation, ModerationDefinition, ModerationProcess, ModerationQuality, ModerationRelated, ModerationServices, ModeratorSafeguards, OperationsDelivery, PolicyTaxonomy } from "./ContentModerationCoreSections";

const canonical = "https://www.eqourse.com/ai-data-services/annotation-labeling/content-moderation";
const faqPairs = [
  ["What is content moderation?", "Content moderation is the review of user-generated content against a platform policy and the decision about what happens to it—leave, remove, restrict, age-gate, demonetise or escalate. Automation handles most volume; human moderators handle context-dependent and borderline cases."],
  ["What types of content can eQOURSE moderate?", "Text and comments, images, video, audio, profiles and identity documents, marketplace listings, advertising creative, and spam, scam and fraud detection across 30+ languages."],
  ["What is the difference between content moderation and building a moderation model?", "Labeling a corpus to train a safety classifier is a finite annotation project. Running a live queue against policy is an ongoing operation with coverage hours, latency targets and escalation paths. Many platforms need both."],
  ["Why do we need human moderators if we have automated filters?", "Automation should handle the bulk. Human review is most valuable near the classifier decision threshold, in context-dependent cases, for novel harm patterns and for appeals that require independent reasoning."],
  ["How do you protect moderator wellbeing?", "Safeguards include capped exposure in high-severity queues, mandatory rotation, proactive confidential clinical support, exposure-reducing tools, an unconditional right to step away, informed consent, peer debriefs and trained supervisors. Unsafe queue configurations are declined."],
  ["How do you measure moderation accuracy?", "False positives and false negatives are reported separately, with per-category precision and recall, agreement on borderline cases, appeal overturn rates, hidden gold cases, senior adjudication, SLA latency and historical consistency checks."],
  ["What is a severity tier and why does it matter?", "Severity tiers grade how serious a violation is within a category so proportionate action can be applied. Each category-tier combination maps to a defined outcome and uncertain cases have an explicit escalation path."],
  ["Do you handle child sexual abuse material?", "No. eQOURSE does not accept CSAM review or classification work. It must be handled by organisations specifically licensed, trained and legally structured for it with the relevant authorities. Incidentally encountered content follows a pre-agreed escalation protocol."],
  ["Can you moderate in languages other than English?", "Yes. Moderation is available across 30+ global languages with native speakers and strong coverage across India's regional languages, dialects, code-mixed and romanised content."],
  ["Do you work in our moderation tooling?", "Yes. We can work inside your queue system with your access controls, or in a managed platform where you do not have one."],
  ["Can you provide 24/7 coverage?", "Yes. Business-hours, extended-hours or 24/7 coverage can be designed across time zones, with peak volumes agreed in advance and latency SLAs set by severity."],
  ["Can you help us write our content policy?", "Yes. Policy taxonomy design covers categories, severity tiers, action mapping, context modifiers and worked examples, stress-tested against representative content before launch."],
  ["How much does content moderation cost?", "Pricing may be per item, per moderator FTE or a monthly retainer. Cost depends on volume, content type, complexity, severity mix, coverage, latency, languages, appeals, policy maturity and security."],
  ["Can moderation decisions improve our automated systems?", "Yes. Moderator decisions can be returned as labeled training data, particularly for the uncertain decision boundary where classifiers are weakest."],
  ["How do we start?", "Share your policy, a representative content sample and volume profile. We stress-test the taxonomy, run a pilot with measured agreement and latency, and scope a safely staffed operation."],
] as const;
const faqs = faqPairs.map(([question, answer]) => ({ question, answer }));
const offers = ["Text and Comment Moderation","Image Moderation","Video Moderation","Audio Moderation","Profile and Identity Review","Marketplace and Listing Moderation","Spam, Scam and Fraud Detection","Brand Safety and Ad Review","Appeals and Escalation Review","Policy Taxonomy Design","Multilingual Content Moderation"];
const schema = {"@context":"https://schema.org","@graph":[{"@type":"Service","@id":`${canonical}#service`,name:"Content Moderation & Trust and Safety Services",serviceType:"Content Moderation and Trust and Safety",url:canonical,description:"Human content moderation across text, image, video and audio with severity-tiered enforcement, appeals review, multilingual context and moderator wellbeing safeguards.",provider:{"@type":"Organization",name:"eQOURSE",url:"https://www.eqourse.com/",address:[{"@type":"PostalAddress",addressCountry:"IN"},{"@type":"PostalAddress",addressCountry:"SG"}]},areaServed:"Worldwide",availableLanguage:["en","hi","bn","ta","te","mr","gu","kn","ml","pa","or","as","ur","es","fr","de","pt","ar","zh","ja","ko","id","th","vi"],isPartOf:{"@type":"Service","@id":"https://www.eqourse.com/ai-data-services/annotation-labeling#service",name:"Data Annotation & Labeling Services",url:"https://www.eqourse.com/ai-data-services/annotation-labeling"},hasOfferCatalog:{"@type":"OfferCatalog",name:"Content Moderation Services",itemListElement:offers.map(name=>({"@type":"Offer",itemOffered:{"@type":"Service",name}}))}},{"@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"Home",item:"https://www.eqourse.com/"},{"@type":"ListItem",position:2,name:"AI Data Services",item:"https://www.eqourse.com/ai-data-services"},{"@type":"ListItem",position:3,name:"Data Annotation & Labeling",item:"https://www.eqourse.com/ai-data-services/annotation-labeling"},{"@type":"ListItem",position:4,name:"Content Moderation",item:canonical}]},{"@type":"FAQPage",mainEntity:faqs.map(({question,answer})=>({"@type":"Question",name:question,acceptedAnswer:{"@type":"Answer",text:answer}}))}]};

const ContentModerationPage = () => <AIDataServicesLayout breadcrumbs={[{label:"AI Data Services",href:"/ai-data-services"},{label:"Data Annotation & Labeling",href:"/ai-data-services/annotation-labeling"},{label:"Content Moderation"}]}>
  <SEOHead title="Content Moderation & Trust and Safety Services | eQOURSE" description="Human content moderation with severity-tiered enforcement, appeals review, multilingual context and moderator wellbeing safeguards across 30+ languages." canonical={canonical} keywords="content moderation services, content moderation outsourcing, trust and safety services, UGC moderation services, image moderation services, video content moderation, multilingual content moderation" ogImage="https://www.eqourse.com/assets/ai-data/annotation-labeling/content-moderation/content-moderation-og.webp"/>
  <Helmet><link rel="preload" as="image" href="/assets/ai-data/annotation-labeling/content-moderation/content-moderation-trust-safety-services-hero.avif" type="image/avif" fetchPriority="high"/><script type="application/ld+json">{JSON.stringify(schema)}</script></Helmet>
  <ServiceHero tone="dark" preHeadline="Human Judgment for the Decisions That Matter" headline="Content Moderation & Trust and" headlineAccent="Safety Services" subtext="Human moderation across text, image, video and audio—severity-tiered policy enforcement, appeals and escalation in 30+ languages, delivered with cultural context and moderator safeguards." ctaText="Start Free Pilot" ctaLink="/free-pilot" secondaryCtaText="Talk to a Trust & Safety Specialist" secondaryCtaLink="/contact-us" imageSrc="/assets/ai-data/annotation-labeling/content-moderation/content-moderation-trust-safety-services-hero.webp" imageAvifSrc="/assets/ai-data/annotation-labeling/content-moderation/content-moderation-trust-safety-services-hero.avif" imageAlt="Content moderator reviewing a queue of flagged items with policy categories and severity levels displayed" imageWidth={1200} imageHeight={800} trustStats={[{value:"30+ languages",label:"Regional + cultural context"},{value:"Severity-tiered",label:"Proportionate enforcement"},{value:"Safeguarded",label:"Exposure limits + rotation"}]} rotatingBadges={[{icon:Scale,title:"Policy-led",subtitle:"Category · Severity · Action",color:"hsl(165 72% 58%)"},{icon:HeartHandshake,title:"People protected",subtitle:"Rotation · Support · Consent",color:"hsl(35 92% 62%)"},{icon:ShieldCheck,title:"Decisions measured",subtitle:"FP · FN · Appeals · SLA",color:"hsl(205 78% 66%)"}]} bottomBadge={{iconText:"T&S",title:"Context at the decision boundary",subtitle:"Human review · Reasoning · Escalation"}}/>
  <ModerationDefinition/><ModerationServices/><PolicyTaxonomy/><ModeratorSafeguards/><HumanAutomation/><ModerationProcess/><ModerationQuality/><ContextAppeals/><DeclinedWork/><OperationsDelivery/><ModerationRelated/>
  <RelatedBlogs />
  <FAQSection faqs={faqs} label="Trust & Safety FAQs" title="Frequently Asked Questions About Content Moderation"/>
  <ServiceCTA headline="Build a Moderation Operation That Holds Up" subtext="Share your policy and a representative content sample—we'll stress-test the taxonomy, run a measured pilot and scope coverage that can be staffed safely." ctaText="Start Free Pilot" ctaLink="/free-pilot" secondaryCtaText="Talk to a Trust & Safety Specialist" secondaryCtaLink="/contact-us" note="Pilot includes taxonomy review, agreement, accuracy and latency measurement"/>
</AIDataServicesLayout>;

export default ContentModerationPage;
