import { type ReactNode } from "react";
import { Helmet } from "react-helmet-async";
import { Link } from "react-router-dom";
import { motion, useReducedMotion } from "framer-motion";
import { ArrowRight, ClipboardCheck, Eye, FileCheck2, TimerReset } from "lucide-react";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import AIDataServicesLayout from "../../shared/AIDataServicesLayout";
import SEOHead from "../../shared/SEOHead";
import ServiceCTA from "../../shared/ServiceCTA";
import ServiceHero from "../../shared/ServiceHero";
import RelatedBlogs from "@/components/blog/RelatedBlogs";

const PATH = "/robotics-training-data-services/deployment-validation";
const CANONICAL = `https://www.eqourse.com${PATH}`;
const ASSETS = "/assets/ai-data/robotics/deployment-validation";
const CONTACT = `/contact-us?service=deployment-validation&source=${PATH.slice(1)}#contact-form`;
const DESCRIPTION = "Structured robot deployment validation in the target environment—acceptance testing, endurance observation, human-robot interaction study and incident logging for your evidence pack.";

const standards = [
  ["ISO 10218-1:2025", "In force since 1 April 2025", "Manufacturer-side robot design, inherent safety capability and force-limiting hardware. First revision since 2011."],
  ["ISO 10218-2:2025", "In force since 1 April 2025", "Integrator-side application risk assessment, safeguarding and validation for the specific task. This is the half operational evidence supports."],
  ["ISO/TS 15066:2016", "No longer standalone", "Collaborative-application requirements, including power-and-force limiting, were consolidated into ISO 10218."],
  ["ISO 25785-1", "Draft; publication estimated around 2027", "Actively balanced industrial mobile robots: fall risk, controlled descent, power-loss behaviour and workspace zoning. Supplements ISO 10218."],
  ["ANSI/RIA R15.06 · CSA Z434", "Regional dates vary", "Confirm adoption and applicable obligations with the relevant national body."],
] as const;

const validationRows = [
  ["Task success in situ", "Completion on actual tasks, objects and stations", "Workshop rates rarely survive real product variation"],
  ["Throughput under load", "Sustained cycle time over full shifts", "Operations run all day; demos show a good run"],
  ["Environmental variation", "Lighting, floor, temperature, dust and noise", "The deployment site differs from the integrator floor"],
  ["Recovery and intervention", "Failure response, intervention frequency and recovery time", "Intervention rate determines whether automation saves labour"],
  ["Human-robot interaction", "How people move around, near and with the system", "Real behaviour is more variable than the assessment model"],
  ["Endurance", "Drift, thermal effects, wear and degradation", "Failures at hour six are invisible in a two-hour test"],
  ["Edge cases", "Scheduled obstruction, misplacement and interrupted cycles", "Waiting for rare events means discovering them in production"],
  ["Operator usability", "Start, stop, fault clearance and resumption", "Actual operators must be able to recover the system"],
] as const;

const criteria = [
  "Task success threshold over an agreed number of cycles",
  "Sustained throughput over a full shift—not peak rate",
  "Intervention-rate ceiling and recovery-time limits",
  "Safety-relevant observation and immediate-stop triggers",
  "Environmental conditions explicitly in and out of scope",
  "Duration, cycle counts and what the observed volume can support",
  "The consequence of a failed criterion, agreed before results exist",
] as const;

const failureRows = [
  ["Validated in the workshop", "A valid result about a different application", "Observe at the target site on real tasks"],
  ["Too short", "Habituation, drift and wear appear after the engagement", "Four to eight weeks with an endurance phase"],
  ["Criteria set after results", "Whatever happened becomes the pass mark", "Sign criteria before observation"],
  ["Near-misses omitted", "The leading indicator disappears", "Use a defined severity scale that includes near-misses"],
  ["Observer drift", "Week-one and week-four logs cannot be compared", "Measure agreement at start and re-check it"],
  ["No stated limitations", "The assessor must guess what was not covered", "Put explicit limitations in every evidence pack"],
] as const;

const steps = [
  ["01", "Scope & criteria", "Weeks 1–2", "Acceptance criteria, severity scale, conditions and escalation path."],
  ["02", "Site familiarisation", "Week 2", "Learn normal operation, layout, shifts and people."],
  ["03", "Observer calibration", "Week 2", "Measure classification agreement on a shared sample."],
  ["04", "Baseline observation", "Week 3", "Capture normal operation and the week-one behaviour baseline."],
  ["05", "Structured observation", "Week 3 onward", "Full shifts, agreed cycle counts and scheduled disturbances."],
  ["06", "Endurance phase", "Consecutive days", "Track load, drift, thermal effects and wear."],
  ["07", "Evidence pack", "Final week", "Results, logs, HRI findings, limitations and joint walkthrough."],
] as const;

const faqs = [
  ["What is robot deployment validation?", "Structured observation of a robot system doing its actual job in its actual environment, over enough cycles and time to establish task success, throughput, intervention rate, environmental variation, endurance, edge cases and human behaviour. The output is an evidence pack against pre-agreed acceptance criteria."],
  ["Do you certify robots as safe?", "No. eQOURSE is not a notified body, safety certifier or CE-marking consultancy. We do not issue conformity assessments, sign risk assessments or certify a system as safe. We produce operational evidence for your integrator and assessor."],
  ["Why can’t we rely only on the robot’s certification?", "Because safety is a property of the collaborative application—robot, task, tooling and environment together. The certificate describes the robot; it does not describe your floor, product mix, throughput target or people."],
  ["What changed in ISO 10218:2025?", "ISO 10218-1:2025 and ISO 10218-2:2025 came into force on 1 April 2025. ISO/TS 15066 is no longer standalone; its collaborative-application requirements were consolidated into ISO 10218. Confirm obligations with your assessor and national body."],
  ["What about humanoid and legged robots?", "ISO 25785-1 addresses industrial mobile robots with actively controlled stability, including fall risk, controlled descent and power-loss behaviour. It supplements ISO 10218 and is estimated to publish around 2027."],
  ["How long does validation take?", "Typically four to eight weeks on site, driven by shifts and required cycle counts. Habituation and endurance findings are not observable in a short engagement."],
  ["What is habituation?", "People initially give a new robot wide clearance. Over time they may walk closer, stop looking up or develop workarounds. The robot has not changed, but the operating risk profile has."],
  ["Do you record near-misses?", "Yes. Near-misses, unplanned stops and interventions are logged against a defined severity scale with timestamps, conditions and resolution details."],
  ["How is this different from VLA evaluation?", "VLA evaluation asks how capable a policy is under controlled comparative trials. Deployment validation asks whether this specific application works in this specific place under operational conditions and agreed criteria."],
  ["What if you find something serious?", "It is escalated immediately through the path agreed before day one. We do not continue observing a situation we consider unsafe; we stop and say so."],
] as const;

const schema = { "@context": "https://schema.org", "@graph": [
  { "@type": "Service", "@id": `${CANONICAL}#service`, name: "Robot Deployment Validation", serviceType: "Operational validation and structured observation of robot deployments", description: DESCRIPTION, url: CANONICAL, provider: { "@type": "Organization", name: "eQOURSE", url: "https://www.eqourse.com/" }, areaServed: ["IN", "SG", "AE", "AU", "GB", "EU", "US"], isPartOf: { "@id": "https://www.eqourse.com/robotics-training-data-services#service" }, hasOfferCatalog: { "@type": "OfferCatalog", name: "Deployment validation services", itemListElement: ["Pilot deployment validation", "Site acceptance observation and evidence", "Human-robot interaction observation", "Endurance and habituation study", "Edge case and disturbance testing", "Re-validation after change", "Multi-site rollout validation"].map(name => ({ "@type": "Offer", itemOffered: { "@type": "Service", name } })) } },
  { "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: "https://www.eqourse.com/" }, { "@type": "ListItem", position: 2, name: "Robotics Training Data", item: "https://www.eqourse.com/robotics-training-data-services" }, { "@type": "ListItem", position: 3, name: "Deployment Validation", item: CANONICAL }] },
  { "@type": "FAQPage", mainEntity: faqs.map(([question, answer]) => ({ "@type": "Question", name: question, acceptedAnswer: { "@type": "Answer", text: answer } })) },
] };

const Reveal = ({ children, className = "" }: { children: ReactNode; className?: string }) => { const reduce = useReducedMotion(); return <motion.div className={className} initial={reduce ? false : { opacity: 0, y: 24 }} whileInView={reduce ? undefined : { opacity: 1, y: 0 }} viewport={{ once: true, amount: .08 }} transition={{ duration: .55 }}>{children}</motion.div>; };
const Intro = ({ eyebrow, title, accent, body, light = false }: { eyebrow: string; title: string; accent?: string; body?: string; light?: boolean }) => <div className="max-w-4xl"><p className={`text-xs font-bold uppercase tracking-[.18em] ${light ? "text-teal-300" : "text-primary"}`}>{eyebrow}</p><h2 className={`mt-4 font-heading text-3xl font-bold leading-tight md:text-5xl ${light ? "text-white" : "text-[#15183f]"}`}>{title} {accent && <span className="text-primary">{accent}</span>}</h2>{body && <p className={`mt-5 text-base leading-7 md:text-lg ${light ? "text-white/70" : "text-slate-600"}`}>{body}</p>}</div>;
const Callout = ({ children, dark = false }: { children: ReactNode; dark?: boolean }) => <div className={`mt-8 border-l-4 border-primary p-6 leading-7 ${dark ? "bg-white/[.06] text-white/75" : "bg-primary/[.06] text-slate-700"}`}>{children}</div>;
const Table = ({ headers, rows, caption, dark = false, min = "800px" }: { headers: string[]; rows: readonly (readonly string[])[]; caption: string; dark?: boolean; min?: string }) => <div className={`mt-10 max-w-full overflow-x-auto rounded-3xl border ${dark ? "border-white/10 bg-[#13243d]" : "border-slate-200 bg-white"}`}><table style={{ minWidth: min }} className="w-full border-collapse text-left text-sm"><caption className="sr-only">{caption}</caption><thead className="bg-[#13213a] text-white"><tr>{headers.map(h => <th key={h} scope="col" className="px-5 py-4 font-semibold">{h}</th>)}</tr></thead><tbody>{rows.map((row, i) => <tr key={row[0]} className={dark ? (i % 2 ? "bg-white/[.035]" : "") : (i % 2 ? "bg-slate-50/70" : "bg-white")}>{row.map((cell, j) => j === 0 ? <th key={cell} scope="row" className={`border-t px-5 py-4 font-bold ${dark ? "border-white/10 text-white" : "border-slate-200 text-[#15183f]"}`}>{cell}</th> : <td key={cell} className={`border-t px-5 py-4 leading-6 ${dark ? "border-white/10 text-white/70" : "border-slate-200 text-slate-600"}`}>{cell}</td>)}</tr>)}</tbody></table></div>;

const ApplicationDiagram = () => <div className="max-w-full overflow-x-auto rounded-[2rem] border border-slate-200 bg-[#f8fcfb] p-4"><svg viewBox="0 0 980 500" role="img" aria-labelledby="app-title app-desc" className="h-auto min-w-[720px] w-full"><title id="app-title">A robot application includes robot, task, tooling and environment</title><desc id="app-desc">Four clearly separated elements sit inside one application boundary. Changing any element means the application needs validating again.</desc><rect x="35" y="35" width="910" height="400" rx="34" fill="#fff" stroke="#10a58e" strokeWidth="3"/><text x="75" y="82" fill="#0f766e" fontSize="17" fontWeight="800">THE APPLICATION</text>{[[75,"ROBOT","Certificate covers this","#e5f8f3"],[295,"TASK","What it must do","#eef5ff"],[515,"TOOLING","What it uses","#fff6df"],[735,"ENVIRONMENT","Where people work","#f4efff"]].map(([x,t,d,c])=><g key={t}><rect x={Number(x)} y="135" width="170" height="170" rx="26" fill={String(c)}/><circle cx={Number(x)+34} cy="172" r="8" fill="#10a58e"/><text x={Number(x)+24} y="225" fill="#13213a" fontSize="18" fontWeight="800">{t}</text><text x={Number(x)+24} y="258" fill="#64748b" fontSize="13">{d}</text></g>)}<path d="M140 355 H840" stroke="#f59e0b" strokeWidth="4" strokeDasharray="10 10"/><text x="490" y="392" textAnchor="middle" fill="#9a5b00" fontSize="18" fontWeight="800">Change any one → validate the application again</text></svg></div>;

const HabituationChart = () => <div className="max-w-full overflow-x-auto rounded-[2rem] border border-white/10 bg-[#102038]"><svg viewBox="0 0 980 520" role="img" aria-labelledby="hab-title hab-desc" className="h-auto min-w-[720px] w-full"><title id="hab-title">Illustrative habituation trend over eight weeks</title><desc id="hab-desc">An illustrative line declines from a larger average approach distance in week one to a smaller distance in later weeks. It is a conceptual pattern, not measured client data.</desc><rect width="980" height="520" rx="32" fill="#102038"/><text x="82" y="70" fill="#fff" fontSize="18" fontWeight="800">Average approach distance</text><g stroke="#fff" strokeOpacity=".1">{[130,220,310,400].map(y=><line key={y} x1="95" x2="900" y1={y} y2={y}/>)}</g><path d="M120 130 C260 155 320 215 430 260 S690 350 860 382" fill="none" stroke="#45d8bb" strokeWidth="9" strokeLinecap="round"/><g>{[[120,130,"WEEK 1","ASSESSED HERE"],[430,260,"WEEK 4","OPERATING HERE"],[860,382,"WEEK 8","SUSTAINED VIEW"]].map(([x,y,a,b],i)=><g key={String(a)}><circle cx={Number(x)} cy={Number(y)} r="14" fill={i===0?"#f5a01b":"#45d8bb"}/><line x1={Number(x)} x2={Number(x)} y1={Number(y)+20} y2="430" stroke={i===0?"#f5a01b":"#45d8bb"} strokeDasharray="6 7"/><text x={Number(x)} y="458" textAnchor="middle" fill="#fff" fontSize="15" fontWeight="800">{a}</text><text x={Number(x)} y="480" textAnchor="middle" fill="#fff" fillOpacity=".55" fontSize="12">{b}</text></g>)}</g><text x="80" y="505" fill="#fff" fillOpacity=".5" fontSize="12">Illustrative conceptual pattern—not client measurement or a universal rate of change.</text></svg></div>;

const Process = () => <div className="mt-12"><div className="hidden overflow-x-auto rounded-[2rem] border border-slate-200 bg-[#f8fcfb] p-8 md:block"><div className="grid min-w-[1000px] grid-cols-4 gap-4">{steps.map(([n,t,time,d],i)=><motion.article key={n} whileHover={{ y: -4 }} className={`relative min-h-56 rounded-3xl border p-6 ${i===3?"border-amber-400 bg-amber-50":"border-slate-200 bg-white"}`}><span className={`font-mono text-sm font-bold ${i===3?"text-amber-700":"text-primary"}`}>{n}</span><p className="mt-8 text-xs font-bold uppercase tracking-wider text-slate-400">{time}</p><h3 className="mt-3 font-heading text-xl font-bold text-[#15183f]">{t}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{d}</p>{i===3&&<span className="absolute -bottom-7 left-1/2 -translate-x-1/2 whitespace-nowrap rounded-full bg-amber-500 px-4 py-2 text-xs font-bold text-white">Habituation baseline starts here</span>}</motion.article>)}</div></div><div className="grid gap-3 md:hidden">{steps.map(([n,t,time,d],i)=><article key={n} className={`rounded-2xl border p-6 ${i===3?"border-amber-400 bg-amber-50":"border-slate-200 bg-white"}`}><div className="flex justify-between"><span className="font-mono font-bold text-primary">{n}</span><span className="text-xs font-semibold text-slate-500">{time}</span></div><h3 className="mt-5 font-heading text-xl font-bold text-[#15183f]">{t}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{d}</p>{i===3&&<p className="mt-4 text-xs font-bold uppercase tracking-wider text-amber-700">Habituation baseline starts here</p>}</article>)}</div></div>;

const DeploymentValidationPage = () => <AIDataServicesLayout breadcrumbs={[{ label: "Robotics Training Data", href: "/robotics-training-data-services" }, { label: "Deployment Validation" }]}>
  <SEOHead title="Robot Deployment Validation & Site Testing | eQOURSE" description={DESCRIPTION} canonical={CANONICAL} keywords="robot deployment validation, robot site acceptance testing, operational readiness testing robots, robot pilot validation, robot commissioning support, industrial robot deployment testing, robot soak testing" ogImage={`https://www.eqourse.com${ASSETS}/deployment-validation-hero.webp`}/>
  <Helmet><meta name="robots" content="index, follow, max-image-preview:large"/><link rel="preload" as="image" href={`${ASSETS}/deployment-validation-hero.avif`} type="image/avif" fetchPriority="high"/><script type="application/ld+json">{JSON.stringify(schema)}</script></Helmet>
  <main className="overflow-hidden bg-[#f5faf9]">
    <ServiceHero tone="light" compactHeadline preHeadline="Observe · Measure · Evidence" headline="Robot Deployment" headlineAccent="Validation" subtext="Structured observation of your robot doing its actual job, in the actual place, over enough cycles to mean something. We produce the operational evidence; your integrator and safety assessor produce the safety case." ctaText="Scope a Validation" ctaLink={CONTACT} secondaryCtaText="What We Do and Don’t Sign" secondaryCtaLink="#the-boundary" imageSrc={`${ASSETS}/deployment-validation-hero.webp`} imageAvifSrc={`${ASSETS}/deployment-validation-hero.avif`} imageAlt="Trained observer recording robot cell operation against a structured validation protocol on site" imageWidth={1600} imageHeight={900} trustStats={[{value:"On site",label:"Operational volume"},{value:"Before",label:"Criteria agreed"},{value:"Defined",label:"Severity scale"},{value:"Evidence",label:"Not certification"}]} rotatingBadges={[{icon:Eye,title:"Observed in place",subtitle:"Task · people · environment",color:"hsl(170 82% 38%)"},{icon:TimerReset,title:"Sustained evidence",subtitle:"Shifts · endurance · drift",color:"hsl(28 90% 48%)"},{icon:ClipboardCheck,title:"Acceptance locked",subtitle:"Criteria · fail · escalation",color:"hsl(190 76% 40%)"}]} bottomBadge={{iconText:"SITE",title:"Verify the application",subtitle:"Measured · traceable · bounded"}}/>

    <section className="bg-white py-20 md:py-28"><div className="container mx-auto max-w-7xl px-4"><Reveal><Intro eyebrow="The governing idea" title="You cannot validate a robot." accent="You validate an application." body="Safety belongs to the robot, task, tooling and environment considered together. Change one, and you are validating a different application."/></Reveal><div className="mt-12"><ApplicationDiagram/></div><Callout><strong>This is why validation happens where the robot will run.</strong> A workshop test is genuinely useful evidence about the workshop application—not automatically about yours.</Callout></div></section>

    <section id="the-boundary" className="scroll-mt-32 bg-[#102038] py-20 text-white md:py-28"><div className="container mx-auto max-w-7xl px-4"><Reveal><Intro light eyebrow="Clear responsibility" title="What we do—and" accent="what we don’t sign" body="eQOURSE is not a notified body, safety certifier or CE-marking consultancy. We do not issue conformity assessments, sign risk assessments or certify a system as safe."/></Reveal><Table dark headers={["You · integrator · assessor", "eQOURSE"]} rows={[["Own the risk assessment and safety file","Run the structured observation protocol that generates evidence"],["Define requirements and thresholds","Test against them and report measured results"],["Choose the collaborative technique and safeguarding","Observe performance over full shifts"],["Sign conformity and make the go-live decision","Supply a bounded evidence pack and report what we saw"]]} caption="Responsibility boundary for deployment validation" min="760px"/><Callout dark><strong className="text-amber-300">We produce the operational evidence. Your integrator and assessor produce the safety case.</strong> If you need a notified body, we will say so on the first call.</Callout></div></section>

    <section className="py-20 md:py-28"><div className="container mx-auto max-w-7xl px-4"><Reveal><Intro eyebrow="Current orientation" title="Where the standards" accent="stand" body="Position as of August 2026. This is orientation—not legal or conformity advice. Confirm obligations with your integrator, assessor and relevant national body."/><Table headers={["Standard","Status","Operational relevance"]} rows={standards} caption="Robot safety standards relevant to deployment validation"/><p className="mt-4 text-xs font-semibold text-slate-500">Last reviewed: August 2026 · review scheduled quarterly</p></Reveal></div></section>

    <section className="bg-white py-20 md:py-28"><div className="container mx-auto max-w-7xl px-4"><Reveal><Intro eyebrow="In-site evidence" title="What we" accent="validate" body="The useful question is not whether the demo worked. It is whether the application keeps working under the conditions your operation will impose."/><Table headers={["Dimension","What we observe","Why the real site matters"]} rows={validationRows} caption="Robot deployment validation dimensions"/></Reveal></div></section>

    <section className="bg-[#102038] py-20 text-white md:py-28"><div className="container mx-auto grid max-w-7xl gap-12 px-4 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><Reveal><Intro light eyebrow="Human-robot interaction" title="People change around" accent="a familiar robot" body="Week one behaviour is rarely month-two behaviour. Sustained observation catches habituation, workarounds, bystanders, startle and miscalibrated trust."/><p className="mt-6 leading-7 text-white/68">Risk assessments model human behaviour. Real shifts reveal which assumptions hold, which drift, and what operators do when safe procedures cost time.</p></Reveal><Reveal><HabituationChart/></Reveal></div></section>

    <section className="py-20 md:py-28"><div className="container mx-auto grid max-w-7xl gap-12 px-4 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><Reveal><picture><img src={`${ASSETS}/on-site-observation.avif`} alt="Observers logging events to a defined severity scale during a deployment validation" width="1200" height="675" loading="lazy" decoding="async" className="aspect-video w-full rounded-[2rem] object-cover"/></picture></Reveal><Reveal><Intro eyebrow="Evidence discipline" title="Acceptance criteria before" accent="anything runs" body="A validation without a pre-agreed fail condition is a demonstration. Criteria, escalation and consequences are settled in writing before production observation."/><ul className="mt-8 divide-y divide-slate-200 border-y border-slate-200">{criteria.map((c,i)=><li key={c} className="flex gap-4 py-4"><span className="font-mono text-xs font-bold text-primary">{String(i+1).padStart(2,"0")}</span><span className="font-semibold text-[#15183f]">{c}</span></li>)}</ul></Reveal></div></section>

    <section className="bg-white py-20 md:py-28"><div className="container mx-auto max-w-7xl px-4"><Reveal><Intro eyebrow="Observation to evidence" title="Incident logging that" accent="survives scrutiny" body="A defined severity scale, timestamped conditions and measured observer agreement turn impressions into evidence."/></Reveal><div className="mt-12 grid gap-px overflow-hidden rounded-3xl border border-slate-200 bg-slate-200 md:grid-cols-3">{[["Near-misses","Record the leading indicator, not only contacts."],["Every intervention","Cause, duration, resolver and recovery outcome."],["Environmental context","Lighting, load, shift and condition beside each event."],["Observer agreement","Calibrate on a shared sample and re-check during long studies."],["Immediate escalation","Safety-relevant findings never wait for the final report."],["Explicit limitations","State what the observation did not establish."]].map(([t,d],i)=><article key={t} className="bg-white p-7"><span className="font-mono text-xs font-bold text-primary">0{i+1}</span><h3 className="mt-5 font-heading text-xl font-bold text-[#15183f]">{t}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{d}</p></article>)}</div><Callout><strong>Near-miss data is often the most valuable part of the pack.</strong> It captures the moments existing reporting channels usually miss.</Callout></div></section>

    <section className="py-20 md:py-28"><div className="container mx-auto max-w-7xl px-4"><Reveal><Intro eyebrow="Validation flow" title="How a validation" accent="runs" body="A typical programme runs four to eight weeks on site. The time is intentional: human behaviour, drift and endurance failures need time to appear."/></Reveal><Process/></div></section>

    <section className="bg-[#102038] py-20 text-white md:py-28"><div className="container mx-auto max-w-7xl px-4"><Reveal><Intro light eyebrow="Evidence pack" title="What you get—and" accent="what it is for" body="The pack is structured for your integrator’s application risk assessment and assessor’s file. It is evidence, not a conformity conclusion."/></Reveal><div className="mt-12 grid gap-px overflow-hidden rounded-3xl border border-white/10 bg-white/10 sm:grid-cols-2 lg:grid-cols-3">{["Full observation protocol","Criteria and measured results","Cycle and duration record","Incident and near-miss log","Intervention and recovery analysis","Human-behaviour findings","Environmental variation record","Edge-case results","Observer agreement statistics","Explicit limitations"].map(t=><article key={t} className="bg-[#102038] p-6"><FileCheck2 className="h-5 w-5 text-teal-300"/><p className="mt-4 font-semibold text-white">{t}</p></article>)}</div></div></section>

    <section className="bg-white py-20 md:py-28"><div className="container mx-auto max-w-7xl px-4"><Reveal><Intro eyebrow="Failure prevention" title="Where deployment validation" accent="goes wrong"/><Table headers={["Failure","What happens","Our control"]} rows={failureRows} caption="Common deployment validation failures and controls"/></Reveal></div></section>

    <section className="py-20 md:py-28"><div className="container mx-auto max-w-7xl px-4"><Reveal><Intro eyebrow="Engagement models" title="Five ways" accent="to engage"/></Reveal><div className="mt-12 divide-y divide-slate-200 border-y border-slate-200">{[["Pilot validation","First deployment before wider rollout; usually four to eight weeks on site."],["Site acceptance support","Evidence against agreed criteria aligned with commissioning."],["Re-validation after change","Focused validation after task, tooling, layout, product mix or people change."],["Multi-site rollout","One protocol across sites so local and systemic problems separate cleanly."],["Endurance & habituation","Extended study of drift, wear and changing human behaviour."]].map(([t,d],i)=><article key={t} className="grid gap-3 py-7 md:grid-cols-[3rem_1fr_1.4fr]"><span className="font-mono text-xs font-bold text-primary">0{i+1}</span><h3 className="font-heading text-xl font-bold text-[#15183f]">{t}</h3><p className="leading-7 text-slate-600">{d}</p></article>)}</div></div></section>

    <section className="bg-white py-20 md:py-28"><div className="container mx-auto max-w-7xl px-4"><Reveal><Intro eyebrow="Robotics service map" title="One programme, five" accent="connected service lines"/></Reveal><div className="mt-10 divide-y divide-slate-200 border-y border-slate-200">{[["Human demonstrations","We create the episodes.","/robotics-training-data-services/human-demonstrations"],["Multimodal sensor data","We capture and align the signals.","/robotics-training-data-services/multimodal-sensor-data"],["3D & spatial annotation","We label the world.","/robotics-training-data-services/3d-spatial-annotation"],["VLA evaluation","We score the model.","/robotics-training-data-services/vla-evaluation"],["Deployment validation","We verify it in place.",PATH]].map(([t,d,to],i)=><div key={t} className="grid gap-2 py-6 md:grid-cols-[3rem_1fr_1fr_auto] md:items-center"><span className="font-mono text-xs text-primary">0{i+1}</span><h3 className="font-heading text-xl font-bold text-[#15183f]">{t}</h3><p className="text-slate-600">{d}</p>{to===PATH?<span aria-current="page" className="text-sm font-bold text-primary">Current page</span>:<Link to={to} className="inline-flex items-center gap-1 text-sm font-bold text-primary">Explore <ArrowRight className="h-4 w-4"/></Link>}</div>)}</div><div className="mt-8 flex flex-wrap gap-3"><Link to="/robotics-training-data-services" className="rounded-full border border-primary/25 px-5 py-3 text-sm font-bold text-primary">Robotics training data services</Link><Link to="/ai-data-services/model-testing" className="rounded-full border border-slate-200 px-5 py-3 text-sm font-bold text-[#15183f]">AI Model Testing</Link><Link to="/ai-data-services/data-collection" className="rounded-full border border-slate-200 px-5 py-3 text-sm font-bold text-[#15183f]">Data Collection</Link></div></div></section>

    <RelatedBlogs/>
    <section className="bg-[#102038] py-20 text-white md:py-28"><div className="container mx-auto grid max-w-7xl gap-12 px-4 lg:grid-cols-[.7fr_1.3fr]"><Reveal><Intro light eyebrow="FAQ" title="Deployment validation" accent="questions" body="Direct answers about certification boundaries, standards, duration, habituation, near-misses and escalation."/></Reveal><Reveal><Accordion type="single" collapsible className="divide-y divide-white/10 border-y border-white/10">{faqs.map(([question,answer],i)=><AccordionItem key={question} value={`faq-${i}`} className="border-0"><AccordionTrigger className="py-6 text-left font-heading text-base font-bold text-white hover:text-teal-300 hover:no-underline md:text-lg">{question}</AccordionTrigger><AccordionContent className="pb-6 pr-8 leading-7 text-white/65">{answer}</AccordionContent></AccordionItem>)}</Accordion></Reveal></div></section>

    <ServiceCTA headline="Find Out How It Behaves in Month Two, Not on Demo Day" subtext="Tell us the robot type, site, tasks and go-live date, and whether your integrator and assessor are engaged. We will return with an observation protocol, acceptance criteria worth agreeing and a clear statement of what the evidence will—and will not—establish." ctaText="Scope a Validation" ctaLink={CONTACT} secondaryCtaText="Talk to Our Robotics Team" secondaryCtaLink="/contact-us?service=robotics-team#contact-form" note="Operational evidence · acceptance criteria · incident logging · explicit limitations"/>
  </main>
</AIDataServicesLayout>;

export default DeploymentValidationPage;
