import { type ReactNode } from "react";
import { Helmet } from "react-helmet-async";
import { Link } from "react-router-dom";
import { motion, useReducedMotion } from "framer-motion";
import { ArrowRight, Check, CircleUserRound, Database, FileCheck2, Gauge, RotateCcw, ShieldCheck, UsersRound, Video } from "lucide-react";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import AIDataServicesLayout from "../../shared/AIDataServicesLayout";
import SEOHead from "../../shared/SEOHead";
import ServiceCTA from "../../shared/ServiceCTA";
import ServiceHero from "../../shared/ServiceHero";
import RelatedBlogs from "@/components/blog/RelatedBlogs";
import { collectionMethods, diversityAxes, failureModes, faqs, programmeSteps, qualityDimensions } from "./HumanDemonstrationsContent";

const PATH = "/robotics-training-data-services/human-demonstrations";
const CANONICAL = `https://www.eqourse.com${PATH}`;
const ASSET_ROOT = "/assets/ai-data/robotics/human-demonstrations";
const CONTACT = `/contact-us?service=human-demonstrations&source=${PATH.slice(1)}#contact-form`;

const serviceSchema = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "Service", "@id": `${CANONICAL}#service`, name: "Human Demonstration Data Collection for Robotics",
      serviceType: "Teleoperation and egocentric demonstration data collection for robot learning", url: CANONICAL,
      description: "Teleoperated and egocentric human demonstration data collection for Physical AI and robot learning, with designed diversity, failure and recovery episodes, per-episode QA and LeRobot and RLDS-compatible delivery.",
      provider: { "@type": "Organization", name: "eQOURSE", url: "https://www.eqourse.com/" },
      areaServed: ["IN", "SG", "US", "GB", "AE", "AU", "EU", "JP", "KR"],
      isPartOf: { "@id": "https://www.eqourse.com/robotics-training-data-services#service" },
      hasOfferCatalog: {
        "@type": "OfferCatalog", name: "Demonstration data collection services",
        itemListElement: ["Teleoperation data collection", "Handheld and wrist-mounted rig collection", "Bimanual leader-follower demonstration capture", "VR teleoperation data collection", "Egocentric human demonstration video collection", "Failure and recovery episode collection", "LeRobot and RLDS dataset delivery"].map((name) => ({ "@type": "Offer", itemOffered: { "@type": "Service", name } })),
      },
    },
    {
      "@type": "BreadcrumbList", itemListElement: [
        { "@type": "ListItem", position: 1, name: "Home", item: "https://www.eqourse.com/" },
        { "@type": "ListItem", position: 2, name: "Robotics Training Data", item: "https://www.eqourse.com/robotics-training-data-services" },
        { "@type": "ListItem", position: 3, name: "Human Demonstrations", item: CANONICAL },
      ],
    },
    { "@type": "FAQPage", mainEntity: faqs.map(({ question, answer }) => ({ "@type": "Question", name: question, acceptedAnswer: { "@type": "Answer", text: answer } })) },
  ],
};

const Reveal = ({ children, className = "", delay = 0 }: { children: ReactNode; className?: string; delay?: number }) => {
  const reduce = useReducedMotion();
  return <motion.div className={className} initial={reduce ? false : { opacity: 0, y: 30 }} whileInView={reduce ? undefined : { opacity: 1, y: 0 }} viewport={{ once: true, amount: .12 }} transition={{ duration: .65, delay, ease: [0.22, 1, 0.36, 1] }}>{children}</motion.div>;
};

const Intro = ({ eyebrow, title, accent, body, light = false }: { eyebrow: string; title: string; accent?: string; body?: string; light?: boolean }) => <div className="max-w-3xl">
  <p className={`text-xs font-bold uppercase tracking-[.18em] ${light ? "text-teal-300" : "text-primary"}`}>{eyebrow}</p>
  <h2 className={`mt-4 font-heading text-3xl font-bold leading-tight md:text-5xl ${light ? "text-white" : "text-[#15183f]"}`}>{title} {accent && <span className="text-primary">{accent}</span>}</h2>
  {body && <p className={`mt-5 text-base leading-7 md:text-lg ${light ? "text-white/68" : "text-muted-foreground"}`}>{body}</p>}
</div>;

const DataTable = ({ headers, rows, caption }: { headers: string[]; rows: readonly (readonly string[])[]; caption: string }) => <div className="mt-10 overflow-x-auto rounded-[1.5rem] border border-slate-200 bg-white shadow-[0_24px_70px_rgba(17,31,59,.07)]">
  <table className="w-full min-w-[760px] border-collapse text-left text-sm">
    <caption className="sr-only">{caption}</caption>
    <thead className="bg-[#12223b] text-white"><tr>{headers.map((h) => <th key={h} scope="col" className="px-5 py-4 font-semibold">{h}</th>)}</tr></thead>
    <tbody>{rows.map((row, i) => <tr key={row[0]} className={i % 2 ? "bg-slate-50/75" : "bg-white"}>{row.map((cell, j) => j === 0 ? <th key={cell} scope="row" className="min-w-44 border-t border-slate-200 px-5 py-4 font-bold text-[#15183f]">{cell}</th> : <td key={cell} className="border-t border-slate-200 px-5 py-4 leading-6 text-slate-600">{cell}</td>)}</tr>)}</tbody>
  </table>
</div>;

const DiversityGraphic = () => <svg viewBox="0 0 920 500" role="img" aria-labelledby="diversity-title diversity-desc" className="h-auto w-full">
  <title id="diversity-title">Illustrative comparison of repeated episodes and task diversity</title>
  <desc id="diversity-desc">Episodes of one task rise quickly then flatten around 500 to 1,000, while distinct task types continue to add value.</desc>
  <rect x="1" y="1" width="918" height="498" rx="30" fill="#0f2038"/>
  <g transform="translate(76 50)">
    <text x="0" y="0" fill="#fff" fontSize="18" fontWeight="700">Marginal training value</text>
    <path d="M0 340H760M0 340V28" stroke="#fff" strokeOpacity=".22" strokeWidth="2"/>
    <rect x="208" y="28" width="120" height="312" fill="#ffae35" fillOpacity=".08"/>
    <path d="M0 328C72 148 154 88 244 76C344 63 506 62 760 62" fill="none" stroke="#ffae35" strokeWidth="8" strokeLinecap="round"/>
    <path d="M0 328C132 287 245 246 366 202C500 153 626 105 760 44" fill="none" stroke="#63dbc0" strokeWidth="8" strokeLinecap="round"/>
    <circle cx="244" cy="76" r="9" fill="#ffae35"/><path d="M244 88V151" stroke="#ffae35" strokeWidth="2" strokeDasharray="6 6"/>
    <rect x="156" y="151" width="221" height="62" rx="12" fill="#172b46" stroke="#ffae35" strokeOpacity=".55"/>
    <text x="174" y="178" fill="#ffd58d" fontSize="18" fontWeight="700">~500–1,000 episodes</text><text x="174" y="199" fill="#fff" fillOpacity=".64" fontSize="14">repetition starts to flatten</text>
    <rect x="500" y="73" width="248" height="40" rx="20" fill="#ffae35" fillOpacity=".12"/><circle cx="523" cy="93" r="6" fill="#ffae35"/><text x="540" y="99" fill="#ffd58d" fontSize="16" fontWeight="700">More of one task</text>
    <rect x="500" y="214" width="248" height="40" rx="20" fill="#63dbc0" fillOpacity=".12"/><circle cx="523" cy="234" r="6" fill="#63dbc0"/><text x="540" y="240" fill="#8fe8d2" fontSize="16" fontWeight="700">More distinct tasks</text>
    <text x="0" y="382" fill="#fff" fillOpacity=".72" fontSize="15">Collection budget / episode count →</text>
    <text x="0" y="415" fill="#fff" fillOpacity=".46" fontSize="13">Illustrative curves. The practical threshold varies by task, embodiment and environment.</text>
  </g>
</svg>;

const RecoveryGraphic = () => {
  return <svg viewBox="0 0 980 500" role="img" aria-labelledby="recovery-title recovery-desc" className="h-auto w-full">
    <title id="recovery-title">Success, recovery and dead-end demonstration trajectories</title><desc id="recovery-desc">One trajectory reaches the goal, one slips and recovers, and one ends as a labelled dead end.</desc>
    <rect x="1" y="1" width="978" height="498" rx="30" fill="#f5faf9" stroke="#b9ddd6"/>
    <text x="46" y="50" fill="#13213a" fontSize="16" fontWeight="700">THREE VALID EPISODE OUTCOMES</text>
    {[["01","Clean success","No deviation","#13ae96",115],["02","Slip → recovery","Deviation retained with correction","#ff9d13",250],["03","Labelled dead end","Failure retained; no invented recovery","#718096",385]].map(([n,title,sub,color,y]) => <g key={n}>
      <rect x="42" y={Number(y)-42} width="896" height="104" rx="18" fill="#fff" stroke={color as string} strokeOpacity=".35"/>
      <circle cx="84" cy={Number(y)+10} r="24" fill={color as string}/><text x="84" y={Number(y)+16} textAnchor="middle" fill="#fff" fontSize="15" fontWeight="700">{n}</text>
      <text x="126" y={Number(y)} fill="#13213a" fontSize="18" fontWeight="700">{title}</text><text x="126" y={Number(y)+26} fill="#64748b" fontSize="14">{sub}</text>
      <circle cx="436" cy={Number(y)+10} r="10" fill="#15243d"/><path d={`M452 ${Number(y)+10}H552`} stroke={color as string} strokeWidth="6" strokeLinecap="round"/>
      {n === "02" && <><circle cx="552" cy={Number(y)+10} r="12" fill="#fff" stroke={color as string} strokeWidth="5"/><path d={`M568 ${Number(y)+10}C630 ${Number(y)+52} 684 ${Number(y)+52} 742 ${Number(y)+10}`} fill="none" stroke={color as string} strokeWidth="6" strokeLinecap="round"/><text x="622" y={Number(y)+54} fill="#b75d00" fontSize="13" fontWeight="700">recover</text></>}
      {n === "01" && <path d={`M552 ${Number(y)+10}H742`} stroke={color as string} strokeWidth="6" strokeLinecap="round"/>}
      {n === "03" && <><path d={`M552 ${Number(y)+10}H676`} stroke={color as string} strokeWidth="6" strokeDasharray="10 9"/><path d={`M676 ${Number(y)-2}l24 24m0-24l-24 24`} stroke={color as string} strokeWidth="6"/></>}
      {n !== "03" && <><circle cx="770" cy={Number(y)+10} r="25" fill="#fff" stroke="#13ae96" strokeWidth="6"/><circle cx="770" cy={Number(y)+10} r="7" fill="#13ae96"/></>}
      <text x="830" y={Number(y)+16} fill={n === "03" ? "#64748b" : "#087f70"} fontSize="14" fontWeight="700">{n === "03" ? "QA: KEEP + LABEL" : "GOAL"}</text>
    </g>)}
  </svg>;
};

const HumanDemonstrationsPage = () => {
  const reduce = useReducedMotion();
  return <AIDataServicesLayout breadcrumbs={[{ label: "Robotics Training Data", href: "/robotics-training-data-services" }, { label: "Human Demonstrations" }]}>
    <SEOHead title="Human Demonstration Data Collection for Robotics | eQOURSE" description="Teleoperation and egocentric human demonstration data for robot learning with multi-rig collection, failure-recovery episodes, per-episode QA, LeRobot and RLDS delivery." canonical={CANONICAL} keywords="human demonstration data for robotics, teleoperation data collection services, robot demonstration data, embodied AI data collection, robot training data collection, LeRobot dataset format" ogImage="https://www.eqourse.com/assets/ai-data/robotics/human-demonstrations/og-human-demonstrations.jpg" />
    <Helmet><meta name="robots" content="index, follow, max-image-preview:large"/><link rel="preload" as="image" href={`${ASSET_ROOT}/human-demonstrations-hero.avif`} type="image/avif" fetchPriority="high"/><script type="application/ld+json">{JSON.stringify(serviceSchema)}</script></Helmet>
    <main className="overflow-hidden bg-[#f6faf9]">
      <ServiceHero tone="light" preHeadline="Human-Operated · Policy-Ready" headline="Human Demonstration Data" headlineAccent="for Robot Learning" subtext="Teleoperated and egocentric demonstrations collected by trained operators across varied tasks, objects and environments—including the failure-and-recovery episodes most datasets discard." ctaText="Start a Demonstration Data Pilot" ctaLink={CONTACT} secondaryCtaText="Plan Episode Coverage" secondaryCtaLink="#how-many" imageSrc={`${ASSET_ROOT}/human-demonstrations-hero.webp`} imageAvifSrc={`${ASSET_ROOT}/human-demonstrations-hero.avif`} imageAlt="Operator recording a teleoperated manipulation demonstration on a leader-follower rig" imageWidth={1600} imageHeight={900} trustStats={[{ value: "Multi-rig", label: "Collection" }, { value: "Failure", label: "+ recovery" }, { value: "Episode", label: "QA" }, { value: "RLDS", label: "LeRobot ready" }]} rotatingBadges={[{ icon: CircleUserRound, title: "Operator certified", subtitle: "Task · rig · protocol", color: "hsl(170 82% 38%)" }, { icon: RotateCcw, title: "Recovery retained", subtitle: "Deviation · correction · outcome", color: "hsl(28 90% 48%)" }, { icon: Video, title: "Views synchronized", subtitle: "Egocentric · wrist · scene", color: "hsl(190 76% 40%)" }]} bottomBadge={{ iconText: "ACT", title: "Episode-level integrity", subtitle: "Action · state · observation" }}/>

      <section className="bg-white py-20 md:py-28"><div className="container mx-auto grid max-w-7xl gap-12 px-4 lg:grid-cols-[1.05fr_.95fr] lg:items-center"><Reveal><Intro eyebrow="The real bottleneck" title="The rigs are available." accent="Sustained human quality is not."/><div className="mt-8 space-y-5 text-lg leading-8 text-slate-600"><p>Vision-language-action architectures are advancing quickly, and some capture rigs cost less than a single workstation. But every useful episode still requires a person to perform a physical task well while actions, states and observations stay aligned.</p><p><strong className="text-[#15183f]">The constraint on Physical AI is trained human hours at sustained quality.</strong> That is a workforce operations problem: staffing, certification, rotation, environment control and episode-level review.</p></div></Reveal><Reveal className="rounded-[2rem] bg-[#12223b] p-8 text-white md:p-10" delay={.1}><Gauge className="h-9 w-9 text-teal-300"/><p className="mt-8 font-heading text-3xl font-bold leading-tight">A capture rig can cost around <span className="text-[#ffb547]">$500.</span> A trained operator working a full year does not.</p><p className="mt-5 leading-7 text-white/65">Where and how collection is staffed determines whether a programme reaches 100,000 episodes or stalls at 3,000.</p></Reveal></div></section>

      <section id="collection-methods" className="scroll-mt-32 py-20 md:py-28"><div className="container mx-auto max-w-7xl px-4"><Reveal><Intro eyebrow="Collection methods" title="Choose fidelity, throughput" accent="and embodiment fit" body="There is no universally correct rig. Published practice figures below are directional—not eQOURSE throughput guarantees. We scope only the methods available for your programme."/><p className="mt-3 text-xs text-slate-500">Last reviewed: August 2026</p><DataTable headers={["Method", "What it is", "Typical published throughput", "Best for", "Trade-off"]} rows={collectionMethods} caption="Comparison of human demonstration collection methods"/></Reveal></div></section>

      <section id="how-many" className="scroll-mt-32 bg-white py-20 md:py-28"><div className="container mx-auto max-w-7xl px-4"><Reveal><Intro eyebrow="Dataset shape" title="Breadth keeps paying after" accent="depth flattens" body="Current practice suggests the marginal value of repeating one task declines around 500–1,000 demonstrations, while new task types keep adding value much longer."/><p className="mt-3 text-xs text-slate-500">Last reviewed: August 2026</p></Reveal><div className="mt-12 grid gap-10 lg:grid-cols-[1.1fr_.9fr] lg:items-center"><Reveal><DiversityGraphic/></Reveal><Reveal className="lg:pl-5" delay={.08}><p className="font-heading text-3xl font-bold leading-tight text-[#15183f]">Don’t buy 5,000 episodes of one task. Buy 800 each across six tasks.</p><p className="mt-5 text-lg leading-8 text-slate-600">Same budget. Varied environments, objects, operators and initial conditions. A policy that has a chance to generalise instead of memorise.</p><div className="mt-8 border-l-4 border-primary bg-primary/[.06] p-5 text-sm leading-6 text-slate-700"><strong>Our position:</strong> we would rather propose a broader programme than a bigger one. The diversity split and its rationale belong in the scope document.</div></Reveal></div><Reveal><DataTable headers={["Axis", "What to vary", "Why it matters"]} rows={diversityAxes} caption="Diversity axes for robot demonstration datasets"/></Reveal></div></section>

      <section className="bg-[#0e1b30] py-20 text-white md:py-28"><div className="container mx-auto max-w-7xl px-4"><Reveal><Intro light eyebrow="Failure is data" title="The episodes almost nobody collects" body="Operators naturally reset after a slip. We deliberately preserve the deviation, the correction and the cases that cannot be recovered."/></Reveal><div className="mt-12 grid gap-10 lg:grid-cols-[1.08fr_.92fr] lg:items-center"><Reveal><RecoveryGraphic/></Reveal><Reveal delay={.08}><div className="space-y-5">{["Grasp failures and re-grasps", "Mid-task perturbations", "Partial completion and resumption", "Near-miss corrections", "Genuine labelled dead ends", "Multiple valid strategies"].map((x, i) => <div key={x} className="flex items-center gap-4 border-b border-white/10 pb-5"><span className="font-mono text-xs text-teal-300">0{i + 1}</span><p className="font-semibold text-white/85">{x}</p></div>)}</div><p className="mt-8 text-sm leading-7 text-white/62"><strong className="text-teal-300">An operations decision, not a hardware feature.</strong> A well-executed failure is treated as a successful episode when it follows the brief and is labelled honestly.</p></Reveal></div></div></section>

      <section className="py-20 md:py-28"><div className="container mx-auto max-w-7xl px-4"><Reveal><Intro eyebrow="Episode integrity" title="What makes a demonstration" accent="usable" body="A visually convincing episode can still be harmful training data. These are the checks that decide whether it ships."/><DataTable headers={["Quality dimension", "What good looks like", "What it costs when wrong"]} rows={qualityDimensions} caption="Human demonstration episode quality dimensions"/><p className="mt-6 text-sm leading-7 text-slate-600">For how timestamp alignment is measured, verified and documented per episode, see <Link to="/robotics-training-data-services/multimodal-sensor-data" className="font-bold text-primary hover:underline">Multimodal Sensor Data</Link>.</p></Reveal></div></section>

      <section className="bg-white py-20 md:py-28"><div className="container mx-auto grid max-w-7xl gap-12 px-4 lg:grid-cols-2 lg:items-center"><Reveal className="overflow-hidden rounded-[2rem]"><picture><source srcSet={`${ASSET_ROOT}/collection-floor.avif`} type="image/avif"/><source srcSet={`${ASSET_ROOT}/collection-floor.webp`} type="image/webp"/><img src={`${ASSET_ROOT}/collection-floor.webp`} alt="Multiple task stations dressed with varied surfaces, objects and lighting for demonstration diversity" width="1200" height="675" loading="lazy" decoding="async" className="aspect-video h-full w-full object-cover"/></picture></Reveal><Reveal delay={.1}><Intro eyebrow="The operational moat" title="Operator quality is" accent="an operations problem"/><div className="mt-7 space-y-4">{["Managed session lengths with enforced rotation", "Calibration tasks and operator certification", "Multiple operators per task by design", "Per-episode QA instead of batch sampling", "Per-operator quality tracked over time", "Ergonomic caps for VR and exoskeleton work"].map((x) => <div key={x} className="flex gap-3 text-slate-700"><Check className="mt-1 h-5 w-5 shrink-0 text-primary"/><span className="leading-7">{x}</span></div>)}</div><div className="mt-8 rounded-2xl bg-[#15183f] p-6 text-white"><p className="font-heading text-2xl font-bold"><span className="text-teal-300">500+ trained specialists</span> is the operating advantage.</p><p className="mt-3 text-sm leading-6 text-white/65">Rigs can be bought quickly. A certified, scheduled and quality-managed operator bench takes time to build.</p></div></Reveal></div></section>

      <section className="py-20 md:py-28"><div className="container mx-auto max-w-7xl px-4"><div className="grid gap-8 lg:grid-cols-[.9fr_1.1fr]"><Reveal><Intro eyebrow="Interoperable delivery" title="Data you cannot load" accent="is data you do not have" body="The target format and conventions are agreed at scoping and validated in your own loader before volume collection begins."/><div className="mt-8 flex flex-wrap gap-2">{["LeRobot", "RLDS", "Open X-Embodiment", "HDF5", "Raw synchronised streams", "Metadata sidecar"].map((x) => <span key={x} className="rounded-full border border-primary/20 bg-white px-4 py-2 text-sm font-semibold text-[#15183f]">{x}</span>)}</div></Reveal><Reveal className="rounded-[2rem] bg-[#12223b] p-8 text-white md:p-10" delay={.1}><Database className="h-8 w-8 text-teal-300"/><div className="mt-7 grid gap-7 sm:grid-cols-2"><div><h3 className="font-heading text-xl font-bold">Action representation</h3><p className="mt-3 text-sm leading-6 text-white/62">Absolute versus delta is written into the manifest, documentation and pilot handover. Published work has documented 0% success when this convention was confused.</p></div><div><h3 className="font-heading text-xl font-bold">Proprioceptive state</h3><p className="mt-3 text-sm leading-6 text-white/62">Fields, order, frame and rate are explicit. Published evaluation work has documented a 55-point swing from the wrong source.</p></div></div><p className="mt-8 border-t border-white/12 pt-6 text-sm font-semibold text-teal-200">Published figures illustrate why conventions must be validated; they are not claims about a specific client model.</p></Reveal></div></div></section>

      <section className="bg-white py-20 md:py-28"><div className="container mx-auto max-w-7xl px-4"><Reveal><Intro eyebrow="Pilot-gated scale" title="How a collection programme" accent="runs" body="Seven controlled steps turn a task idea into rolling, training-ready episodes. Step five is the gate."/></Reveal><div className="mt-12 grid gap-3 md:grid-cols-2 lg:grid-cols-4">{programmeSteps.map(([n, title, time, text], i) => <Reveal key={n} className={`relative min-h-56 rounded-2xl border p-6 ${i === 4 ? "border-amber-400 bg-[#fff7e8] ring-4 ring-amber-100 lg:col-span-2" : "border-slate-200 bg-[#f6faf9]"}`} delay={i * .035}><div className="flex items-center justify-between"><span className={`font-mono text-sm font-bold ${i === 4 ? "text-amber-700" : "text-primary"}`}>{n}</span><span className="text-xs font-semibold text-slate-500">{time}</span></div><h3 className="mt-8 font-heading text-xl font-bold text-[#15183f]">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{text}</p>{i === 4 && <p className="mt-5 text-xs font-bold uppercase tracking-[.12em] text-amber-700">Nothing scales until this clears</p>}</Reveal>)}</div><p className="mt-8 text-center text-sm text-slate-600">Setup through a cleared pilot typically takes <strong className="text-[#15183f]">about four weeks</strong>. Volume is then quoted in episodes per week with rolling delivery.</p></div></section>

      <section className="py-20 md:py-28"><div className="container mx-auto max-w-7xl px-4"><Reveal><Intro eyebrow="Delivery package" title="What you" accent="get"/></Reveal><div className="mt-10 grid gap-px overflow-hidden rounded-[2rem] border border-slate-200 bg-slate-200 sm:grid-cols-2 lg:grid-cols-4">{[[Database,"Episode dataset"],[FileCheck2,"Per-episode metadata"],[RotateCcw,"Failure + recovery subset"],[Gauge,"Diversity coverage report"],[ShieldCheck,"QA records"],[FileCheck2,"Convention documentation"],[Check,"Pilot validation record"],[Database,"Rejected-episode log"]].map(([Icon, title]) => { const IconComponent = Icon as typeof Database; return <article key={title as string} className="bg-white p-6"><IconComponent className="h-6 w-6 text-primary"/><h3 className="mt-8 font-heading font-bold text-[#15183f]">{title as string}</h3></article>; })}</div></div></section>

      <section className="bg-white py-20 md:py-28"><div className="container mx-auto max-w-7xl px-4"><Reveal><Intro eyebrow="Failure prevention" title="Where demonstration collection" accent="goes wrong"/><DataTable headers={["Failure", "What happens", "How we avoid it"]} rows={failureModes} caption="Common robot demonstration collection failures and controls"/></Reveal></div></section>

      <section className="bg-[#15183f] py-20 text-white md:py-28"><div className="container mx-auto max-w-7xl px-4"><Reveal><Intro light eyebrow="Clear boundaries" title="What we do—and what we do not"/></Reveal><div className="mt-12 grid gap-8 lg:grid-cols-2"><Reveal className="rounded-[2rem] border border-teal-300/20 bg-teal-300/[.07] p-8"><h3 className="font-heading text-2xl font-bold text-teal-200">We collect, QA and deliver</h3><ul className="mt-7 space-y-4 text-white/72">{["Purpose-built demonstration episodes", "Documented task and diversity design", "Exclusive client data ownership", "Consent-led capture and secure handling", "Pilot-validated formats and conventions"].map((x) => <li key={x} className="flex gap-3"><Check className="mt-1 h-4 w-4 shrink-0 text-teal-300"/>{x}</li>)}</ul></Reveal><Reveal className="rounded-[2rem] border border-white/12 p-8" delay={.08}><h3 className="font-heading text-2xl font-bold">We do not overclaim</h3><ul className="mt-7 space-y-4 text-white/62">{["We do not train your robot policies", "We do not sell episode count without dataset shape", "We do not claim rigs that are unavailable", "We do not scale before the pilot loads", "We do not reuse or resell your data"].map((x) => <li key={x} className="border-b border-white/10 pb-4">{x}</li>)}</ul></Reveal></div></div></section>

      <section className="py-20 md:py-28"><div className="container mx-auto max-w-7xl px-4"><Reveal><Intro eyebrow="Engagement models" title="Start at the scale" accent="that proves the workflow"/></Reveal><div className="mt-10 grid gap-5 md:grid-cols-2">{[["Pilot programme","One or two tasks, limited diversity and full format validation in 4–5 weeks."],["Task collection programme","A designed task set, diversity split and failure protocol delivered on a rolling schedule."],["Egocentric diversity layer","Large-scale human video capture without a robot, alongside or ahead of teleoperation."],["Dedicated capacity","A reserved operator pool and rig configuration with agreed weekly throughput."]].map(([title, text], i) => <Reveal key={title} className="group border-t border-slate-300 py-7" delay={i * .05}><span className="font-mono text-xs text-primary">0{i+1}</span><h3 className="mt-5 font-heading text-2xl font-bold text-[#15183f]">{title}</h3><p className="mt-3 max-w-xl leading-7 text-slate-600">{text}</p></Reveal>)}</div><Link to={CONTACT} className="mt-8 inline-flex items-center gap-2 font-bold text-primary">Scope a collection programme <ArrowRight className="h-4 w-4"/></Link></div></section>

      <section className="bg-white py-20 md:py-28"><div className="container mx-auto max-w-7xl px-4"><Reveal><Intro eyebrow="Why eQOURSE" title="Human operations designed" accent="for data quality"/></Reveal><div className="mt-12 grid gap-px overflow-hidden rounded-[2rem] border border-slate-200 bg-slate-200 md:grid-cols-2 lg:grid-cols-3">{[[UsersRound,"500+ trained specialists","Rotation, certification and per-operator quality tracking."],[Gauge,"Viable collection economics","India-led operations and international engagement for sustained, managed capacity."],[RotateCcw,"Recovery by design","Failure and recovery are planned, not found by accident."],[Database,"Regional collection network","Real environments and diversity no single lab can reproduce."],[FileCheck2,"Per-episode QA","Every episode is reviewed before delivery."],[ShieldCheck,"ISO 9001 & 27001","Exclusive ownership and restricted-environment handling."]].map(([Icon,title,text])=>{const I=Icon as typeof UsersRound;return <article key={title as string} className="bg-[#f8fbfa] p-7"><I className="h-7 w-7 text-primary"/><h3 className="mt-7 font-heading text-xl font-bold text-[#15183f]">{title as string}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{text as string}</p></article>})}</div></div></section>

      <section className="py-20 md:py-28"><div className="container mx-auto max-w-7xl px-4"><Reveal><Intro eyebrow="Robotics service map" title="One programme, five" accent="connected service lines" body="The categories are separated by what they produce, so clients and search engines can understand where each responsibility begins."/></Reveal><div className="mt-10 divide-y divide-slate-200 border-y border-slate-200">{[["Human demonstrations","We create the episodes.",PATH,"current"],["Multimodal sensor data","We capture and align the signals.","/robotics-training-data-services/multimodal-sensor-data","live"],["3D & spatial annotation","We label the world.","/robotics-training-data-services/3d-spatial-annotation","live"],["VLA evaluation","We score the model.","/robotics-training-data-services/vla-evaluation","live"],["Deployment validation","We verify it in place.","/robotics-training-data-services/deployment-validation","live"]].map(([title,text,to,status],i)=><div key={title} className="grid gap-2 py-6 md:grid-cols-[3rem_1fr_1fr_auto] md:items-center"><span className="font-mono text-xs text-primary">0{i+1}</span><h3 className="font-heading text-xl font-bold text-[#15183f]">{title}</h3><p className="text-slate-600">{text}</p>{status === "current" ? <span aria-current="page" className="text-sm font-bold text-primary">Current page</span> : status === "live" ? <Link to={to} className="inline-flex items-center gap-1 text-sm font-bold text-primary">Explore <ArrowRight className="h-4 w-4"/></Link> : <span className="text-xs font-semibold uppercase tracking-wider text-slate-400">Page coming next</span>}</div>)}</div><p className="mt-7 max-w-3xl text-sm leading-7 text-slate-600">The same operator bench can also produce a trained human baseline for <Link to="/robotics-training-data-services/vla-evaluation" className="font-bold text-primary hover:underline">VLA evaluation and robot policy benchmarking</Link> on an identical fixture and protocol.</p><div className="mt-10 flex flex-wrap gap-3"><Link to="/robotics-training-data-services" className="rounded-full border border-primary/25 bg-white px-5 py-3 text-sm font-bold text-primary">Robotics training data services</Link><Link to="/robotics-training-data-services/deployment-validation" className="rounded-full border border-primary/25 bg-white px-5 py-3 text-sm font-bold text-primary">Deployment Validation</Link><Link to="/ai-data-services/data-collection" className="rounded-full border border-slate-200 bg-white px-5 py-3 text-sm font-bold text-[#15183f]">AI data collection</Link><Link to="/ai-data-services/annotation-labeling/3d-point-cloud-lidar-annotation" className="rounded-full border border-slate-200 bg-white px-5 py-3 text-sm font-bold text-[#15183f]">3D Point Cloud & LiDAR Annotation</Link></div></div></section>

      <RelatedBlogs/>
      <section className="bg-white py-20 md:py-28"><div className="container mx-auto grid max-w-7xl gap-12 px-4 lg:grid-cols-[.7fr_1.3fr]"><Reveal><Intro eyebrow="FAQ" title="Human demonstration data" accent="questions" body="Practical answers for robotics teams scoping collection, formats and operator capacity."/></Reveal><Reveal><Accordion type="single" collapsible className="divide-y divide-slate-200 border-y border-slate-200">{faqs.map(({question,answer},i)=><AccordionItem key={question} value={`faq-${i}`} className="border-0"><AccordionTrigger className="py-6 text-left font-heading text-base font-bold text-[#15183f] hover:text-primary hover:no-underline md:text-lg">{question}</AccordionTrigger><AccordionContent className="pb-6 pr-8 leading-7 text-slate-600">{answer}</AccordionContent></AccordionItem>)}</Accordion></Reveal></div></section>

      <ServiceCTA headline="Start with a Pilot That Proves the Episode Format" subtext="Tell us your embodiment, tasks and training framework. We will return with a task design, diversity split, failure protocol and a four-week pilot that proves the format loads." ctaText="Scope a Collection Programme" ctaLink={CONTACT} secondaryCtaText="Talk to Our Robotics Data Team" secondaryCtaLink="/contact-us?service=robotics-training-data#contact-form" note="Pilot before scale · exclusive client data"/>
    </main>
  </AIDataServicesLayout>;
};

export default HumanDemonstrationsPage;
