import { Helmet } from "react-helmet-async";
import RelatedBlogs from "@/components/blog/RelatedBlogs";
import { Link } from "react-router-dom";
import { Boxes, Crosshair, ShieldCheck } from "lucide-react";
import AIDataServicesLayout from "../../shared/AIDataServicesLayout";
import SEOHead from "../../shared/SEOHead";
import ServiceHero from "../../shared/ServiceHero";
import FAQSection from "../../shared/FAQSection";
import ServiceCTA from "../../shared/ServiceCTA";
import { AssistedSecurityCost, CalibrationTruth, FormatsApplications, GeometricQuality, LidarDefinition, LidarProcess, LidarRelated, LidarTypes, SensorLimits } from "./PointCloudLidarCoreSections";

const canonical="https://www.eqourse.com/ai-data-services/annotation-labeling/3d-point-cloud-lidar-annotation";
const faqs=[
  ["What is 3D point cloud annotation?","3D point cloud annotation labels LiDAR or depth-sensor data so a model can understand a scene in three dimensions through oriented cuboids, point classes, surfaces and persistent tracks."],
  ["What is the difference between a 3D cuboid and a 2D bounding box?","A 2D box describes where an object appears in an image. A 3D cuboid adds x, y and z position, length, width, height and yaw so it represents the object's physical location, extent and heading."],
  ["What 3D annotation types does eQOURSE provide?","Services include 3D cuboids, semantic and instance segmentation, multi-sweep tracking, camera-LiDAR and radar fusion, 3D lanes, drivable space, ground classification, keypoints, occupancy labels and aerial point clouds."],
  ["What is sensor fusion annotation?","Sensor fusion annotation labels LiDAR, camera and sometimes radar so every sensor describes the same object consistently. Projected 3D labels are checked against camera views to expose calibration or annotation disagreement."],
  ["Why does calibration matter for 3D annotation?","Incorrect extrinsic calibration makes a correctly placed cuboid look misaligned in the camera view. We validate calibration before production because annotation cannot repair bad calibration—it can only preserve the error."],
  ["How do you measure 3D annotation quality?","We report 3D IoU plus translation, dimension and heading error separately, track consistency for sequences, fusion projection agreement, automated geometry checks, hidden gold sweeps and accuracy by distance band."],
  ["How do you handle far-away and sparse objects?","The guideline sets minimum point thresholds by class and defines whether low-evidence objects are flagged or excluded. When sensor returns cannot support a reliable extent, we do not invent dimensions."],
  ["What input and output formats do you support?","Inputs include PCD, LAS or LAZ, PLY, KITTI-style BIN, ROS bag and E57. Outputs include KITTI labels, nuScenes JSON, Waymo-style structures, SUSTechPOINTS, point-wise labels, cuboid tables and custom schemas."],
  ["Can you track objects across multiple sweeps?","Yes. Persistent object IDs are maintained across sweeps, with ID-switch and track-fragmentation metrics reported alongside geometric accuracy."],
  ["Do you use models to pre-generate 3D annotations?","Where suitable, detectors can pre-generate common near-field cuboids for human correction. Recall is measured by distance band, while rare, far-field and benchmark data returns to manual annotation where automation would bias coverage."],
  ["How much does 3D point cloud annotation cost?","Cost depends on annotation type, objects per sweep, point density, tracking, fusion, classes and attributes, accuracy thresholds, scene difficulty, sampling, security and turnaround. A 20–50 frame pilot provides the best estimate."],
  ["How is sensor data kept secure?","Projects use ISO 27001 processes, NDAs, vetted pools, role-based access, secure transfer, optional restricted environments, audit trails and contract-defined retention and deletion."],
  ["Can you annotate drone or survey point clouds?","Yes. Aerial and photogrammetry point clouds can be labeled for structures, terrain, vegetation, utilities and infrastructure features."],
  ["How do we start?","Share 20–50 representative difficult frames, calibration files and your schema. We validate calibration, annotate a pilot and report geometric error by component and distance band."],
].map(([question,answer])=>({question,answer}));
const offers=["3D Cuboid Annotation","Point-Level Semantic Segmentation","3D Instance Segmentation","Multi-Sweep Object Tracking","Camera-LiDAR Sensor Fusion Annotation","Radar Annotation and Multi-Sensor Fusion","3D Lane and Road Marking Annotation","Drivable Space and Free Space Annotation","Ground and Surface Classification","3D Keypoints and Pose Annotation","Occupancy Grid Labeling","Aerial and Survey Point Cloud Annotation"];
const schema={"@context":"https://schema.org","@graph":[{"@type":"Service","@id":`${canonical}#service`,name:"3D Point Cloud & LiDAR Annotation Services",serviceType:"3D Point Cloud and LiDAR Annotation",url:canonical,description:"3D point cloud and LiDAR annotation for autonomous systems and robotics, including cuboids, point segmentation, tracking, sensor fusion, drivable space and occupancy labels with calibration validation and component-level geometric QA.",provider:{"@type":"Organization",name:"eQOURSE",url:"https://www.eqourse.com/",address:[{"@type":"PostalAddress",addressCountry:"IN"},{"@type":"PostalAddress",addressCountry:"SG"}]},areaServed:"Worldwide",availableLanguage:"en",isPartOf:{"@type":"Service","@id":"https://www.eqourse.com/ai-data-services/annotation-labeling#service",name:"Data Annotation & Labeling Services",url:"https://www.eqourse.com/ai-data-services/annotation-labeling"},hasOfferCatalog:{"@type":"OfferCatalog",name:"3D Point Cloud and LiDAR Annotation Services",itemListElement:offers.map(name=>({"@type":"Offer",itemOffered:{"@type":"Service",name}}))}},{"@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"Home",item:"https://www.eqourse.com/"},{"@type":"ListItem",position:2,name:"AI Data Services",item:"https://www.eqourse.com/ai-data-services"},{"@type":"ListItem",position:3,name:"Data Annotation & Labeling",item:"https://www.eqourse.com/ai-data-services/annotation-labeling"},{"@type":"ListItem",position:4,name:"3D Point Cloud & LiDAR Annotation",item:canonical}]},{"@type":"FAQPage",mainEntity:faqs.map(({question,answer})=>({"@type":"Question",name:question,acceptedAnswer:{"@type":"Answer",text:answer}}))}]};

const PointCloudLidarAnnotationPage=()=> <AIDataServicesLayout breadcrumbs={[{label:"AI Data Services",href:"/ai-data-services"},{label:"Data Annotation & Labeling",href:"/ai-data-services/annotation-labeling"},{label:"3D Point Cloud & LiDAR"}]}>
  <SEOHead title="3D Point Cloud & LiDAR Annotation Services | eQOURSE" description="3D cuboids, point segmentation, multi-sweep tracking and camera-LiDAR fusion for autonomous systems and robotics. KITTI, nuScenes and custom formats." canonical={canonical} keywords="3d point cloud annotation, lidar annotation services, 3d annotation services, point cloud labeling services, 3d cuboid annotation, sensor fusion annotation, lidar data labeling, autonomous driving annotation services, 3d semantic segmentation annotation, point cloud segmentation services" ogImage="https://www.eqourse.com/assets/ai-data/annotation-labeling/3d-point-cloud-lidar-annotation/3d-point-cloud-lidar-annotation-og.webp"/>
  <Helmet><link rel="preload" as="image" href="/assets/ai-data/annotation-labeling/3d-point-cloud-lidar-annotation/3d-point-cloud-lidar-annotation-services-hero.avif" type="image/avif" fetchPriority="high"/><script type="application/ld+json">{JSON.stringify(schema)}</script></Helmet>
  <ServiceHero tone="dark" preHeadline="Measured Geometry for Spatial AI" headline="3D Point Cloud & LiDAR Annotation Services for" headlineAccent="Autonomous Systems" subtext="Cuboids, point-level segmentation, multi-sweep tracking and camera–LiDAR fusion delivered in KITTI, nuScenes, PCD or your schema—with calibration validated and geometric accuracy measured by component." ctaText="Start Free Pilot" ctaLink="/free-pilot" secondaryCtaText="Talk to a Data Specialist" secondaryCtaLink="/contact-us" imageSrc="/assets/ai-data/annotation-labeling/3d-point-cloud-lidar-annotation/3d-point-cloud-lidar-annotation-services-hero.webp" imageAvifSrc="/assets/ai-data/annotation-labeling/3d-point-cloud-lidar-annotation/3d-point-cloud-lidar-annotation-services-hero.avif" imageAlt="Specialist placing 3D cuboids around vehicles in a LiDAR point cloud annotation interface" imageWidth={1200} imageHeight={800} trustStats={[{value:"Fusion-verified",label:"3D + camera agreement"},{value:"Multi-sweep",label:"Persistent object IDs"},{value:"ISO 9001 + 27001",label:"Quality + security"}]} rotatingBadges={[{icon:Crosshair,title:"Calibration-aware",subtitle:"Extrinsics · Time · Projection",color:"hsl(165 72% 58%)"},{icon:Boxes,title:"Geometry-aware",subtitle:"Position · Extent · Heading",color:"hsl(35 92% 58%)"},{icon:ShieldCheck,title:"Sequence-aware",subtitle:"Tracks · Range · Drift",color:"hsl(205 78% 66%)"}]} bottomBadge={{iconText:"3D",title:"Geometry made measurable",subtitle:"IoU → translation → dimensions → heading"}}/>
  <section className="bg-white py-10"><div className="container mx-auto max-w-6xl px-4"><p className="rounded-2xl border border-primary/20 bg-primary/[.05] p-6 leading-7 text-slate-700">This page covers <strong>perception annotation</strong>—what is where in a scene, as cuboids, segmentation and tracks, for driving, mapping and inspection. If a gripper is involved and you need to know <em>how to interact</em> with an object—grasp poses, affordances, articulation and 6-DoF pose—see <Link to="/robotics-training-data-services/3d-spatial-annotation" className="font-bold text-primary hover:underline">3D &amp; spatial annotation for robot manipulation</Link>.</p></div></section>
  <LidarDefinition/><LidarTypes/><CalibrationTruth/><LidarProcess/><GeometricQuality/><SensorLimits/><FormatsApplications/><AssistedSecurityCost/><LidarRelated/>
  <RelatedBlogs />
  <FAQSection faqs={faqs} label="3D Annotation FAQs" title="Frequently Asked Questions About 3D & LiDAR Annotation"/>
  <ServiceCTA headline="Annotate Your Sensor Data for Production Perception" subtext="Send your hardest frames with calibration files—we'll validate alignment, run a pilot and report geometric accuracy by component before you commit to volume." ctaText="Start Free Pilot" ctaLink="/free-pilot" secondaryCtaText="Talk to a Data Specialist" secondaryCtaLink="/contact-us" note="Pilot includes calibration review, component-level error and distance-band reporting"/>
</AIDataServicesLayout>;
export default PointCloudLidarAnnotationPage;
