import { type ReactNode } from "react";
import { Helmet } from "react-helmet-async";
import { Link } from "react-router-dom";
import { motion, useReducedMotion } from "framer-motion";
import { ArrowRight, BadgeCheck, Boxes, Check, Crosshair, Hand, ScanLine } from "lucide-react";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import AIDataServicesLayout from "../../shared/AIDataServicesLayout";
import SEOHead from "../../shared/SEOHead";
import ServiceCTA from "../../shared/ServiceCTA";
import ServiceHero from "../../shared/ServiceHero";
import RelatedBlogs from "@/components/blog/RelatedBlogs";
import { annotationTypes, failures, faqs, poseMethods, programmeSteps } from "./ThreeDSpatialAnnotationContent";

const PATH = "/robotics-training-data-services/3d-spatial-annotation";
const CANONICAL = `https://www.eqourse.com${PATH}`;
const ASSETS = "/assets/ai-data/robotics/3d-spatial-annotation";
const CONTACT = `/contact-us?service=3d-spatial-annotation&source=${PATH.slice(1)}#contact-form`;
const VERIFY = `/contact-us?service=automated-3d-annotation-verification&source=${PATH.slice(1)}#contact-form`;
const description = "Grasp poses, affordances, 6-DoF pose, part and articulation annotation for robot manipulation, plus automated-candidate verification and simulation-ready assets.";

const schema = { "@context": "https://schema.org", "@graph": [
  { "@type": "Service", "@id": `${CANONICAL}#service`, name: "3D & Spatial Annotation for Robot Manipulation", serviceType: "Grasp, affordance, pose and articulation annotation for robot manipulation", description, url: CANONICAL, provider: { "@type": "Organization", name: "eQOURSE", url: "https://www.eqourse.com/" }, areaServed: ["IN", "SG", "US", "GB", "AE", "AU", "EU", "JP", "KR"], isPartOf: { "@id": "https://www.eqourse.com/robotics-training-data-services#service" }, hasOfferCatalog: { "@type": "OfferCatalog", name: "3D and spatial annotation services", itemListElement: ["Grasp pose annotation", "Affordance region annotation", "6-DoF object pose annotation", "3D part segmentation and semantic keypoints", "Articulated object and URDF annotation", "Automated annotation pipeline verification", "Hardware grounding and sim-to-real validation"].map(name => ({ "@type": "Offer", itemOffered: { "@type": "Service", name } })) } },
  { "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: "https://www.eqourse.com/" }, { "@type": "ListItem", position: 2, name: "Robotics Training Data", item: "https://www.eqourse.com/robotics-training-data-services" }, { "@type": "ListItem", position: 3, name: "3D & Spatial Annotation", item: CANONICAL }] },
  { "@type": "FAQPage", mainEntity: faqs.map(({ question, answer }) => ({ "@type": "Question", name: question, acceptedAnswer: { "@type": "Answer", text: answer } })) },
] };

const Reveal = ({ children, className = "" }: { children: ReactNode; className?: string }) => { const reduce = useReducedMotion(); return <motion.div className={className} initial={reduce ? false : { opacity: 0, y: 24 }} whileInView={reduce ? undefined : { opacity: 1, y: 0 }} viewport={{ once: true, amount: .08 }} transition={{ duration: .55 }}>{children}</motion.div>; };
const Intro = ({ eyebrow, title, accent, body, light = false }: { eyebrow: string; title: string; accent?: string; body?: string; light?: boolean }) => <div className="max-w-4xl"><p className={`text-xs font-bold uppercase tracking-[.18em] ${light ? "text-teal-300" : "text-primary"}`}>{eyebrow}</p><h2 className={`mt-4 font-heading text-3xl font-bold leading-tight md:text-5xl ${light ? "text-white" : "text-[#15183f]"}`}>{title} {accent && <span className="text-primary">{accent}</span>}</h2>{body && <p className={`mt-5 text-base leading-7 md:text-lg ${light ? "text-white/70" : "text-slate-600"}`}>{body}</p>}</div>;
const Table = ({ headers, rows, caption, min = "860px" }: { headers: string[]; rows: readonly (readonly string[])[]; caption: string; min?: string }) => <div className="mt-10 max-w-full overflow-x-auto rounded-[1.5rem] border border-slate-200 bg-white"><table style={{ minWidth: min }} className="w-full border-collapse text-left text-sm"><caption className="sr-only">{caption}</caption><thead className="bg-[#13213a] text-white"><tr>{headers.map(h => <th key={h} scope="col" className="px-5 py-4 font-semibold">{h}</th>)}</tr></thead><tbody>{rows.map((row, i) => <tr key={row[0]} className={i % 2 ? "bg-slate-50/70" : "bg-white"}>{row.map((cell, j) => j === 0 ? <th key={cell} scope="row" className="border-t border-slate-200 px-5 py-4 font-bold text-[#15183f]">{cell}</th> : <td key={cell} className="border-t border-slate-200 px-5 py-4 leading-6 text-slate-600">{cell}</td>)}</tr>)}</tbody></table></div>;
const Callout = ({ children, dark = false }: { children: ReactNode; dark?: boolean }) => <div className={`mt-8 border-l-4 border-primary p-6 leading-7 ${dark ? "bg-white/[.06] text-white/75" : "bg-primary/[.06] text-slate-700"}`}>{children}</div>;

const GraspSetDiagram = () => <svg viewBox="0 0 1080 620" role="img" aria-labelledby="grasp-title grasp-desc" className="h-auto w-full"><title id="grasp-title">Four task-conditioned grasp answers for one mug</title><desc id="grasp-desc">Handle, rim, body and top-down approaches are shown; the top-down grasp is excluded because it collides with a lid.</desc><rect x="1" y="1" width="1078" height="618" rx="34" fill="#102038"/><path d="M410 145h210v255c0 58-47 105-105 105s-105-47-105-105z" fill="#19314c" stroke="#71e0c6" strokeWidth="5"/><path d="M620 205c150-20 170 190 10 174" fill="none" stroke="#71e0c6" strokeWidth="34"/><path d="M620 220c105-8 105 128 8 123" fill="none" stroke="#102038" strokeWidth="21"/><path d="M292 284h110" stroke="#4dd6b6" strokeWidth="6" markerEnd="url(#a)"/><path d="M516 70v82" stroke="#ffad2f" strokeWidth="6" markerEnd="url(#b)"/><path d="M744 292h-105" stroke="#4dd6b6" strokeWidth="6" markerEnd="url(#a)"/><path d="M510 520v-92" stroke="#4dd6b6" strokeWidth="6" markerEnd="url(#a)"/><defs><marker id="a" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M0 0l10 5-10 5z" fill="#4dd6b6"/></marker><marker id="b" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M0 0l10 5-10 5z" fill="#ffad2f"/></marker></defs><text x="60" y="260" fill="#9df0dd" fontSize="18" fontWeight="700">body — relocation</text><text x="705" y="270" fill="#9df0dd" fontSize="18" fontWeight="700">handle — permits pouring</text><text x="510" y="545" textAnchor="middle" fill="#9df0dd" fontSize="18" fontWeight="700">rim — task dependent</text><text x="515" y="48" textAnchor="middle" fill="#ffd58d" fontSize="18" fontWeight="700">top-down — excluded with lid</text><path d="M476 82l80 80M556 82l-80 80" stroke="#ffad2f" strokeWidth="5"/><path d="M120 575H960" stroke="#fff" strokeOpacity=".12"/><text x="540" y="602" textAnchor="middle" fill="#fff" fillOpacity=".58" fontSize="15">one object, four answers — the task decides</text></svg>;

const FunnelDiagram = () => <svg viewBox="0 0 1080 520" role="img" aria-labelledby="funnel-title funnel-desc" className="h-auto w-full"><title id="funnel-title">Automated annotation verification funnel</title><desc id="funnel-desc">Generated candidates narrow to 26.6 percent physics validated and 23.2 percent retained, followed by separately measured hardware verification.</desc><rect x="1" y="1" width="1078" height="518" rx="34" fill="#f5faf9" stroke="#b8ddd5"/><text x="540" y="52" textAnchor="middle" fill="#13213a" fontSize="21" fontWeight="700">Candidate generation is cheap. Trust is the narrowing layer.</text>{[[120,900,"GENERATED CANDIDATES","100%","#17324d"],[215,650,"PHYSICS VALIDATED","26.6%","#0fa58e"],[310,520,"RETAINED AFTER FILTERING","23.2%","#f39a14"]].map(([y,w,label,pct,c])=><g key={String(label)}><rect x={(1080-Number(w))/2} y={Number(y)} width={Number(w)} height="70" rx="18" fill={String(c)}/><text x="540" y={Number(y)+30} textAnchor="middle" fill="#fff" fontSize="17" fontWeight="700">{label}</text><text x="540" y={Number(y)+54} textAnchor="middle" fill="#fff" fillOpacity=".75" fontSize="14">{pct}</text></g>)}<path d="M540 380v42" stroke="#13213a" strokeWidth="3" strokeDasharray="7 7"/><rect x="250" y="422" width="580" height="62" rx="17" fill="#fff" stroke="#f39a14" strokeWidth="3"/><text x="540" y="448" textAnchor="middle" fill="#13213a" fontSize="16" fontWeight="700">HARDWARE VERIFIED — measured per object class</text><text x="540" y="470" textAnchor="middle" fill="#64748b" fontSize="13">not inferred from simulation</text><text x="54" y="500" fill="#64748b" fontSize="12">Published automatic-annotation research reported 26.6% physics pass and 23.2% final retention on its audited suite.</text></svg>;

const Programme = () => <div role="img" aria-label="Seven-step 3D spatial annotation programme with pilot as the scale gate" className="grid gap-3 md:grid-cols-2 lg:grid-cols-4">{programmeSteps.map(([n,title,time,text],i)=><article key={n} className={`min-h-52 rounded-2xl border p-6 ${i === 3 ? "border-amber-400 bg-amber-50 ring-4 ring-amber-100" : "border-slate-200 bg-white"}`}><div className="flex justify-between"><span className="font-mono text-sm font-bold text-primary">{n}</span><span className="text-xs font-semibold text-slate-500">{time}</span></div><h3 className="mt-7 font-heading text-xl font-bold text-[#15183f]">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{text}</p>{i === 3 && <p className="mt-4 text-xs font-bold uppercase tracking-wider text-amber-700">Scale gate</p>}</article>)}</div>;

const ThreeDSpatialAnnotationPage = () => <AIDataServicesLayout breadcrumbs={[{ label: "Robotics Training Data", href: "/robotics-training-data-services" }, { label: "3D & Spatial Annotation" }]}>
  <SEOHead title="3D & Spatial Annotation for Robot Manipulation | eQOURSE" description={description} canonical={CANONICAL} keywords="3D spatial annotation for robotics, grasp annotation, 6-DoF pose annotation, affordance annotation, articulated object annotation, robot manipulation data annotation, URDF annotation services" ogImage={`https://www.eqourse.com${ASSETS}/og-3d-spatial-annotation.jpg`}/>
  <Helmet><meta name="robots" content="index, follow, max-image-preview:large"/><link rel="preload" as="image" href={`${ASSETS}/3d-spatial-annotation-hero.avif`} type="image/avif" fetchPriority="high"/><script type="application/ld+json">{JSON.stringify(schema)}</script></Helmet>
  <main className="overflow-hidden bg-[#f5faf9]">
    <ServiceHero tone="light" preHeadline="Manipulation · Not Perception" headline="3D & Spatial Annotation" headlineAccent="for Robot Manipulation" subtext="Grasp poses, affordance regions, 6-DoF object pose, part structure and articulation—the annotations a robot needs to interact with something rather than merely detect it. Produced from scratch or verified over your automated pipeline." ctaText="Scope an Annotation Programme" ctaLink={CONTACT} secondaryCtaText="Verifying Automated Annotation" secondaryCtaLink="#verifying-automation" imageSrc={`${ASSETS}/3d-spatial-annotation-hero.webp`} imageAvifSrc={`${ASSETS}/3d-spatial-annotation-hero.avif`} imageAlt="Annotator reviewing grasp annotations against a physical object during spatial annotation work" imageWidth={1600} imageHeight={900} trustStats={[{value:"Grasp sets",label:"Not single labels"},{value:"6-DoF",label:"Frames explicit"},{value:"Human",label:"Candidate verification"},{value:"ISO",label:"9001 · 27001"}]} rotatingBadges={[{icon:Hand,title:"Task-conditioned",subtitle:"Grasp · affordance · next action",color:"hsl(170 82% 38%)"},{icon:Crosshair,title:"Frame-aware",subtitle:"Pose · symmetry · transforms",color:"hsl(28 90% 48%)"},{icon:ScanLine,title:"Physically reviewed",subtitle:"Sim filter · hardware evidence",color:"hsl(190 76% 40%)"}]} bottomBadge={{iconText:"6D",title:"Interaction made measurable",subtitle:"Coverage · exclusion · robustness"}}/>

    <section className="bg-white py-20 md:py-28"><div className="container mx-auto max-w-7xl px-4"><Reveal><Intro eyebrow="A clean service boundary" title="Perception tells you what is there." accent="Manipulation needs how." body="A bounding box is enough for a vehicle avoiding a mug and nowhere near enough for an arm picking it up. Manipulation must know where fingers close, along what vector, with which wrist orientation and whether the grasp supports the next task."/><Table headers={["","Perception annotation","Manipulation annotation"]} rows={[["Question","What is here, and where?","How do I interact with it?"],["Primitives","3D cuboids, segmentation, tracks","Grasp poses, affordances, 6-DoF pose, parts, articulation"],["Correct answer","Usually one","Usually many; coverage matters"],["Validation","Annotator agreement","Physical feasibility"],["Typical buyer","Driving, mapping, inspection","Manipulation, assembly, logistics picking"]]} caption="Perception and manipulation annotation compared" min="720px"/><Callout>Labelling road scenes? Explore <Link to="/ai-data-services/annotation-labeling/3d-point-cloud-lidar-annotation" className="font-bold text-primary hover:underline">3D point cloud &amp; LiDAR annotation</Link>. If a gripper is involved, this manipulation page is the right service.</Callout></Reveal></div></section>

    <section className="py-20 md:py-28"><div className="container mx-auto max-w-7xl px-4"><Reveal><Intro eyebrow="Annotation scope" title="What we" accent="annotate" body="Each primitive answers a different physical interaction question. The eleven-row table remains native HTML and scrolls only inside its container on small screens."/><Table headers={["Annotation type","What it contains","What it is for"]} rows={annotationTypes} caption="3D manipulation annotation types"/></Reveal></div></section>

    <section className="bg-[#102038] py-20 text-white md:py-28"><div className="container mx-auto max-w-7xl px-4"><Reveal><Intro light eyebrow="The core idea" title="There is no single" accent="correct grasp" body="A mug can be grasped by its handle, rim, body or from above. Validity changes with the gripper, fill state and the task that comes next."/></Reveal><div className="mt-12 overflow-hidden rounded-[2rem] border border-white/10"><GraspSetDiagram/></div><div className="mt-10 grid gap-px overflow-hidden rounded-[1.5rem] bg-white/10 md:grid-cols-5">{[["Coverage","Span valid grasp families"],["Exclusion","Rule out collision and instability"],["Task conditioning","Preserve the next action"],["Gripper specificity","Match the real end effector"],["Robustness","Rank valid alternatives"]].map(([t,d])=><article key={t} className="bg-[#152a45] p-6"><h3 className="font-heading text-lg font-bold text-teal-300">{t}</h3><p className="mt-3 text-sm leading-6 text-white/65">{d}</p></article>)}</div><Callout dark><strong className="text-amber-300">“Accurate grasp labelling” should trigger a question: accurate against what?</strong> The useful measures are coverage, correct exclusion and task conditioning—not agreement with one arbitrary canonical grasp.</Callout></div></section>

    <section id="verifying-automation" className="scroll-mt-32 bg-white py-20 md:py-28"><div className="container mx-auto max-w-7xl px-4"><Reveal><Intro eyebrow="Verification layer" title="Automated systems generate candidates." accent="We make them trustworthy." body="Published automatic-annotation work reported 26.6% physics-validation pass and 23.2% final retention on its own audited suite. These figures illustrate why candidate generation and physical correctness are different jobs; they do not generalise to every pipeline."/><p className="mt-3 text-xs text-slate-500">Last reviewed: August 2026</p></Reveal><div className="mt-12"><FunnelDiagram/></div><div className="mt-10 grid gap-px overflow-hidden rounded-[1.5rem] border border-slate-200 bg-slate-200 md:grid-cols-5">{[["Verification pass","Feasibility, gripper and task review"],["Hard-case arbitration","Deformables, clutter and unusual geometry"],["Coverage audit","Find grasp-family blind spots"],["Real-world grounding","Measure sim-to-real by object class"],["Generator diagnosis","Return the pattern behind failures"]].map(([t,d])=><article key={t} className="bg-[#f8fbfa] p-6"><BadgeCheck className="h-5 w-5 text-primary"/><h3 className="mt-5 font-heading font-bold text-[#15183f]">{t}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{d}</p></article>)}</div><Callout><strong>The most valuable hand-back is often the pattern, not the corrections.</strong> A systematic top-down bias can be fixed once; a corrected batch only fixes one batch.</Callout></div></section>

    <section className="py-20 md:py-28"><div className="container mx-auto grid max-w-7xl gap-12 px-4 lg:grid-cols-2"><Reveal><Intro eyebrow="Simulation-ready assets" title="Anything articulated needs" accent="more than a mesh" body="Doors, drawers, laptops, valves and tools need joint axes, limits, kinematic structure, collision geometry and physical properties that behave plausibly under contact."/><div className="mt-8 space-y-4">{["Joint type, axis, origin and limits","Kinematic tree and part-aligned segmentation","Collision meshes that do not tunnel or catch","Mass, centre of mass, inertia and friction","URDF or MJCF loaded and actuated before delivery"].map(x=><p key={x} className="flex gap-3 text-slate-700"><Check className="mt-1 h-5 w-5 shrink-0 text-primary"/><span>{x}</span></p>)}</div></Reveal><Reveal className="rounded-[2rem] bg-[#14243d] p-8 text-white md:p-10"><Boxes className="h-9 w-9 text-teal-300"/><h3 className="mt-8 font-heading text-3xl font-bold">A simulation-ready asset is one that has been simulated.</h3><p className="mt-5 leading-7 text-white/65">Looking correct in a viewer is not enough. We load and actuate the asset, then report what changed to make it behave plausibly.</p></Reveal></div></section>

    <section className="bg-[#f0f7f5] py-20 md:py-28"><div className="container mx-auto max-w-7xl px-4"><Reveal><Intro eyebrow="Ground truth" title="Physics validation is a filter." accent="Hardware is evidence." body="Simulation asks whether a grasp succeeds under a model of contact, mass and friction. Real execution asks whether it holds on the actual object with the actual gripper."/><div className="mt-10 grid gap-4 md:grid-cols-2"><article className="rounded-[1.5rem] border border-slate-200 bg-white p-8"><h3 className="font-heading text-2xl font-bold text-[#15183f]">Simulation validation</h3><p className="mt-4 leading-7 text-slate-600">Fast, scalable and valuable for filtering. Its answer is bounded by physics assumptions and asset properties.</p></article><article className="rounded-[1.5rem] border border-primary/30 bg-[#102038] p-8 text-white"><h3 className="font-heading text-2xl font-bold">Real-world validation</h3><p className="mt-4 leading-7 text-white/65">Slower and costlier, but it measures the actual object, gripper, approach speed and contact dynamics.</p></article></div><Callout><strong>The sim-to-real pass rate belongs to your simulator and object set.</strong> We report it by object class rather than inventing one universal percentage.</Callout></Reveal></div></section>

    <section className="bg-white py-20 md:py-28"><div className="container mx-auto max-w-7xl px-4"><Reveal><Intro eyebrow="Pose evidence" title="Establishing 6-DoF" accent="ground truth" body="Most programmes combine methods by object class and report achieved accuracy. Symmetry classes are declared explicitly so equivalent rotations are not scored as errors."/><Table headers={["Method","How it works","Accuracy","Trade-off"]} rows={poseMethods} caption="Methods for establishing 6-DoF pose ground truth"/></Reveal></div></section>

    <section className="py-20 md:py-28"><div className="container mx-auto max-w-7xl px-4"><Reveal><Intro eyebrow="Quality" title="Agreement without pretending" accent="there is one answer" body="Coverage overlap, exclusion agreement, task-conditioning consistency and physical verification replace one-label agreement where grasp sets are inherently plural."/></Reveal><div className="mt-10 grid gap-px overflow-hidden rounded-[1.5rem] border border-slate-200 bg-slate-200 md:grid-cols-3">{[["Coverage overlap","Do independent reviewers find overlapping sets?"],["Exclusion agreement","Do reviewers agree on invalid grasps?"],["Physical verification","What proportion holds when executed?"],["Task consistency","Do downstream-task labels agree?"],["Geometric precision","Position and rotation error where one answer exists"],["Adjudication loop","Fix recurring ambiguity in the guideline"]].map(([t,d])=><article key={t} className="bg-white p-7"><h3 className="font-heading text-lg font-bold text-[#15183f]">{t}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{d}</p></article>)}</div></div></section>

    <section className="bg-[#102038] py-20 text-white md:py-28"><div className="container mx-auto max-w-7xl px-4"><Reveal><Intro light eyebrow="Delivery" title="Frames, transforms and" accent="verification stated" body="We support grasp poses, pose frames, mesh/point segmentation, affordance regions, URDF or MJCF, scene graphs and per-annotation metadata."/></Reveal><div className="mt-10 grid gap-px overflow-hidden rounded-[1.5rem] bg-white/10 sm:grid-cols-2 lg:grid-cols-4">{["Frame and transform direction","Symmetry class","Guideline version","Verification method","Simulation validation status","Hardware verification status","Confidence / robustness rank","Annotator and adjudication trail"].map((x,i)=><article key={x} className="bg-[#162a45] p-6"><span className="font-mono text-xs text-teal-300">0{i+1}</span><p className="mt-5 font-semibold">{x}</p></article>)}</div><Callout dark><strong className="text-teal-300">A silently inverted transform is destructive because it looks plausible.</strong> Direction is stated and verified on the pilot every time.</Callout></div></section>

    <section className="bg-white py-20 md:py-28"><div className="container mx-auto max-w-7xl px-4"><Reveal><Intro eyebrow="Programme flow" title="How an engagement" accent="runs" body="A cleared pilot is the gate between guideline design and production scale."/></Reveal><div className="mt-12"><Programme/></div><p className="mt-8 text-sm leading-7 text-slate-600">Scope through cleared pilot typically takes <strong>three weeks</strong>. Verification over an existing automated pipeline can reach first delivery in about <strong>two weeks</strong>.</p></div></section>

    <section className="py-20 md:py-28"><div className="container mx-auto max-w-7xl px-4"><Reveal><Intro eyebrow="Failure prevention" title="Where spatial annotation" accent="goes wrong"/><Table headers={["Failure","What happens","How we avoid it"]} rows={failures} caption="Common failures in 3D spatial annotation"/></Reveal></div></section>

    <section className="bg-white py-20 md:py-28"><div className="container mx-auto max-w-7xl px-4"><Reveal><Intro eyebrow="Robotics service map" title="One programme, five" accent="connected service lines"/></Reveal><div className="mt-10 divide-y divide-slate-200 border-y border-slate-200">{[["Human demonstrations","We create the episodes.","/robotics-training-data-services/human-demonstrations","live"],["Multimodal sensor data","We capture and align the signals.","/robotics-training-data-services/multimodal-sensor-data","live"],["3D & spatial annotation","We label the world.",PATH,"current"],["VLA evaluation","We score the model.","/robotics-training-data-services/vla-evaluation","live"],["Deployment validation","We verify it in place.","/robotics-training-data-services/deployment-validation","live"]].map(([title,text,to,status],i)=><div key={title} className="grid gap-2 py-6 md:grid-cols-[3rem_1fr_1fr_auto] md:items-center"><span className="font-mono text-xs text-primary">0{i+1}</span><h3 className="font-heading text-xl font-bold text-[#15183f]">{title}</h3><p className="text-slate-600">{text}</p>{status === "current" ? <span aria-current="page" className="text-sm font-bold text-primary">Current page</span> : status === "live" ? <Link to={to} className="inline-flex items-center gap-1 text-sm font-bold text-primary">Explore <ArrowRight className="h-4 w-4"/></Link> : <span className="text-xs font-semibold uppercase tracking-wider text-slate-400">Planned</span>}</div>)}</div><div className="mt-8 flex flex-wrap gap-3"><Link to="/robotics-training-data-services" className="rounded-full border border-primary/25 px-5 py-3 text-sm font-bold text-primary">Robotics training data services</Link><Link to="/robotics-training-data-services/vla-evaluation" className="rounded-full border border-primary/25 px-5 py-3 text-sm font-bold text-primary">VLA Evaluation</Link><Link to="/ai-data-services/annotation-labeling/3d-point-cloud-lidar-annotation" className="rounded-full border border-slate-200 px-5 py-3 text-sm font-bold text-[#15183f]">3D Point Cloud &amp; LiDAR Annotation</Link><Link to="/ai-data-services/annotation-labeling/image-annotation" className="rounded-full border border-slate-200 px-5 py-3 text-sm font-bold text-[#15183f]">Image Annotation</Link></div></div></section>

    <RelatedBlogs/>
    <section className="py-20 md:py-28"><div className="container mx-auto grid max-w-7xl gap-12 px-4 lg:grid-cols-[.7fr_1.3fr]"><Reveal><Intro eyebrow="FAQ" title="3D spatial annotation" accent="questions" body="Direct answers about grasp sets, pose ground truth, automated candidates, symmetry and simulation-ready assets."/></Reveal><Reveal><Accordion type="single" collapsible className="divide-y divide-slate-200 border-y border-slate-200">{faqs.map(({question,answer},i)=><AccordionItem key={question} value={`faq-${i}`} className="border-0"><AccordionTrigger className="py-6 text-left font-heading text-base font-bold text-[#15183f] hover:text-primary hover:no-underline md:text-lg">{question}</AccordionTrigger><AccordionContent className="pb-6 pr-8 leading-7 text-slate-600">{answer}</AccordionContent></AccordionItem>)}</Accordion></Reveal></div></section>

    <ServiceCTA headline="Grasp Sets, Not Grasp Labels" subtext="Tell us your end effector, object classes and whether you already generate annotations automatically. We will return with a guideline outline, a task-fit quality definition and a pilot plan." ctaText="Scope an Annotation Programme" ctaLink={CONTACT} secondaryCtaText="Verify an Automated Pipeline" secondaryCtaLink={VERIFY} note="Coverage · exclusion · task conditioning · frames explicit"/>
  </main>
</AIDataServicesLayout>;

export default ThreeDSpatialAnnotationPage;
