import { type ReactNode } from "react";
import { Helmet } from "react-helmet-async";
import { Link } from "react-router-dom";
import { motion, useReducedMotion } from "framer-motion";
import { ArrowRight, Check, Clock3, Database, FileCheck2, Gauge, ShieldCheck, SlidersHorizontal, Waves } from "lucide-react";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import AIDataServicesLayout from "../../shared/AIDataServicesLayout";
import SEOHead from "../../shared/SEOHead";
import ServiceCTA from "../../shared/ServiceCTA";
import ServiceHero from "../../shared/ServiceHero";
import RelatedBlogs from "@/components/blog/RelatedBlogs";
import { clusterRows, failureRows, faqs, modalities, programmeSteps, rateMethods, syncMethods, verificationRows } from "./MultimodalSensorDataContent";

const PATH = "/robotics-training-data-services/multimodal-sensor-data";
const CANONICAL = `https://www.eqourse.com${PATH}`;
const ASSET_ROOT = "/assets/ai-data/robotics/multimodal-sensor-data";
const CONTACT = `/contact-us?service=multimodal-sensor-data&source=${PATH.slice(1)}#contact-form`;
const AUDIT = `/contact-us?service=multimodal-sensor-data-audit&source=${PATH.slice(1)}#contact-form`;
const description = "Time-synchronised multimodal robot data—vision, depth, proprioception, force-torque, tactile, IMU and audio—with measured sync error, documented calibration and per-episode lineage.";

const schema = { "@context": "https://schema.org", "@graph": [
  { "@type": "Service", "@id": `${CANONICAL}#service`, name: "Multimodal Sensor Data for Robotics", serviceType: "Time-synchronised multimodal sensor data capture for robot learning", description, url: CANONICAL, provider: { "@type": "Organization", name: "eQOURSE", url: "https://www.eqourse.com/" }, areaServed: ["IN", "SG", "US", "GB", "AE", "AU", "EU", "JP", "KR"], isPartOf: { "@id": "https://www.eqourse.com/robotics-training-data-services#service" }, hasOfferCatalog: { "@type": "OfferCatalog", name: "Multimodal sensor data services", itemListElement: ["Synchronised multimodal capture", "Force-torque and tactile data collection", "Sensor calibration and extrinsic registration", "Rig instrumentation and triggering setup", "Dataset synchronisation and calibration audit", "Metadata and lineage documentation"].map(name => ({ "@type": "Offer", itemOffered: { "@type": "Service", name } })) } },
  { "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: "https://www.eqourse.com/" }, { "@type": "ListItem", position: 2, name: "Robotics Training Data", item: "https://www.eqourse.com/robotics-training-data-services" }, { "@type": "ListItem", position: 3, name: "Multimodal Sensor Data", item: CANONICAL }] },
  { "@type": "FAQPage", mainEntity: faqs.map(({ question, answer }) => ({ "@type": "Question", name: question, acceptedAnswer: { "@type": "Answer", text: answer } })) },
] };

const Reveal = ({ children, className = "", delay = 0 }: { children: ReactNode; className?: string; delay?: number }) => {
  const reduce = useReducedMotion();
  return <motion.div className={className} initial={reduce ? false : { opacity: 0, y: 24 }} whileInView={reduce ? undefined : { opacity: 1, y: 0 }} viewport={{ once: true, amount: .1 }} transition={{ duration: .58, delay }}>{children}</motion.div>;
};

const Intro = ({ eyebrow, title, accent, body, light = false }: { eyebrow: string; title: string; accent?: string; body?: string; light?: boolean }) => <div className="max-w-4xl">
  <p className={`text-xs font-bold uppercase tracking-[.18em] ${light ? "text-teal-300" : "text-primary"}`}>{eyebrow}</p>
  <h2 className={`mt-4 font-heading text-3xl font-bold leading-tight md:text-5xl ${light ? "text-white" : "text-[#15183f]"}`}>{title} {accent && <span className="text-primary">{accent}</span>}</h2>
  {body && <p className={`mt-5 text-base leading-7 md:text-lg ${light ? "text-white/68" : "text-slate-600"}`}>{body}</p>}
</div>;

const Table = ({ headers, rows, caption }: { headers: string[]; rows: readonly (readonly string[])[]; caption: string }) => <div className="mt-10 overflow-x-auto rounded-[1.5rem] border border-slate-200 bg-white shadow-[0_24px_70px_rgba(17,31,59,.06)]">
  <table className="w-full min-w-[820px] border-collapse text-left text-sm"><caption className="sr-only">{caption}</caption><thead className="bg-[#12223b] text-white"><tr>{headers.map(h => <th key={h} scope="col" className="px-5 py-4 font-semibold">{h}</th>)}</tr></thead><tbody>{rows.map((row, i) => <tr key={row[0]} className={i % 2 ? "bg-slate-50/75" : "bg-white"}>{row.map((cell, j) => j === 0 ? <th key={cell} scope="row" className="min-w-48 border-t border-slate-200 px-5 py-4 font-bold text-[#15183f]">{cell}</th> : <td key={cell} className="border-t border-slate-200 px-5 py-4 leading-6 text-slate-600">{cell}</td>)}</tr>)}</tbody></table>
</div>;

const Callout = ({ children, dark = false }: { children: ReactNode; dark?: boolean }) => <div className={`mt-8 border-l-4 border-primary p-6 leading-7 ${dark ? "bg-white/[.06] text-white/75" : "bg-primary/[.06] text-slate-700"}`}>{children}</div>;

const RateDiagram = () => <svg viewBox="0 0 1000 430" role="img" aria-labelledby="rate-title rate-desc" className="h-auto w-full">
  <title id="rate-title">Video and force sensor rate mismatch</title><desc id="rate-desc">Sparse video frames sit above a dense force trace whose contact transient falls between two frames.</desc>
  <rect x="1" y="1" width="998" height="428" rx="28" fill="#0f2038"/>
  <text x="55" y="58" fill="#fff" fontSize="20" fontWeight="700">Shared time axis</text><path d="M56 360H944" stroke="#fff" strokeOpacity=".28" strokeWidth="2"/>
  <text x="56" y="112" fill="#8fe8d2" fontSize="16" fontWeight="700">VISION — TENS OF FPS</text>
  {[140,280,420,560,700,840].map((x,i)=><g key={x}><rect x={x-24} y="132" width="48" height="42" rx="7" fill="#63dbc0" fillOpacity=".16" stroke="#63dbc0"/><text x={x} y="158" textAnchor="middle" fill="#8fe8d2" fontSize="12">F{i+1}</text><path d={`M${x} 174V360`} stroke="#63dbc0" strokeOpacity=".16" strokeDasharray="5 7"/></g>)}
  <text x="56" y="236" fill="#ffd58d" fontSize="16" fontWeight="700">FORCE — HUNDREDS TO THOUSANDS OF HZ</text>
  <path d="M86 302C210 300 318 306 458 300C505 298 516 296 530 190C541 286 553 307 594 302C715 298 814 304 918 300" fill="none" stroke="#ffae35" strokeWidth="7" strokeLinecap="round"/>
  <circle cx="530" cy="190" r="9" fill="#ffae35"/><path d="M530 180V112" stroke="#ffae35" strokeWidth="2" strokeDasharray="6 6"/><rect x="415" y="72" width="310" height="48" rx="14" fill="#ffae35" fillOpacity=".13"/><text x="570" y="102" textAnchor="middle" fill="#ffd58d" fontSize="16" fontWeight="700">the transient lands between frames</text>
  <text x="56" y="396" fill="#fff" fillOpacity=".48" fontSize="13">Illustrative trace shape · native force rate retained in delivery</text>
</svg>;

const SyncDiagram = () => <svg viewBox="0 0 1000 480" role="img" aria-labelledby="sync-title sync-desc" className="h-auto w-full">
  <title id="sync-title">Comparison of three sensor synchronisation methods</title><desc id="sync-desc">Stream markers become progressively better aligned from software timestamping to network time protocol and hardware triggering.</desc>
  <rect x="1" y="1" width="998" height="478" rx="28" fill="#f5faf9" stroke="#b9ddd6"/>
  {[{y:98,n:"SOFTWARE TIMESTAMP",a:"tens of ms · drifting",xs:[570,642,704],c:"#718096"},{y:235,n:"PTP / NETWORK CLOCK",a:"sub-ms with PTP",xs:[606,617,630],c:"#ff9d13"},{y:372,n:"HARDWARE TRIGGER",a:"best available alignment",xs:[618,620,622],c:"#13ae96"}].map(({y,n,a,xs,c},i)=><g key={n}>
    <text x="55" y={y-12} fill="#13213a" fontSize="17" fontWeight="700">0{i+1} · {n}</text><text x="55" y={y+17} fill="#64748b" fontSize="14">{a}</text>
    <path d={`M430 ${y}H930`} stroke="#cbd5e1" strokeWidth="3"/><path d={`M620 ${y-39}V${y+39}`} stroke="#13213a" strokeOpacity=".22" strokeDasharray="5 5"/>
    {xs.map((x,j)=><g key={x}><circle cx={x} cy={y} r="15" fill={c}/><text x={x} y={y+5} textAnchor="middle" fill="#fff" fontSize="11" fontWeight="700">{["V","F","S"][j]}</text></g>)}
  </g>)}
  <text x="430" y="442" fill="#64748b" fontSize="13">V = vision · F = force · S = state · centre line = reference event</text>
</svg>;

const ProgrammeDiagram = () => <div role="img" aria-label="Seven-step multimodal capture programme with the pilot as the scale gate" className="grid gap-3 md:grid-cols-2 lg:grid-cols-4">{programmeSteps.map(([n,title,time,text],i)=><article key={n} className={`relative min-h-56 rounded-2xl border p-6 ${i===4?"border-amber-400 bg-[#fff7e8] ring-4 ring-amber-100 lg:col-span-2":"border-slate-200 bg-white"}`}><div className="flex items-center justify-between"><span className={`font-mono text-sm font-bold ${i===4?"text-amber-700":"text-primary"}`}>{n}</span><span className="text-xs font-semibold text-slate-500">{time}</span></div><h3 className="mt-8 font-heading text-xl font-bold text-[#15183f]">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{text}</p>{i===4&&<p className="mt-5 text-xs font-bold uppercase tracking-[.12em] text-amber-700">Nothing scales until this clears</p>}</article>)}</div>;

const MultimodalSensorDataPage = () => <AIDataServicesLayout breadcrumbs={[{ label: "Robotics Training Data", href: "/robotics-training-data-services" }, { label: "Multimodal Sensor Data" }]}>
  <SEOHead title="Multimodal Sensor Data for Robotics & Physical AI | eQOURSE" description={description} canonical={CANONICAL} keywords="multimodal sensor data for robotics, robot sensor data collection, force torque data collection, tactile sensor data, sensor synchronisation robotics, robot data lineage" ogImage={`https://www.eqourse.com${ASSET_ROOT}/multimodal-sensor-data-hero.webp`}/>
  <Helmet><meta name="robots" content="index, follow, max-image-preview:large"/><link rel="preload" as="image" href={`${ASSET_ROOT}/multimodal-sensor-data-hero.avif`} type="image/avif" fetchPriority="high"/><script type="application/ld+json">{JSON.stringify(schema)}</script></Helmet>
  <main className="overflow-hidden bg-[#f6faf9]">
    <ServiceHero tone="light" preHeadline="Measured · Calibrated · Traceable" headline="Multimodal Sensor Data" headlineAccent="for Robot Learning" subtext="Vision, depth, proprioception, force-torque, tactile, IMU and audio—captured together, aligned to an error we measure rather than assume, calibrated with residual error stated, and delivered with per-episode lineage." ctaText="Scope a Capture Programme" ctaLink={CONTACT} secondaryCtaText="How We Verify Synchronisation" secondaryCtaLink="#synchronisation" imageSrc={`${ASSET_ROOT}/multimodal-sensor-data-hero.webp`} imageAvifSrc={`${ASSET_ROOT}/multimodal-sensor-data-hero.avif`} imageAlt="Robot arm instrumented with a wrist camera and six-axis force-torque sensor for multimodal capture" imageWidth={1600} imageHeight={900} trustStats={[{value:"Measured",label:"Sync error"},{value:"Residual",label:"Calibration error"},{value:"Checksums",label:"Versions · QA"},{value:"ISO",label:"9001 · 27001"}]} rotatingBadges={[{icon:Clock3,title:"Time agreement",subtitle:"Offset · drift · gaps",color:"hsl(170 82% 38%)"},{icon:SlidersHorizontal,title:"Spatial agreement",subtitle:"Frames · residuals · validity",color:"hsl(28 90% 48%)"},{icon:Waves,title:"Native signals",subtitle:"Force · tactile · state",color:"hsl(190 76% 40%)"}]} bottomBadge={{iconText:"QA",title:"Per-episode evidence",subtitle:"Measured · versioned · withdrawable"}}/>

    <section className="bg-white py-20 md:py-28"><div className="container mx-auto grid max-w-7xl gap-12 px-4 lg:grid-cols-[1.05fr_.95fr]"><Reveal><Intro eyebrow="The distinction" title="Multimodal does not mean several files" accent="from the same session"/><div className="mt-7 space-y-5 text-lg leading-8 text-slate-600"><p>Most “multimodal” datasets are a video folder, a joint-state CSV and a force log recorded during roughly the same session, but never verified to agree about <em>when</em>.</p><p>They load, train and evaluate without error because held-out data carries the same defect. The failure appears only on a real robot, where lag has stopped behaving like a useful signal.</p><p className="font-bold text-[#15183f]">The defect is invisible at every stage except the one that matters.</p></div></Reveal><Reveal className="rounded-[2rem] bg-[#12223b] p-8 text-white md:p-10" delay={.08}><Gauge className="h-9 w-9 text-teal-300"/><p className="mt-8 font-heading text-3xl font-bold leading-tight">We do not sell a folder of streams. We deliver <span className="text-teal-300">evidence that they agree.</span></p><p className="mt-5 leading-7 text-white/65">Measured synchronisation error, calibration residuals and a lineage record that lets you isolate or withdraw a bad episode months later.</p></Reveal></div></section>

    <section className="py-20 md:py-28"><div className="container mx-auto max-w-7xl px-4"><Reveal><Intro eyebrow="Signal scope" title="What we" accent="capture" body="The stack is chosen from the task, not from a generic sensor checklist."/><p className="mt-3 text-xs text-slate-500">Last reviewed: August 2026</p><Table headers={["Modality","What it contains","Typical rate","Why it matters"]} rows={modalities} caption="Robotics sensor modalities and typical rates"/><Callout><strong>Audio is the cheapest modality few teams collect.</strong> A small gripper microphone can capture seating clicks, misaligned scrapes and slip signatures for almost no added rig complexity.</Callout></Reveal></div></section>

    <section className="bg-[#0e1b30] py-20 text-white md:py-28"><div className="container mx-auto max-w-7xl px-4"><Reveal><Intro light eyebrow="Rate mismatch" title="The modelling decision" accent="hidden in the loader" body="Vision arrives at tens of frames per second. Force and state arrive at hundreds or thousands of hertz. How those rates are reconciled changes what the policy learns."/></Reveal><div className="mt-12"><RateDiagram/></div><Table headers={["Approach","What it does","When it is right","What it costs"]} rows={rateMethods} caption="Methods for reconciling robotics sensor rates"/><Callout dark><strong className="text-teal-300">For force and tactile, native rate is our default.</strong> A contact spike often lands between video frames. Interpolate it and it disappears; hold it and it smears. Every per-stream decision is recorded in the manifest.</Callout></div></section>

    <section id="synchronisation" className="scroll-mt-32 bg-white py-20 md:py-28"><div className="container mx-auto max-w-7xl px-4"><Reveal><Intro eyebrow="Technical heart" title="Synchronisation, measured" accent="rather than assumed" body="Synchronised is a claim that is true only to a tolerance, under stated conditions and for a stated period."/><p className="mt-3 text-xs text-slate-500">Last reviewed: August 2026</p></Reveal><div className="mt-12"><SyncDiagram/></div><Table headers={["Method","How it works","Realistic alignment","Appropriate use"]} rows={syncMethods} caption="Comparison of robotics sensor synchronisation methods"/><div className="mt-10 grid gap-px overflow-hidden rounded-[1.5rem] border border-slate-200 bg-slate-200 sm:grid-cols-2 lg:grid-cols-4">{["Timestamp units and time domain","Clock source per device","Camera exposure timing","Measured offsets and drift","Resets and gaps","Interpolation method","Start/end session checks","Measured error per episode"].map((x,i)=><div key={x} className="bg-[#f8fbfa] p-5"><span className="font-mono text-xs text-primary">0{i+1}</span><p className="mt-4 font-semibold text-[#15183f]">{x}</p></div>)}</div><Callout><strong>Measured synchronisation error is the deliverable.</strong> Not the theoretical capability of the hardware—the alignment verified on the episodes you receive.</Callout></div></section>

    <section className="py-20 md:py-28"><div className="container mx-auto grid max-w-7xl gap-12 px-4 lg:grid-cols-2"><Reveal><Intro eyebrow="Spatial agreement" title="Calibration, versioned" accent="with residual error" body="A stream that cannot be placed in space cannot be fused. Calibration also decays, so every result needs a version and validity interval."/><div className="mt-8 space-y-4">{["Camera intrinsics and lens distortion with reprojection residual", "Sensor extrinsics with transform direction stated explicitly", "Versioned robot kinematics for end-effector pose", "Force-torque gravity and centre-of-mass compensation across six orientations", "Validity interval and recalibration triggers after every rig change"].map(x=><div key={x} className="flex gap-3 text-slate-700"><Check className="mt-1 h-5 w-5 shrink-0 text-primary"/><span className="leading-7">{x}</span></div>)}</div></Reveal><Reveal className="rounded-[2rem] bg-[#15183f] p-8 text-white md:p-10" delay={.08}><SlidersHorizontal className="h-9 w-9 text-teal-300"/><h3 className="mt-8 font-heading text-3xl font-bold">Calibration drifts and nothing errors.</h3><p className="mt-5 leading-7 text-white/65">A bumped mount or swapped gripper can silently offset every later episode. Versioned calibration tells you exactly which episodes are affected instead of forcing you to distrust the whole corpus.</p><div className="mt-8 grid grid-cols-2 gap-3 text-sm"><span className="rounded-xl bg-white/[.07] p-4">Residual recorded</span><span className="rounded-xl bg-white/[.07] p-4">Validity bounded</span><span className="rounded-xl bg-white/[.07] p-4">Direction explicit</span><span className="rounded-xl bg-white/[.07] p-4">Episodes traceable</span></div></Reveal></div></section>

    <section className="bg-white py-20 md:py-28"><div className="container mx-auto max-w-7xl px-4"><Reveal><Intro eyebrow="Contact-rich data" title="The modalities everyone" accent="under-collects" body="Vision says the gripper is near the object. Force says it touched. Tactile says whether the grasp will survive the next acceleration."/></Reveal><div className="mt-10 grid gap-px overflow-hidden rounded-[2rem] border border-slate-200 bg-slate-200 md:grid-cols-2 lg:grid-cols-3">{[["Contact detection","Know when interaction begins."],["Insertion & alignment","Read resistance, seating and jams."],["Slip","Detect motion before it becomes visible."],["Grasp quality","Measure pressure distribution."],["Object properties","Infer weight, compliance and deformation."],["Failure signatures","See failures with no visual cue."]].map(([t,d])=><article key={t} className="bg-[#f8fbfa] p-7"><Waves className="h-6 w-6 text-primary"/><h3 className="mt-7 font-heading text-xl font-bold text-[#15183f]">{t}</h3><p className="mt-3 text-slate-600">{d}</p></article>)}</div><Callout><strong>Instrument at rig-build time.</strong> The marginal cost is small; recollecting one hundred thousand episodes because force or tactile was omitted is not.</Callout></div></section>

    <section className="bg-[#12223b] py-20 text-white md:py-28"><div className="container mx-auto max-w-7xl px-4"><Reveal><Intro light eyebrow="Auditability" title="Metadata and" accent="lineage" body="Every episode carries the record needed to find, explain and withdraw a bad batch six months later."/></Reveal><div className="mt-10 grid gap-px overflow-hidden rounded-[2rem] bg-white/10 sm:grid-cols-2 lg:grid-cols-4">{["Stable episode, session and rig IDs","Checksums for every file","Calibration and pipeline versions","Synchronisation record","Known limitations","QA results","Release approval","Correction and withdrawal history"].map((x,i)=><article key={x} className="bg-[#162943] p-6"><span className="font-mono text-xs text-teal-300">0{i+1}</span><p className="mt-6 font-semibold leading-6">{x}</p></article>)}</div><Callout dark><strong className="text-teal-300">A withdrawal history proves the QA process is real.</strong> A dataset whose quality system has caught and documented something is more trustworthy than one claiming a perfect record.</Callout></div></section>

    <section className="py-20 md:py-28"><div className="container mx-auto max-w-7xl px-4"><Reveal><Intro eyebrow="Release gate" title="How we verify" accent="before delivery"/><Table headers={["Check","Evidence produced"]} rows={verificationRows} caption="Verification checks applied before multimodal sensor data delivery"/></Reveal></div></section>

    <section className="bg-white py-20 md:py-28"><div className="container mx-auto grid max-w-7xl gap-12 px-4 lg:grid-cols-[.9fr_1.1fr]"><Reveal><Intro eyebrow="Delivery contract" title="Formats that load" accent="with the manifest intact" body="LeRobot, RLDS, Open X-Embodiment structures, HDF5, ROS bag, MCAP or raw synchronised streams—validated through your loader before scale."/><div className="mt-8 flex flex-wrap gap-2">{["LeRobot","RLDS","Open X-Embodiment","HDF5","ROS bag","MCAP","Raw + manifest"].map(x=><span key={x} className="rounded-full border border-primary/25 bg-primary/[.05] px-4 py-2 text-sm font-bold text-[#15183f]">{x}</span>)}</div></Reveal><Reveal className="rounded-[2rem] border border-slate-200 p-8" delay={.08}><Database className="h-8 w-8 text-primary"/><h3 className="mt-7 font-heading text-2xl font-bold text-[#15183f]">Every delivery includes</h3><ul className="mt-6 space-y-4 text-slate-600">{["Per-stream rates, units, frames and clock source","Alignment and interpolation method","Calibration version and residual","Measured sync error per episode","QA, exclusion and lineage record","Pilot validation in your stack"].map(x=><li key={x} className="flex gap-3"><Check className="mt-1 h-4 w-4 shrink-0 text-primary"/>{x}</li>)}</ul></Reveal></div></section>

    <section className="py-20 md:py-28"><div className="container mx-auto max-w-7xl px-4"><Reveal><Intro eyebrow="Pilot-gated scale" title="How a programme" accent="runs" body="Specification through a cleared pilot typically takes four weeks; volume follows only after the data loads in your stack."/></Reveal><div className="mt-12"><ProgrammeDiagram/></div></div></section>

    <section className="bg-white py-20 md:py-28"><div className="container mx-auto max-w-7xl px-4"><Reveal><Intro eyebrow="Delivery package" title="What you" accent="get"/></Reveal><div className="mt-10 grid gap-px overflow-hidden rounded-[2rem] border border-slate-200 bg-slate-200 sm:grid-cols-2 lg:grid-cols-4">{[[Database,"Synchronised episodes"],[FileCheck2,"Per-stream manifest"],[Clock3,"Measured sync error"],[SlidersHorizontal,"Calibration package"],[ShieldCheck,"Lineage record"],[Gauge,"Verification reports"],[Check,"Pilot validation"],[FileCheck2,"Flagged-episode log"]].map(([Icon,title])=>{const I=Icon as typeof Database;return <article key={title as string} className="bg-[#f8fbfa] p-6"><I className="h-6 w-6 text-primary"/><h3 className="mt-7 font-heading font-bold text-[#15183f]">{title as string}</h3></article>})}</div></div></section>

    <section className="py-20 md:py-28"><div className="container mx-auto max-w-7xl px-4"><Reveal><Intro eyebrow="Failure prevention" title="Where multimodal capture" accent="goes wrong"/><Table headers={["Failure","What happens","How we avoid it"]} rows={failureRows} caption="Common multimodal robotics data failures and controls"/></Reveal></div></section>

    <section className="bg-[#15183f] py-20 text-white md:py-28"><div className="container mx-auto max-w-7xl px-4"><Reveal><Intro light eyebrow="Clear boundaries" title="What we do not do"/></Reveal><div className="mt-10 grid gap-4 md:grid-cols-2">{["Claim synchronisation we have not measured","Silently fill gaps with smooth fake data","Resample away force and tactile transients by default","Train or tune your robot policy","Scale before a pilot loads in your stack","Reuse or resell client data"].map(x=><div key={x} className="rounded-2xl border border-white/12 p-6 text-white/72"><span className="mr-3 font-mono text-teal-300">—</span>{x}</div>)}</div></div></section>

    <section className="py-20 md:py-28"><div className="container mx-auto max-w-7xl px-4"><Reveal><Intro eyebrow="Engagement models" title="Start where the" accent="uncertainty is"/></Reveal><div className="mt-10 grid gap-5 md:grid-cols-2">{[["Instrumentation & calibration setup","A documented, repeatable configuration for your operation · 3–4 weeks."],["Capture programme","Full multimodal capture beside demonstration collection with rolling QA."],["Dataset audit & remediation","Quantify recoverable defects and required recollection · 2–3 weeks."],["Retrofit instrumentation","Add force, tactile or audio with recalibration and a revised manifest."]].map(([t,d],i)=><article key={t} className="border-t border-slate-300 py-7"><span className="font-mono text-xs text-primary">0{i+1}</span><h3 className="mt-5 font-heading text-2xl font-bold text-[#15183f]">{t}</h3><p className="mt-3 leading-7 text-slate-600">{d}</p></article>)}</div></div></section>

    <section className="bg-white py-20 md:py-28"><div className="container mx-auto max-w-7xl px-4"><Reveal><Intro eyebrow="Robotics service map" title="One programme, five" accent="connected service lines"/><Table headers={["Page","Deliverable","Status"]} rows={clusterRows.map(([page,deliverable,,status])=>[page,deliverable,status === "current" ? "Current page" : status === "live" ? "Live service page" : "Planned page"])} caption="Robotics training data service boundaries"/></Reveal><div className="mt-8 flex flex-wrap gap-3"><Link to="/robotics-training-data-services/human-demonstrations" className="inline-flex items-center gap-2 rounded-full border border-primary/25 px-5 py-3 text-sm font-bold text-primary">Human Demonstrations <ArrowRight className="h-4 w-4"/></Link><Link to="/robotics-training-data-services/3d-spatial-annotation" className="inline-flex items-center gap-2 rounded-full border border-primary/25 px-5 py-3 text-sm font-bold text-primary">3D &amp; Spatial Annotation <ArrowRight className="h-4 w-4"/></Link><Link to="/ai-data-services/annotation-labeling/3d-point-cloud-lidar-annotation" className="rounded-full border border-slate-200 px-5 py-3 text-sm font-bold text-[#15183f]">3D Point Cloud & LiDAR Annotation</Link><Link to="/ai-data-services/cleaning-validation/data-validation-verification" className="rounded-full border border-slate-200 px-5 py-3 text-sm font-bold text-[#15183f]">Data Validation & Verification</Link></div><p className="mt-6 text-sm leading-7 text-slate-600">Sensor extrinsics and spatial annotation share a quiet failure mode: an inverted transform can look plausible while making every downstream result wrong. Both services state and verify transform direction explicitly.</p></div></section>

    <RelatedBlogs/>
    <section className="py-20 md:py-28"><div className="container mx-auto grid max-w-7xl gap-12 px-4 lg:grid-cols-[.68fr_1.32fr]"><Reveal><Intro eyebrow="FAQ" title="Multimodal sensor data" accent="questions" body="Direct answers about rates, triggers, calibration, metadata and pilot scope."/></Reveal><Reveal><Accordion type="single" collapsible className="divide-y divide-slate-200 border-y border-slate-200">{faqs.map(({question,answer},i)=><AccordionItem key={question} value={`faq-${i}`} className="border-0"><AccordionTrigger className="py-6 text-left font-heading text-base font-bold text-[#15183f] hover:text-primary hover:no-underline md:text-lg">{question}</AccordionTrigger><AccordionContent className="pb-6 pr-8 leading-7 text-slate-600">{answer}</AccordionContent></AccordionItem>)}</Accordion></Reveal></div></section>

    <ServiceCTA headline="Find Out Whether Your Streams Actually Agree" subtext="Tell us which modalities you need, what your robot is and whether contact-rich tasks are on the roadmap. We will return with a sensor spec, a task-led tolerance and a four-week path to a verified pilot." ctaText="Scope a Capture Programme" ctaLink={CONTACT} secondaryCtaText="Audit an Existing Dataset" secondaryCtaLink={AUDIT} note="Measured error · documented calibration · full lineage"/>
  </main>
</AIDataServicesLayout>;

export default MultimodalSensorDataPage;
