import { useEffect, useRef, useState } from "react";
import RelatedBlogs from "@/components/blog/RelatedBlogs";
import { Link } from "react-router-dom";
import { ArrowRight, AudioLines, CheckCircle2, FileCheck2, Headphones, Languages, Mic2, ShieldCheck, Sparkles, UsersRound, Volume2 } from "lucide-react";
import FAQSection from "../../shared/FAQSection";
import SectionHeader from "../../shared/SectionHeader";
import { acousticRows, asrSpeechFaqs, deliverableRows, engagementModels, engagementSteps, failureRows, metricRows, regionalRows, testSurfaces } from "./ASRSpeechContent";

const Reveal = ({ children, className = "" }: { children: React.ReactNode; className?: string }) => {
  const ref = useRef<HTMLDivElement>(null);
  const [visible, setVisible] = useState(false);
  useEffect(() => {
    if (window.matchMedia("(prefers-reduced-motion: reduce)").matches) { setVisible(true); return; }
    const observer = new IntersectionObserver(([entry]) => entry.isIntersecting && setVisible(true), { rootMargin: "0px 0px -8%", threshold: 0.08 });
    if (ref.current) observer.observe(ref.current);
    return () => observer.disconnect();
  }, []);
  return <div ref={ref} className={`asr-reveal min-w-0 ${visible ? "is-visible" : ""} ${className}`}>{children}</div>;
};

const DataTable = ({ headers, rows, minWidth = 760 }: { headers: readonly string[]; rows: readonly (readonly string[])[]; minWidth?: number }) => (
  <div className="max-w-full overflow-x-auto rounded-[1.6rem] border border-border bg-card shadow-sm" tabIndex={0} role="region" aria-label={`${headers[0]} table`}>
    <table className="w-full border-collapse text-left" style={{ minWidth }}>
      <thead className="bg-[#101a2c] text-white"><tr>{headers.map((header) => <th key={header} scope="col" className="border-r border-white/10 px-5 py-4 font-heading text-sm font-bold last:border-r-0">{header}</th>)}</tr></thead>
      <tbody>{rows.map((row, i) => <tr key={`${row[0]}-${i}`} className="border-t border-border transition-colors hover:bg-primary/[.035]">{row.map((cell, j) => <td key={j} className={`border-r border-border px-5 py-4 align-top text-sm leading-6 last:border-r-0 ${j === 0 ? "font-semibold text-foreground" : "text-muted-foreground"}`}>{cell}</td>)}</tr>)}</tbody>
    </table>
  </div>
);

export const ASRSpeechMotionStyles = () => <style>{`
  .asr-reveal{opacity:0;transform:translateY(22px);transition:opacity .65s ease,transform .65s ease}.asr-reveal.is-visible{opacity:1;transform:none}
  .asr-signal{stroke-dasharray:10 9;animation:asrSignal 9s linear infinite}.asr-dot{transform-box:fill-box;transform-origin:center;animation:asrPulse 2.8s ease-in-out infinite}.asr-scan{animation:asrScan 5s ease-in-out infinite}
  @keyframes asrSignal{to{stroke-dashoffset:-190}}@keyframes asrPulse{50%{transform:scale(1.18);opacity:.72}}@keyframes asrScan{0%,100%{transform:translateX(-20%);opacity:.08}50%{transform:translateX(95%);opacity:.4}}
  @media(prefers-reduced-motion:reduce){.asr-reveal{opacity:1;transform:none}.asr-signal,.asr-dot,.asr-scan{animation:none}}
`}</style>;

export const TestingSurfaces = () => (
  <section className="bg-background py-20 md:py-24"><div className="container mx-auto px-4"><SectionHeader label="Five surfaces, one product decision" title="What We" gradientText="Test" subtitle="Speech systems fail in more ways than a single accuracy number can express. A system can be excellent on one surface and unusable on another."/><Reveal className="mx-auto grid max-w-7xl overflow-hidden rounded-[2rem] border border-border bg-border sm:grid-cols-2 lg:grid-cols-5">{testSurfaces.map(([title, text], i) => { const icons = [AudioLines, Languages, Volume2, UsersRound, Sparkles]; const Icon = icons[i]; return <article key={title} className="bg-card p-6 lg:min-h-[250px]"><div className="flex items-center justify-between"><Icon className="h-6 w-6 text-primary"/><span className="font-mono text-[10px] font-bold text-primary">0{i + 1}</span></div><h3 className="mt-7 font-heading text-lg font-bold leading-snug">{title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{text}</p></article>})}</Reveal></div></section>
);

export const BeyondWer = () => (
  <section id="beyond-wer" className="scroll-mt-32 bg-[#101a2c] py-20 text-white md:py-24"><div className="container mx-auto px-4"><SectionHeader label="Beyond the headline score" title="Why Word Error Rate" gradientText="Isn't Enough" dark subtitle="WER remains useful for comparability. It is not sufficient for deciding whether a speech product works."/><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[.75fr_1.25fr]"><Reveal><div className="divide-y divide-white/10 border-y border-white/10">{[
    ["Every error weighs the same", "A missed filler word counts exactly like a missed drug name, amount or account ID."],
    ["It can punish better capture", "Correct backchannels and quiet affirmations become insertions when human references missed them."],
    ["Ground truth is not neutral", "Once a model reaches transcriber accuracy, WER can measure conformity to flawed labels."],
    ["Valid variants become errors", "Healthcare/health care, numerals/words and punctuation need an agreed normalisation policy."],
  ].map(([t,d], i)=><article key={t} className="grid gap-3 py-5 sm:grid-cols-[42px_1fr]"><span className="font-mono text-xs font-bold text-[#35dfbb]">0{i+1}</span><div><h3 className="font-heading text-lg font-bold">{t}</h3><p className="mt-2 text-sm leading-6 text-white/65">{d}</p></div></article>)}</div><div className="mt-7 rounded-2xl border border-amber-300/25 bg-amber-300/10 p-5"><p className="text-sm leading-7 text-white/80"><strong className="text-amber-200">Entity measurement changes rankings.</strong> Published comparisons reported 0% vs 8.3% missed drug names and 19.6% vs 30.0% missed phone numbers. We define the entity list with you because importance is a product decision.</p></div><p className="mt-4 text-xs text-white/45">Published comparison figures; vendor names intentionally omitted. Last reviewed August 2026.</p></Reveal><Reveal><DataTable headers={["Metric","What it measures","When it matters"]} rows={metricRows} minWidth={860}/></Reveal></div></div></section>
);

const RegionalChart = () => (
  <div className="w-0 min-w-full max-w-full overflow-x-auto" tabIndex={0} role="region" aria-label="Scrollable regional WER chart"><svg viewBox="0 0 900 360" role="img" aria-labelledby="regional-title regional-desc" className="h-auto min-w-[720px] w-full">
    <title id="regional-title">Regional word error rate spread across India</title><desc id="regional-desc">A dot plot from Nainital at about four percent to Mannarakkat at about forty-four percent, with Hindi about five percent, a Hindi-belt cluster below ten percent, Bhojpuri at 20.9 percent and Maithili at 24.8 percent.</desc>
    <rect x="0" y="0" width="900" height="360" rx="28" fill="#ffffff"/><text x="55" y="55" fill="#101a2c" fontSize="22" fontWeight="700">The same system, one country</text>
    <line x1="70" y1="250" x2="830" y2="250" stroke="#cbd5e1" strokeWidth="3"/>{[0,10,20,30,40].map((v)=><g key={v}><line x1={90+v*16.5} y1="242" x2={90+v*16.5} y2="260" stroke="#94a3b8"/><text x={90+v*16.5} y="286" textAnchor="middle" fill="#64748b" fontSize="13">{v}%</text></g>)}
    <line x1="156" y1="92" x2="816" y2="92" stroke="#0f9f8e" strokeWidth="4" strokeLinecap="round" className="asr-signal"/>
    {[["Nainital ~4%",4,120,"#0f9f8e"],["Hindi ~5%",5,190,"#0f9f8e"],["Hindi-belt <10%",9,105,"#0f9f8e"],["Bhojpuri 20.9%",20.9,175,"#ef9412"],["Maithili 24.8%",24.8,105,"#ef9412"],["Mannarakkat ~44%",44,175,"#ef9412"]].map(([label,value,y,color])=><g key={String(label)}><line x1={90+Number(value)*16.5} y1={Number(y)+12} x2={90+Number(value)*16.5} y2="242" stroke="#cbd5e1" strokeDasharray="4 5"/><circle cx={90+Number(value)*16.5} cy={Number(y)} r="9" fill={String(color)} className="asr-dot"/><text x={90+Number(value)*16.5} y={Number(y)-18} textAnchor="middle" fill="#101a2c" fontSize="13" fontWeight="700">{String(label)}</text></g>)}
    <text x="55" y="330" fill="#64748b" fontSize="12">Source: Voice of India benchmark, 2026</text>
  </svg></div>
);

export const RegionalTesting = () => (
  <section className="bg-[#edf8f5] py-20 md:py-24"><div className="container mx-auto px-4"><SectionHeader label="Regional evidence" title="Accent, Dialect and" gradientText="Regional Testing" subtitle="A single national accuracy figure for a country like India is close to meaningless—and the evidence is now public."/><div className="mx-auto max-w-7xl"><Reveal className="grid gap-8 lg:grid-cols-[1.05fr_.95fr] lg:items-center"><div><p className="leading-8 text-muted-foreground">The <strong className="text-foreground">Voice of India benchmark</strong> evaluated speech recognition across <strong className="text-foreground">15 major Indian languages and 139 regional clusters</strong>—306,230 utterances, 536 hours and 36,691 speakers from unscripted telephone conversations.</p><div className="mt-6 overflow-hidden rounded-[2rem] border border-border bg-white p-3 shadow-soft"><RegionalChart/></div><p className="mt-4 text-xs leading-5 text-muted-foreground">External benchmark evidence, not eQOURSE measurement. <a href="https://arxiv.org/abs/2604.19151" target="_blank" rel="noreferrer" className="font-semibold text-primary hover:underline">Review the source paper</a>. Last reviewed August 2026.</p></div><DataTable headers={["Voice of India finding","Published result"]} rows={regionalRows} minWidth={560}/></Reveal><Reveal className="mt-12 grid gap-px overflow-hidden rounded-[2rem] border border-border bg-border md:grid-cols-3">{[
    ["What we stratify", "Regional accent, language variety, code-mixing, age, gender, speaking style, channel and environment."],
    ["Matched difficulty", "Content, condition, style and utterance length are controlled, and unmatched comparisons are identified."],
    ["Our language bench", "30+ global languages and 12+ Indian languages, with regional panels and native-variety reference transcription."],
  ].map(([t,d])=><article key={t} className="bg-card p-7"><h3 className="font-heading text-xl font-bold">{t}</h3><p className="mt-3 text-sm leading-7 text-muted-foreground">{d}</p></article>)}</Reveal><p className="mx-auto mt-8 max-w-4xl text-center font-heading text-xl font-bold">The same system can vary more than tenfold by region. Your users do not live in the average.</p></div></div></section>
);

const AcousticCurve = () => (
  <svg viewBox="0 0 820 330" role="img" aria-labelledby="acoustic-title acoustic-desc" className="h-auto w-full"><title id="acoustic-title">ASR word error rate across audio-quality quartiles</title><desc id="acoustic-desc">Word error rate rises from 15.31 percent in the highest audio quality quartile to 25.20 percent in the lowest, with the steepest segment labelled the cliff.</desc><rect width="820" height="330" rx="28" fill="#fff"/><text x="48" y="48" fill="#101a2c" fontSize="21" fontWeight="700">Audio quality can move WER by ten points</text><line x1="80" y1="255" x2="750" y2="255" stroke="#cbd5e1" strokeWidth="2"/><line x1="80" y1="85" x2="80" y2="255" stroke="#cbd5e1" strokeWidth="2"/><polyline points="105,210 300,190 495,150 700,82" fill="none" stroke="#0f9f8e" strokeWidth="7" strokeLinecap="round" strokeLinejoin="round" className="asr-signal"/>{[[105,210,"15.31%","Q1 high"],[300,190,"17.4%","Q2"],[495,150,"20.1%","Q3"],[700,82,"25.20%","Q4 low"]].map(([x,y,v,q],i)=><g key={String(q)}><circle cx={Number(x)} cy={Number(y)} r="10" fill={i===3?"#ef9412":"#0f9f8e"} className="asr-dot"/><text x={Number(x)} y={Number(y)-20} textAnchor="middle" fill="#101a2c" fontSize="14" fontWeight="700">{String(v)}</text><text x={Number(x)} y="282" textAnchor="middle" fill="#64748b" fontSize="12">{String(q)}</text></g>)}<path d="M565 116 L635 82" stroke="#ef9412" strokeWidth="2"/><text x="550" y="102" fill="#b65e00" fontSize="14" fontWeight="700">the cliff</text><text x="48" y="312" fill="#64748b" fontSize="12">Source: Voice of India benchmark, 2026</text></svg>
);

export const AcousticAndAgents = () => (
  <><section className="bg-background py-20 md:py-24"><div className="container mx-auto px-4"><SectionHeader label="Production audio, not clean files" title="Testing Under" gradientText="Real Conditions" subtitle="Studio audio tells you the ceiling. Your users are not in a studio."/><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[.8fr_1.2fr] lg:items-start"><Reveal><div className="rounded-[2rem] border border-border bg-white p-3 shadow-soft"><AcousticCurve/></div><div className="mt-5 rounded-2xl border-l-4 border-amber-500 bg-amber-50 p-5 text-sm leading-7 text-slate-700"><strong>We test your production audio path.</strong> If audio arrives at 8 kHz through telephony and two codecs, a 48 kHz WAV describes a system you do not operate.</div></Reveal><Reveal><DataTable headers={["Condition","What we test","Why it bites"]} rows={acousticRows} minWidth={790}/></Reveal></div></div></section>
  <section className="bg-[#101a2c] py-20 text-white md:py-24"><div className="container mx-auto px-4"><SectionHeader label="End-to-end voice behaviour" title="Where Transcription Accuracy" gradientText="Stops Being the Point" dark subtitle="For voice agents, a transcript is an intermediate variable. The product succeeds only when the conversation works."/><Reveal className="mx-auto grid max-w-7xl gap-px overflow-hidden rounded-[2rem] border border-white/10 bg-white/10 sm:grid-cols-2 lg:grid-cols-3">{[
    ["Endpointing","Did the system decide the user had finished at the right moment?"],["Barge-in","Can the user interrupt—and does the system stop and listen?"],["Latency under load","Does real-time performance hold at peak concurrency?"],["Error propagation","Which transcription error became a wrong intent or action?"],["Recovery","Could the user correct the system, and did the correction stick?"],["ASR hallucination","Does silence, noise or non-speech become fluent fabricated text?"],
  ].map(([t,d],i)=><article key={t} className="bg-[#101a2c] p-7"><span className="font-mono text-xs font-bold text-[#35dfbb]">0{i+1}</span><h3 className="mt-5 font-heading text-lg font-bold">{t}</h3><p className="mt-3 text-sm leading-6 text-white/65">{d}</p></article>)}</Reveal><Reveal className="mx-auto mt-8 max-w-5xl rounded-2xl border border-amber-300/25 bg-amber-300/10 p-6 text-center"><p className="font-heading text-xl font-bold text-amber-200">ASR hallucination does not look like an error. It looks like a transcript.</p><p className="mt-2 text-sm leading-6 text-white/70">When it feeds an LLM or automated action, fabricated speech becomes fabricated intent—and nothing downstream flags it.</p></Reveal></div></section></>
);

export const GroundTruth = () => (
  <section className="bg-[#edf8f5] py-20 md:py-24"><div className="container mx-auto px-4"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-2 lg:items-center"><Reveal><p className="font-mono text-xs font-bold uppercase tracking-[.18em] text-primary">Reference quality is measurement quality</p><h2 className="mt-4 font-heading text-4xl font-extrabold leading-tight md:text-5xl">The Reference Transcript Is <span className="text-gradient">Part of the Test</span></h2><p className="mt-5 leading-8 text-muted-foreground">Every accuracy metric measures distance from a reference. If the reference is wrong, the result is wrong—and those errors get attributed to your model.</p><div className="mt-7 divide-y divide-border border-y border-border">{[
    ["Verbatim or clean—decided first","A model is not penalised for correctly capturing a stutter against a clean reference."],["Native-variety transcribers","Regional audio is transcribed by someone who speaks that variety."],["Measured agreement","A double-passed sample establishes the ceiling before model findings."],["Documented normalisation","Numerals, punctuation, contractions and code-mixed orthography are agreed before scoring."],["Ceiling acknowledged","Human-reference limits are reported as measurement limits, not model failures."],
  ].map(([t,d])=><div key={t} className="flex gap-3 py-4"><CheckCircle2 className="mt-1 h-5 w-5 shrink-0 text-primary"/><div><h3 className="font-semibold">{t}</h3><p className="mt-1 text-sm leading-6 text-muted-foreground">{d}</p></div></div>)}</div><p className="mt-6 text-sm text-muted-foreground">The full transcript standard is documented in our <Link to="/ai-data-services/annotation-labeling/audio-speech-annotation" className="font-semibold text-primary hover:underline">audio &amp; speech annotation service</Link>.</p></Reveal><Reveal className="relative overflow-hidden rounded-[2rem] border border-white bg-white shadow-soft"><picture><source srcSet="/assets/ai-data/model-testing/asr-speech/reference-transcript-review.avif" type="image/avif"/><img src="/assets/ai-data/model-testing/asr-speech/reference-transcript-review.webp" alt="Transcribers reconciling a double-passed reference transcript before ASR accuracy measurement" width="1200" height="675" loading="lazy" decoding="async" className="aspect-video w-full object-cover"/></picture><div className="asr-scan absolute inset-y-0 left-0 w-24 bg-gradient-to-r from-teal-300/30 to-transparent"/><div className="border-t border-border p-5"><p className="flex items-center gap-2 text-sm font-bold"><FileCheck2 className="h-5 w-5 text-primary"/>Reference agreement reported before model accuracy.</p></div></Reveal></div></div></section>
);

const EngagementDiagram = () => (
  <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3" role="img" aria-label="Six-step ASR model testing engagement from scope to report">{engagementSteps.map(([n,t,w,d],i)=><article key={n} className="relative overflow-hidden rounded-2xl border border-border bg-white p-6 group"><div className="absolute right-0 top-0 h-16 w-16 rounded-bl-full bg-primary/5 group-hover:w-20 group-hover:h-20 transition-all"/><span className="font-mono text-2xl font-bold text-primary">{n}</span><p className="mt-4 text-xs font-bold uppercase tracking-[.14em] text-amber-600">{w}</p><h3 className="mt-2 font-heading text-lg font-bold">{t}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{d}</p>{i < 5 && <ArrowRight className="absolute bottom-5 right-5 h-4 w-4 text-primary/40"/>}</article>)}</div>
);

export const EngagementAndEvidence = () => (
  <><section className="bg-background py-20 md:py-24"><div className="container mx-auto px-4"><SectionHeader label="Reusable evaluation infrastructure" title="How an Engagement" gradientText="Runs" subtitle="The test design does the hard work. Once it exists, every later release becomes faster to evaluate and easier to compare."/><Reveal className="mx-auto max-w-7xl"><EngagementDiagram/><div className="mt-6 rounded-2xl border border-primary/20 bg-primary/5 p-5 text-center text-sm leading-7 text-muted-foreground"><strong className="text-foreground">Typical first programme: 5–6 weeks.</strong> Subsequent versions run in 1–2 weeks against the versioned test set delivered to you.</div></Reveal><Reveal className="mx-auto mt-12 max-w-7xl"><DataTable headers={["Step","Activity","Window","Output"]} rows={engagementSteps} minWidth={860}/></Reveal></div></section>
  <section className="bg-[#edf8f5] py-20 md:py-24"><div className="container mx-auto px-4"><SectionHeader label="Decision-ready assets" title="What You" gradientText="Get" subtitle="Not a dashboard screenshot—a reusable test system, a typed failure backlog and evidence the engineering team can act on."/><Reveal className="mx-auto max-w-7xl"><DataTable headers={["Deliverable","What it contains"]} rows={deliverableRows} minWidth={680}/></Reveal></div></section></>
);

export const FailuresBoundariesRelated = () => (
  <><section className="bg-background py-20 md:py-24"><div className="container mx-auto px-4"><SectionHeader label="Common evaluation traps" title="Where ASR Testing" gradientText="Goes Wrong"/><Reveal className="mx-auto max-w-7xl"><DataTable headers={["Failure","What happens","How we avoid it"]} rows={failureRows} minWidth={940}/></Reveal></div></section>
  <section className="bg-[#101a2c] py-20 text-white md:py-24"><div className="container mx-auto px-4"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[.8fr_1.2fr]"><Reveal><p className="font-mono text-xs font-bold uppercase tracking-[.18em] text-[#35dfbb]">Clear scope, honest evidence</p><h2 className="mt-4 font-heading text-4xl font-extrabold md:text-5xl">What We <span className="text-[#35dfbb]">Do Not Do</span></h2><div className="mt-7 space-y-4 text-sm leading-7 text-white/70">{[
    "We do not build or tune ASR models. We measure them and classify their failures.","We do not report one headline accuracy number in isolation.","We do not accept an existing test set without first auditing what its sampling can support.","We do not process voice data outside agreed ISO 27001-aligned retention, access and destruction controls.",
  ].map((x)=><p key={x} className="flex gap-3"><ShieldCheck className="mt-1 h-5 w-5 shrink-0 text-[#35dfbb]"/><span>{x}</span></p>)}</div><p className="mt-6 text-sm text-white/65">If training data is the fix, our <Link to="/ai-data-services/annotation-labeling/audio-speech-annotation" className="font-semibold text-[#35dfbb] hover:underline">audio &amp; speech annotation</Link> team can supply it.</p></Reveal><Reveal><DataTable headers={["Engagement model","Best fit","Typical window"]} rows={engagementModels} minWidth={660}/></Reveal></div></div></section>
  <section className="bg-[#edf8f5] py-20 md:py-24"><div className="container mx-auto px-4"><SectionHeader label="A language-aware evaluation bench" title="Why" gradientText="eQOURSE"/><Reveal className="mx-auto grid max-w-7xl gap-px overflow-hidden rounded-[2rem] border border-border bg-border md:grid-cols-2 lg:grid-cols-3">{[
    [Languages,"Regional accent panels","Published data shows this is where the tenfold spread appears"],[UsersRound,"30+ global languages","12+ Indian languages with native-variety reference teams"],[Mic2,"Natural speech by default","Code-mixed, spontaneous and conversational speech"],[Headphones,"One connected bench","The same team understands reference production and testing"],[Volume2,"Production conditions","Telephone and noisy-channel testing are core scope"],[ShieldCheck,"Certified processes","ISO 9001 and ISO 27001 controls"],
  ].map(([Icon,t,d])=>{const C=Icon as typeof Languages;return <article key={String(t)} className="bg-card p-7"><C className="h-6 w-6 text-primary"/><h3 className="mt-5 font-heading text-lg font-bold">{String(t)}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{String(d)}</p></article>})}</Reveal><Reveal className="mx-auto mt-12 max-w-7xl"><h2 className="font-heading text-2xl font-bold">Related services</h2><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{[
    ["AI Model Testing","/ai-data-services/model-testing"],["Audio & Speech Annotation","/ai-data-services/annotation-labeling/audio-speech-annotation"],["AI Bias & Fairness Audit","/ai-data-services/model-testing/bias-fairness-audit"],["LLM Evaluation","/ai-data-services/model-testing/llm-evaluation"],["Data Collection","/ai-data-services/data-collection"],["Dataset QA & Label Audit","/ai-data-services/cleaning-validation/dataset-qa-label-audit"],
  ].map(([t,h])=><Link key={t} to={h} className="flex items-center justify-between rounded-2xl border border-border bg-card px-5 py-4 font-semibold transition-colors hover:border-primary/40 hover:text-primary">{t}<ArrowRight className="h-4 w-4"/></Link>)}<Link to="/ai-data-services/model-testing/human-evaluation-ab-testing" className="flex items-center justify-between rounded-2xl border border-border bg-card px-5 py-4 font-semibold transition-colors hover:border-primary/40 hover:text-primary">Human Evaluation &amp; A/B Testing<ArrowRight className="h-4 w-4"/></Link></div></Reveal></div></section>
  <RelatedBlogs />
  <FAQSection title="ASR & Speech Model Testing FAQs" faqs={asrSpeechFaqs.map(([question,answer])=>({question,answer}))}/></>
);
