import type { ReactNode } from "react";
import RelatedBlogs from "@/components/blog/RelatedBlogs";
import { Link } from "react-router-dom";
import { ArrowRight, CheckCircle2, FileCheck2, Globe2, LockKeyhole, Scale, ShieldCheck, UsersRound } from "lucide-react";
import SectionHeader from "../../shared/SectionHeader";
import FAQSection from "../../shared/FAQSection";
import { useScrollReveal } from "@/hooks/use-scroll-reveal";
import { auditSteps, biasFairnessFaqs, failureModes, fairnessMetrics, modelAuditTypes, regulations } from "./BiasFairnessContent";

const Reveal = ({ children, className = "" }: { children: ReactNode; className?: string }) => {
  const { ref, isVisible } = useScrollReveal();
  return <div ref={ref} className={`transition-all duration-700 ${isVisible ? "translate-y-0 opacity-100" : "translate-y-7 opacity-0"} ${className}`}>{children}</div>;
};

const DataTable = ({ headers, rows, minWidth = 860 }: { headers: string[]; rows: readonly (readonly string[])[]; minWidth?: number }) => (
  <div className="overflow-x-auto rounded-[1.6rem] border border-border bg-white shadow-card" tabIndex={0} aria-label="Scrollable data table">
    <table className="w-full text-left text-sm" style={{ minWidth }}>
      <thead className="bg-[#101a2c] text-white"><tr>{headers.map((h) => <th key={h} scope="col" className="p-4 font-heading">{h}</th>)}</tr></thead>
      <tbody>{rows.map((row) => <tr key={row[0]} className="border-t border-border align-top">{row.map((cell, i) => i === 0 ? <th key={cell} scope="row" className="p-4 font-heading font-bold text-foreground">{cell}</th> : <td key={`${row[0]}-${i}`} className="p-4 leading-6 text-muted-foreground">{cell}</td>)}</tr>)}</tbody>
    </table>
  </div>
);

export const BiasFairnessMotionStyles = () => <style>{`
  @keyframes bf-disparity { 0%,100%{transform:scaleX(.66)} 50%{transform:scaleX(1)} }
  @keyframes bf-dash { to { stroke-dashoffset:-40; } }
  @keyframes bf-scan { 0%{transform:translateY(-120%);opacity:0} 15%,75%{opacity:.75} 100%{transform:translateY(680%);opacity:0} }
  .bf-bar{transform-origin:left;animation:bf-disparity 3.8s ease-in-out infinite}.bf-path{animation:bf-dash 7s linear infinite}.bf-scan{animation:bf-scan 5.2s ease-in-out infinite}
  @media(prefers-reduced-motion:reduce){.bf-bar,.bf-path,.bf-scan{animation:none!important}}
`}</style>;

export const AuditDefinition = () => (
  <section className="bg-background py-20 md:py-24"><div className="container mx-auto px-4"><Reveal className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[.9fr_1.1fr] lg:items-center">
    <div><span className="font-mono text-xs font-bold uppercase tracking-[.2em] text-primary">Measurement, not a certificate</span><h2 className="mt-5 font-heading text-3xl font-bold leading-tight md:text-5xl">What a Bias and Fairness Audit <span className="text-gradient">Actually Is</span></h2><p className="mt-6 text-lg leading-8 text-muted-foreground">A bias and fairness audit measures whether an AI system produces materially different outcomes, or materially different quality of service, for different groups of people—and documents that measurement in a form you can defend.</p><p className="mt-4 leading-7 text-muted-foreground">It is a measurement exercise, not an opinion. The output is a set of distributions, disparity metrics and worked examples, with the method and sample sizes stated so a third party can assess whether the finding holds.</p></div>
    <div className="overflow-hidden rounded-[2rem] border border-border bg-[#101a2c] text-white shadow-elevated">{[
      ["Red teaming", "Asks whether a model can be made to fail and reports successful attacks. A fairness audit asks whether it treats groups differently and reports distributions.", "/ai-data-services/model-testing/ai-red-teaming"],
      ["Certification", "No credible party permanently certifies a model as unbiased. Change the population or data and the result changes."],
      ["Bias mitigation", "An audit measures the disparity. Remediation—data, thresholds or product changes—is separate engineering work."],
    ].map(([title, text, href], i) => <div key={title} className="grid gap-3 border-b border-white/10 p-6 sm:grid-cols-[120px_1fr]"><span className="font-mono text-xs text-teal-300">0{i + 1} · {href ? <Link to={href} className="hover:text-white hover:underline">{title}</Link> : title}</span><p className="text-sm leading-6 text-white/65">{text}</p></div>)}<p className="p-6 font-heading text-lg font-bold text-amber-200">A useful audit is one that could have failed.</p></div>
  </Reveal></div></section>
);

export const RegulationSection = () => (
  <section className="bg-muted/35 py-20 md:py-24"><div className="container mx-auto px-4"><SectionHeader label="Regulatory orientation" title="What Regulation Requires" gradientText="— and When" subtitle="Requirements differ by jurisdiction and use case. This is orientation as of August 2026, not legal advice; confirm your obligations with counsel."/><div className="mx-auto max-w-7xl"><DataTable headers={["Jurisdiction / framework", "Status as of Aug 2026", "What it expects"]} rows={regulations} minWidth={980}/><p className="mt-3 text-right text-xs text-muted-foreground">Last reviewed: August 2026</p><div className="mt-8 grid gap-px overflow-hidden rounded-[2rem] border border-border bg-border lg:grid-cols-2"><div className="bg-[#101a2c] p-7 text-white"><h3 className="font-heading text-2xl font-bold text-teal-300">The EU deadline moved. The work didn't.</h3><p className="mt-4 text-sm leading-7 text-white/65">High-risk obligations were deferred to December 2027 and August 2028. A defensible baseline and remediation programme still take time; baselining now lets teams choose their test sets rather than inherit whatever data exists under deadline pressure.</p></div><div className="bg-white p-7"><h3 className="font-heading text-2xl font-bold">“Independent” can be a legal term.</h3><p className="mt-4 text-sm leading-7 text-muted-foreground">NYC Local Law 144 requires independence from the employer and tool vendor. eQOURSE builds no employment decision tools or scoring models. Confirm the statutory test with counsel; we provide documentation of our role and any prior involvement.</p></div></div></div></div></section>
);

export const ThreeBiases = () => (
  <section className="bg-background py-20 md:py-24"><div className="container mx-auto px-4"><SectionHeader label="Three different questions" title="The Three Kinds of Bias" gradientText="We Test For" subtitle="Conflating these failure modes is the most common reason an audit misses something."/><Reveal className="mx-auto max-w-7xl overflow-hidden rounded-[2rem] border border-border bg-white shadow-soft">
    <svg viewBox="0 0 1200 270" role="img" aria-labelledby="bias-types-title bias-types-desc" className="hidden w-full md:block"><title id="bias-types-title">Three kinds of AI bias</title><desc id="bias-types-desc">Outcome disparity, quality-of-service disparity and representational harm require different tests.</desc><path d="M200 94H1000" stroke="currentColor" className="text-border" strokeWidth="2"/><circle cx="200" cy="94" r="29" className="fill-primary"/><circle cx="600" cy="94" r="29" className="fill-[#101a2c]"/><circle cx="1000" cy="94" r="29" className="fill-amber-400"/><text x="200" y="101" textAnchor="middle" fill="white" fontSize="18">01</text><text x="600" y="101" textAnchor="middle" fill="white" fontSize="18">02</text><text x="1000" y="101" textAnchor="middle" fill="#101a2c" fontSize="18">03</text><text x="200" y="157" textAnchor="middle" fill="currentColor" fontSize="22" fontWeight="700">Outcome disparity</text><text x="600" y="157" textAnchor="middle" fill="currentColor" fontSize="22" fontWeight="700">Quality-of-service disparity</text><text x="1000" y="157" textAnchor="middle" fill="currentColor" fontSize="22" fontWeight="700">Representational harm</text><text x="200" y="193" textAnchor="middle" fill="#667085" fontSize="15">Rates · scores · decisions</text><text x="600" y="193" textAnchor="middle" fill="#667085" fontSize="15">Accuracy · WER · error deltas</text><text x="1000" y="193" textAnchor="middle" fill="#667085" fontSize="15">Stereotypes · erasure · tone</text></svg>
    <div className="grid gap-px bg-border md:grid-cols-3">{[
      ["Outcome disparity", "Different decisions or scores across groups at rates not explained by legitimate factors.", "Impact ratio · equal opportunity · equalized odds"],
      ["Quality-of-service disparity", "The system works, but performs worse for an accent, skin tone, script or language.", "Matched difficulty · per-group errors · accuracy deltas"],
      ["Representational harm", "Outputs stereotype, demean, erase or over-associate a group, even without a formal decision.", "Counterfactual probes · name substitution · matched human panels"],
    ].map(([title, text, tested]) => <article key={title} className="bg-white p-7"><h3 className="font-heading text-xl font-bold">{title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{text}</p><p className="mt-6 border-t border-border pt-4 text-xs font-bold text-primary">Tested with: {tested}</p></article>)}</div>
  </Reveal><p className="mx-auto mt-7 max-w-4xl text-center text-sm leading-6 text-muted-foreground">Many scopes begin with outcome disparity. The sharpest findings often appear in quality of service or representation; a report that covers only outcomes should say so explicitly.</p></div></section>
);

export const MetricsSection = () => (
  <section className="bg-[#101a2c] py-20 text-white md:py-24"><div className="container mx-auto px-4"><SectionHeader light label="The substantive choice" title="Fairness Metrics — and How to" gradientText="Choose the Right One" subtitle="There is no single fairness number. Each metric encodes a different idea of fair, and the choice is fixed before testing starts."/><div className="mx-auto max-w-7xl"><div className="[&_td]:!text-white/65 [&_th]:!text-white [&>div]:!border-white/10 [&>div]:!bg-[#101a2c]"><DataTable headers={["Metric", "What it asks", "Use it when", "Blind spot"]} rows={fairnessMetrics} minWidth={1050}/></div><Reveal className="mt-10 grid gap-10 rounded-[2rem] border border-white/10 bg-white/[.04] p-7 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div id="metric-conflict"><span className="font-mono text-xs font-bold uppercase tracking-[.18em] text-amber-300">Metric conflict</span><h3 className="mt-4 font-heading text-3xl font-bold">You cannot satisfy all definitions at once.</h3><p className="mt-4 text-sm leading-7 text-white/65">Where base rates differ, calibration and equalized odds cannot both hold except in degenerate cases. We agree the primary metric in writing, explain why it fits the decision, and report the others alongside it.</p></div><svg viewBox="0 0 620 310" role="img" aria-labelledby="metric-title metric-desc" className="w-full"><title id="metric-title">Fairness metric conflict</title><desc id="metric-desc">Calibration, equalized odds and demographic parity can conflict when base rates differ.</desc><path d="M310 45 95 260H525Z" fill="none" stroke="currentColor" className="bf-path text-teal-300" strokeWidth="3" strokeDasharray="9 8"/><circle cx="310" cy="45" r="43" className="fill-primary"/><circle cx="95" cy="260" r="43" className="fill-amber-400"/><circle cx="525" cy="260" r="43" className="fill-sky-400"/><text x="310" y="50" textAnchor="middle" fill="white" fontSize="12">CALIBRATION</text><text x="95" y="256" textAnchor="middle" fill="#101a2c" fontSize="12" className="font-bold">EQUALIZED</text><text x="95" y="271" textAnchor="middle" fill="#101a2c" className="font-bold" fontSize="12">ODDS</text><text x="525" y="256" textAnchor="middle" fill="#101a2c" className="font-bold" fontSize="11">DEMOGRAPHIC</text><text className="font-bold" x="525" y="271" textAnchor="middle" fill="#101a2c" fontSize="12">PARITY</text><text x="310" y="183" textAnchor="middle" fill="white" fontSize="15">Base rates differ</text><text x="310" y="204" textAnchor="middle" fill="#99f6e4" fontSize="13">trade-offs must be named</text></svg></Reveal></div></div></section>
);

export const ModelTypesAndMethod = () => (
  <>
    <section className="bg-background py-20 md:py-24"><div className="container mx-auto px-4"><SectionHeader label="Modality coverage" title="Model Types" gradientText="We Audit"/><div className="mx-auto grid max-w-7xl gap-px overflow-hidden rounded-[2rem] border border-border bg-border md:grid-cols-2 lg:grid-cols-3">{modelAuditTypes.map(([type, test], i) => { const content=<><span className="font-mono text-xs text-primary">0{i + 1}</span><h3 className="mt-5 font-heading text-xl font-bold">{type}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{test}</p></>; const href=type === "Speech & ASR" ? "/ai-data-services/model-testing/asr-speech-model-testing" : (type === "Computer vision & face" || type === "Document & OCR") ? "/ai-data-services/model-testing/computer-vision-model-testing" : ""; return href ? <Link key={type} to={href} className="bg-card p-7 transition-colors hover:bg-primary/[.045]">{content}</Link> : <article key={type} className="bg-card p-7 transition-colors hover:bg-primary/[.045]">{content}</article>})}</div><p className="mt-7 text-center text-sm text-muted-foreground">Explore <Link to="/ai-data-services/model-testing/llm-evaluation" className="font-semibold text-primary hover:underline">LLM Evaluation Services</Link>, <Link to="/ai-data-services/model-testing/asr-speech-model-testing" className="font-semibold text-primary hover:underline">ASR &amp; Speech Model Testing</Link> or <Link to="/ai-data-services/model-testing/computer-vision-model-testing" className="font-semibold text-primary hover:underline">Computer Vision Model Testing</Link>.</p></div></section>
    <section className="bg-muted/35 py-20 md:py-24"><div className="container mx-auto px-4"><SectionHeader label="Repeatable method" title="How We Run" gradientText="an Audit" subtitle="The metric is fixed first; the test set and evaluator panel are then built around the decision it must support."/><div className="mx-auto max-w-7xl"><svg viewBox="0 0 1100 100" role="img" aria-labelledby="method-title method-desc" className="mb-4 hidden w-full lg:block"><title id="method-title">Six-step bias audit method</title><desc id="method-desc">Scope, data strategy, test set, evaluator panel, analysis and reporting.</desc><path d="M60 50H1040" stroke="currentColor" className="text-border" strokeWidth="3"/><path d="M1040 50H60" stroke="currentColor" className="bf-path text-primary" strokeWidth="3" strokeDasharray="10 20"/>{auditSteps.map((_, i) => <g key={i}><circle cx={60 + i * 196} cy="50" r="17" className={i === 0 ? "fill-primary" : "fill-white stroke-primary"} strokeWidth="3"/><text x={60 + i * 196} y="55" textAnchor="middle" fontSize="12" className={i === 0 ? "fill-white" : "fill-primary"}>{i + 1}</text></g>)}</svg><ol className="grid gap-px overflow-hidden rounded-[2rem] border border-border bg-border md:grid-cols-2 lg:grid-cols-3">{auditSteps.map(([n, title, text], i) => <li key={n} className={`p-7 ${i === 0 ? "bg-[#101a2c] text-white" : "bg-card"}`}><span className={`font-mono text-xs ${i === 0 ? "text-teal-300" : "text-primary"}`}>{n}</span><h3 className="mt-5 font-heading text-lg font-bold">{title}</h3><p className={`mt-3 text-sm leading-6 ${i === 0 ? "text-white/60" : "text-muted-foreground"}`}>{text}</p></li>)}</ol><p className="mt-7 rounded-2xl border border-primary/20 bg-primary/5 p-5 text-center text-sm font-semibold">First-cycle audit: typically 5–7 weeks. Re-audit against an established baseline: typically 2–3 weeks.</p></div></div></section>
  </>
);

export const BeyondWesternTooling = () => (
  <section className="overflow-hidden bg-background py-20 md:py-24"><div className="container mx-auto px-4"><Reveal className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[1fr_1fr] lg:items-center"><div><span className="font-mono text-xs font-bold uppercase tracking-[.2em] text-primary">Human context is the method</span><h2 className="mt-5 font-heading text-3xl font-bold md:text-5xl">Bias Western Tooling <span className="text-gradient">Doesn't Look For</span></h2><p className="mt-5 leading-7 text-muted-foreground">US protected classes matter, and we test them. For India, South Asia and diaspora markets they are not sufficient. Caste, religion, geography, name signals, script, code-mixing and regional accent require people who recognise the signal—not only a dashboard that computes the arithmetic.</p><div className="mt-8 grid gap-5 border-l border-primary/30 pl-6">{[["Name-conditioned bias", "Community signals must vary while region, gender, generation and phonetic length remain controlled."],["Language, script & code-mixing", "Native probes cover real registers, including romanised and code-mixed inputs."],["Dialect & accent", "Matched audio separates regional speech performance from difficulty differences."],["Proxy variables", "Postcode, institution, device or channel may carry group membership even when the protected attribute is absent."]].map(([title, text]) => <div key={title}><h3 className="font-heading text-lg font-bold">{title}</h3><p className="mt-1 text-sm leading-6 text-muted-foreground">{text}</p></div>)}</div></div><div className="relative overflow-hidden rounded-[2rem]"><picture><source srcSet="/assets/ai-data/model-testing/bias-fairness/fairness-evaluator-panel.avif" type="image/avif"/><img src="/assets/ai-data/model-testing/bias-fairness/fairness-evaluator-panel.webp" alt="Trained evaluator rating model outputs against a structured fairness rubric" width="1200" height="675" loading="lazy" decoding="async" className="w-full"/></picture><span aria-hidden="true" className="bf-scan absolute inset-x-0 top-0 h-px bg-gradient-to-r from-transparent via-primary to-transparent"/><div className="absolute inset-x-5 bottom-5 rounded-2xl border border-white/70 bg-white/85 p-5 backdrop-blur-xl"><p className="font-heading font-bold">The panel is part of the evidence.</p><p className="mt-1 text-xs text-muted-foreground">Language · demographic strata · domain · agreement</p></div></div></Reveal></div></section>
);

export const StatisticalHonesty = () => (
  <section className="bg-[#edf8f5] py-20 md:py-24"><div className="container mx-auto px-4"><SectionHeader label="Confidence before claims" title="Sample Sizes and" gradientText="Statistical Honesty" subtitle="Intersectional analysis creates more cells. Each cell needs enough evidence to support what the report says."/><div className="mx-auto max-w-6xl"><DataTable headers={["Claim", "Approximate sample per group", "How it is reported"]} rows={[["Directional signal", "30–100", "Indicative; worth investigating, not a measured disparity"],["Rate within ±10% at 95% confidence", "~96", "Adequate for internal triage"],["Rate within ±5% at 95% confidence", "~385", "Typical target for a reportable finding"],["Rate within ±3% at 95% confidence", "~1,067", "For findings likely to be published or filed"]]} minWidth={760}/><p className="mt-7 text-center text-sm leading-6 text-muted-foreground">These volumes apply to each intersectional cell, not only to the marginal group. Where data cannot support a claim, the report labels the result indicative rather than overstating certainty.</p></div></div></section>
);

export const DeliverablesAndFailureModes = () => (
  <>
    <section id="report-contents" className="bg-background py-20 md:py-24"><div className="container mx-auto px-4"><Reveal className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><FileCheck2 className="h-8 w-8 text-primary"/><h2 className="mt-6 font-heading text-4xl font-bold">What You Get</h2><p className="mt-5 leading-7 text-muted-foreground">A repeatable audit asset, not only a slide deck. You keep the test sets so your team can reproduce the baseline after the model changes.</p></div><div className="grid gap-x-10 border-y border-border md:grid-cols-2">{["Fairness audit report with worked examples","Metric appendix with confidence intervals and cell sizes","Method statement and evaluator-panel composition","Probe sets and reusable test data","Marginal and intersectional breakdowns","Data-side remediation notes where identifiable","Live walkthrough for ML and compliance teams"].map((item, i) => <div key={item} className="flex gap-3 border-b border-border py-5"><CheckCircle2 className="h-5 w-5 shrink-0 text-primary"/><span className="text-sm font-semibold">{item}</span></div>)}</div></Reveal></div></section>
    <section className="bg-[#101a2c] py-20 text-white md:py-24"><div className="container mx-auto px-4"><SectionHeader light label="Failure patterns" title="Where Bias Audits" gradientText="Go Wrong"/><div className="mx-auto max-w-7xl"><div className="[&_td]:!text-white/65 [&_th]:!text-white [&>div]:!border-white/10 [&>div]:!bg-[#101a2c]"><DataTable headers={["Failure", "What happens", "How we avoid it"]} rows={failureModes} minWidth={920}/></div></div></div></section>
  </>
);

export const BoundariesEngagementWhy = () => (
  <>
    <section className="bg-background py-20 md:py-24"><div className="container mx-auto px-4"><Reveal className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><LockKeyhole className="h-8 w-8 text-primary"/><h2 className="mt-6 font-heading text-4xl font-bold">What We Do Not Do</h2><p className="mt-5 leading-7 text-muted-foreground">The limits are part of a defensible engagement, not footer disclaimers.</p></div><div className="divide-y divide-border border-y border-border">{[["Certify models as unbiased", "We measure against stated definitions, groups and data at a point in time."],["Provide legal advice", "We produce evidence your counsel can assess."],["Audit our own work", "Prior training-data or annotation involvement is disclosed and our role is restricted or referred."],["Soften findings", "Findings are reported as measured under the agreed scope."],["Choose metrics after results", "The primary metric is agreed before the model is tested."]].map(([title, text]) => <div key={title} className="grid gap-2 py-5 sm:grid-cols-[210px_1fr]"><h3 className="font-heading font-bold">We do not {title.toLowerCase()}.</h3><p className="text-sm leading-6 text-muted-foreground">{text}</p></div>)}</div></Reveal></div></section>
    <section className="bg-muted/35 py-20 md:py-24"><div className="container mx-auto px-4"><SectionHeader label="Flexible scope" title="How to" gradientText="Engage"/><div className="mx-auto grid max-w-6xl gap-px overflow-hidden rounded-[2rem] border border-border bg-border md:grid-cols-3">{[["Baseline audit", "One model, a defined scope and one or two languages. Typically 5–7 weeks."],["Programme audit", "Multiple models or languages, phased under one comparable method and quarterly reporting."],["Re-audit cadence", "Re-run retained probes after material model or training-data changes. Typically 2–3 weeks."]].map(([title, text], i) => <article key={title} className="bg-card p-7"><span className="font-mono text-xs text-primary">0{i + 1}</span><h3 className="mt-5 font-heading text-xl font-bold">{title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{text}</p></article>)}</div><div className="mt-8 text-center"><Link to="/contact-us" className="inline-flex items-center gap-2 rounded-xl bg-gradient-primary px-7 py-4 text-sm font-bold text-primary-foreground shadow-soft">Request a Fairness Audit Scope <ArrowRight className="h-4 w-4"/></Link></div></div></section>
    <section className="bg-[#edf8f5] py-20 md:py-24"><div className="container mx-auto px-4"><SectionHeader label="Why eQOURSE" title="The Human Bench Behind" gradientText="the Measurement"/><div className="mx-auto grid max-w-7xl gap-x-8 border-y border-border md:grid-cols-2">{[[UsersRound,"500+ trained evaluators in our India-led delivery network"],[Globe2,"30+ global languages, with deep Indian regional-language coverage"],[Scale,"No scoring system or decision-tool product to protect"],[ShieldCheck,"ISO 9001 and ISO 27001 certified processes"],[FileCheck2,"Education and assessment SMEs who understand defensible measurement"],[CheckCircle2,"Continuity from data collection and annotation through re-testing"]].map(([Icon, text], i) => { const C = Icon as typeof UsersRound; return <div key={String(text)} className="flex gap-4 border-b border-border py-6"><C className="h-5 w-5 shrink-0 text-primary"/><span className="text-sm font-semibold">{String(text)}</span><span className="ml-auto font-mono text-[10px] text-primary">0{i + 1}</span></div>; })}</div></div></section>
  </>
);

export const RelatedAndFaq = () => (
  <>
    <section className="bg-background py-20 md:py-24"><div className="container mx-auto px-4"><SectionHeader label="Connected evidence" title="Related" gradientText="Services"/><div className="mx-auto grid max-w-6xl gap-px overflow-hidden rounded-[2rem] border border-border bg-border md:grid-cols-3">{[
      ["AI Red Teaming & Adversarial Testing", "Try to make the system fail and document reproducible attacks", "/ai-data-services/model-testing/ai-red-teaming"], ["LLM Evaluation", "Measure quality, groundedness, task success and automated-judge reliability", "/ai-data-services/model-testing/llm-evaluation"], ["ASR & Speech Model Testing", "WER, CER, semantic, entity, accent and acoustic-condition testing", "/ai-data-services/model-testing/asr-speech-model-testing"], ["Computer Vision Model Testing", "Real-world test sets and slice-level visual failure analysis", "/ai-data-services/model-testing/computer-vision-model-testing"], ["Dataset QA & Label Audit", "Review label quality before measuring fairness", "/ai-data-services/cleaning-validation/dataset-qa-label-audit"], ["LLM & RLHF Annotation", "Build alignment data with a separate evidence boundary", "/ai-data-services/annotation-labeling/llm-rlhf-annotation"],
    ].map(([title, text, href]) => href ? <Link key={title} to={href} className="group bg-card p-6 transition-colors hover:bg-primary/[.045]"><h3 className="font-heading font-bold">{title}</h3><p className="mt-2 text-sm text-muted-foreground">{text}</p><ArrowRight className="mt-6 h-4 w-4 text-primary transition-transform group-hover:translate-x-1"/></Link> : <div key={title} className="bg-card p-6"><h3 className="font-heading font-bold">{title}</h3><p className="mt-2 text-sm text-muted-foreground">{text}</p></div>)}</div><p className="mt-7 text-center text-sm text-muted-foreground">Return to <Link to="/ai-data-services/model-testing" className="font-bold text-primary hover:underline">AI model testing and evaluation services</Link>.</p></div></section>
    <RelatedBlogs />
    <FAQSection faqs={biasFairnessFaqs.map(([question, answer]) => ({ question, answer }))} label="Fairness audit FAQ" title="Questions Before an Audit"/>
  </>
);
