import { Helmet } from "react-helmet-async";
import RelatedBlogs from "@/components/blog/RelatedBlogs";
import { Braces, Languages, Network } from "lucide-react";
import AIDataServicesLayout from "../../shared/AIDataServicesLayout";
import SEOHead from "../../shared/SEOHead";
import ServiceHero from "../../shared/ServiceHero";
import FAQSection from "../../shared/FAQSection";
import ServiceCTA from "../../shared/ServiceCTA";
import { HardCasesAndLanguages, OperationsAndRelated, TaxonomySection, TextAnnotationTypes, TextDefinition, TextProcess, TextQuality } from "./TextNLPAnnotationCoreSections";

const canonical = "https://www.eqourse.com/ai-data-services/annotation-labeling/text-nlp-annotation";
const faqs = [
  ["What is text annotation?", "Text annotation adds structure and meaning to written language so a model can learn entities, sentiment, intent, relations and categories within text."],
  ["What types of text annotation does eQOURSE provide?", "Named entity recognition, nested and overlapping entities, relation extraction, coreference, classification, sentiment, intent and slots, syntax, span extraction, relevance rating, MT post-editing, summary quality, semantic similarity and taxonomy design."],
  ["What is the difference between text annotation and document annotation?", "If a label depends on where text sits on a page, use document annotation. If the text is already clean digital data and only its meaning matters, use text annotation."],
  ["What is the difference between text annotation and LLM evaluation?", "Text annotation labels language as training data. LLM evaluation judges language a model produced. They use different reviewers and quality metrics."],
  ["How do you design an annotation taxonomy?", "We test mutual exclusivity, exhaustiveness, learnability, boundary rules, granularity and real-data grounding, then stress-test the label set against genuine corpus samples before production."],
  ["How do you measure subjective annotation quality?", "We use Cohen's kappa or Krippendorff's alpha, strict and relaxed span F1, boundary agreement, blind duplicates, expert gold sets and senior adjudication."],
  ["How do you handle nested or overlapping entities?", "The guideline defines whether to label outer spans, all layers or apply priority rules, with worked domain examples before production."],
  ["Do you support Indic languages and code-mixed text?", "Yes. We handle Hinglish and other code-mixed varieties, romanised Indic, transliteration variance, script switching, dialect and honorific register across 30+ languages."],
  ["Can you provide domain experts?", "Yes. Qualified reviewers cover medical, legal, finance, education, technical and linguistics domains."],
  ["What output formats do you deliver?", "JSON, JSONL, CoNLL-U, BIO/IOB/IOBES, spaCy, Hugging Face datasets, brat, XML, CSV, TSV, Label Studio JSON or a custom schema."],
  ["Do you use models to pre-annotate text?", "Where appropriate, reviewers correct pre-annotations while recall is monitored against manual controls. Early taxonomies, rare classes and subjective tasks remain human-first."],
  ["Can you do machine translation post-editing?", "Yes, with accuracy, fluency, terminology, register and cultural-fit error typology alongside our translation and localisation services."],
  ["How much does text annotation cost?", "Cost depends on complexity, label density, taxonomy clarity, text length, language, domain expertise, agreement target, quality, turnaround and security."],
  ["How is our text data kept secure?", "Work uses ISO 27001 certified processes, NDAs, role-based access, PII controls, audit trails, secure delivery and contract-defined retention and deletion."],
  ["How do we start?", "Share a representative text sample and taxonomy—or ask us to design one—and we will return annotated output plus an agreement report."],
].map(([question,answer])=>({question,answer}));
const offers = ["Named Entity Recognition Annotation","Nested and Overlapping Entity Annotation","Relation Extraction","Coreference Resolution","Text Classification","Sentiment and Aspect-Based Sentiment Annotation","Intent Classification and Slot Filling","Part-of-Speech and Syntactic Annotation","Text Span Highlighting and Extraction","Search and Query Relevance Rating","Machine Translation Post-Editing","Summarisation Quality Rating","Semantic Similarity and Paraphrase Labeling","Annotation Taxonomy Design"];
const schema = {"@context":"https://schema.org","@graph":[{"@type":"Service","@id":`${canonical}#service`,name:"Text & NLP Annotation Services",serviceType:"Text and NLP Annotation",url:canonical,description:"Text and NLP annotation services including NER, relations, sentiment, intent and taxonomy design across 30+ languages with Indic and code-mixed coverage and measured agreement.",provider:{"@type":"Organization",name:"eQOURSE",url:"https://www.eqourse.com/",address:[{"@type":"PostalAddress",addressCountry:"IN"},{"@type":"PostalAddress",addressCountry:"SG"}]},areaServed:"Worldwide",availableLanguage:["en","hi","bn","ta","te","mr","gu","kn","ml","pa","or","as","ur"],isPartOf:{"@type":"Service","@id":"https://www.eqourse.com/ai-data-services/annotation-labeling#service",name:"Data Annotation & Labeling Services",url:"https://www.eqourse.com/ai-data-services/annotation-labeling"},hasOfferCatalog:{"@type":"OfferCatalog",name:"Text and NLP Annotation Services",itemListElement:offers.map(name=>({"@type":"Offer",itemOffered:{"@type":"Service",name}}))}},{"@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"Home",item:"https://www.eqourse.com/"},{"@type":"ListItem",position:2,name:"AI Data Services",item:"https://www.eqourse.com/ai-data-services"},{"@type":"ListItem",position:3,name:"Data Annotation & Labeling",item:"https://www.eqourse.com/ai-data-services/annotation-labeling"},{"@type":"ListItem",position:4,name:"Text & NLP Annotation",item:canonical}]},{"@type":"FAQPage",mainEntity:faqs.map(({question,answer})=>({"@type":"Question",name:question,acceptedAnswer:{"@type":"Answer",text:answer}}))}]};

const TextNLPAnnotationPage = () => <AIDataServicesLayout breadcrumbs={[{label:"AI Data Services",href:"/ai-data-services"},{label:"Data Annotation & Labeling",href:"/ai-data-services/annotation-labeling"},{label:"Text & NLP Annotation"}]}>
  <SEOHead title="Text & NLP Annotation Services for Language AI | eQOURSE" description="NER, sentiment, intent and relation annotation across 30+ languages, including Indic and code-mixed text, with native reviewers and measured agreement." canonical={canonical} keywords="text annotation services, NLP annotation, NER annotation, sentiment annotation, intent classification, relation extraction, Indic language annotation, code mixed text annotation, taxonomy design" ogImage="https://www.eqourse.com/assets/ai-data/annotation-labeling/text-nlp-annotation/text-nlp-annotation-og.webp"/>
  <Helmet><link rel="preload" as="image" href="/assets/ai-data/annotation-labeling/text-nlp-annotation/text-nlp-annotation-services-hero.avif" type="image/avif" fetchPriority="high"/><script type="application/ld+json">{JSON.stringify(schema)}</script></Helmet>
  <ServiceHero tone="dark" preHeadline="Taxonomy-Tested Language Data" headline="Text & NLP Annotation Services for" headlineAccent="Language AI" subtext="Build NLP, search, chatbot and LLM training data across 30+ languages with native reviewers, deep Indic and code-mixed coverage, and measured agreement on every batch." ctaText="Start Free Pilot" ctaLink="/free-pilot" secondaryCtaText="Talk to a Data Specialist" secondaryCtaLink="/contact-us" imageSrc="/assets/ai-data/annotation-labeling/text-nlp-annotation/text-nlp-annotation-services-hero.webp" imageAvifSrc="/assets/ai-data/annotation-labeling/text-nlp-annotation/text-nlp-annotation-services-hero.avif" imageAlt="Annotation specialist marking entity spans and sentiment labels in a text annotation interface" imageWidth={1200} imageHeight={800} trustStats={[{value:"30+ languages",label:"Native and domain reviewers"},{value:"Indic + code-mixed",label:"Script, dialect and register"},{value:"Agreement reported",label:"Every production batch"}]} rotatingBadges={[{icon:Braces,title:"Span-aware",subtitle:"Nested · Overlapping · Exact",color:"hsl(170 82% 55%)"},{icon:Network,title:"Relation-aware",subtitle:"Entities · Links · Coreference",color:"hsl(35 92% 58%)"},{icon:Languages,title:"Locale-aware",subtitle:"Indic · Romanised · Mixed script",color:"hsl(260 70% 72%)"}]} bottomBadge={{iconText:"NLP",title:"Language made inspectable",subtitle:"Entity → relation → intent → evidence"}}/>
  <TextDefinition/><TextAnnotationTypes/><TaxonomySection/><TextProcess/><TextQuality/><HardCasesAndLanguages/><OperationsAndRelated/>
  <RelatedBlogs />
  <FAQSection faqs={faqs} label="Text Annotation FAQs" title="Frequently Asked Questions About Text & NLP Annotation"/>
  <ServiceCTA headline="Structure Your Language Data for Production" subtext="Send a representative sample and label set—or let us design one—and we’ll stress-test the taxonomy, run a pilot and report agreement before volume." ctaText="Start Free Pilot" ctaLink="/free-pilot" secondaryCtaText="Talk to a Data Specialist" secondaryCtaLink="/contact-us" note="Pilot includes annotated output and an agreement report"/>
</AIDataServicesLayout>;
export default TextNLPAnnotationPage;
