import { Helmet } from "react-helmet-async";
import RelatedBlogs from "@/components/blog/RelatedBlogs";
import { AudioLines, Languages, Users } from "lucide-react";
import AIDataServicesLayout from "../../shared/AIDataServicesLayout";
import SEOHead from "../../shared/SEOHead";
import ServiceHero from "../../shared/ServiceHero";
import FAQSection from "../../shared/FAQSection";
import ServiceCTA from "../../shared/ServiceCTA";
import { ASRSecurityAndCost, AudioAnnotationTypes, AudioDefinition, AudioProcess, AudioRelated, DeliveryUseCases, HardSpeechAndIndia, SpeechQuality, VerbatimDecision } from "./AudioSpeechAnnotationCoreSections";

const canonical="https://www.eqourse.com/ai-data-services/annotation-labeling/audio-speech-annotation";
const faqs=[
  ["What is audio annotation?","Audio annotation turns recorded sound into structured data: what was said, who said it, when and how they said it, and which non-speech sounds were present."],
  ["What types of audio annotation does eQOURSE provide?","Verbatim and clean transcription, timing, forced alignment, diarization, speaker and language identification, emotion, acoustic events, phonetics, wake words, voice intent, audio quality and TTS prosody review."],
  ["What is the difference between verbatim and clean transcription?","Verbatim preserves fillers, false starts and stutters. Clean transcription removes disfluencies and normalises numbers and dates. Verbatim generally fits ASR; clean fits subtitles, search and readable archives."],
  ["What is speaker diarization?","Speaker diarization determines who spoke when and maintains consistent speaker identities through overlap and interruption. It is measured separately using diarization error rate."],
  ["How do you measure speech annotation quality?","We report raw and normalised WER, DER, timestamp accuracy, speaker consistency, style-guide conformance, hidden gold clips and second-pass listening review, broken down by audio condition."],
  ["How long does transcription take?","Planning uses a real-time ratio. Clean single-speaker work is roughly 2–4× real time; verbatim multi-speaker work with diarization is often 4–8×; difficult audio may exceed 10×. Your pilot confirms the actual rate."],
  ["Do you handle Indian regional languages, accents and code-switched speech?","Yes. Alongside global-language delivery, our India-wide coverage includes regional languages, regional Indian English, dialects, Hinglish, Tanglish, Manglish, script decisions, register and lower-resource speech varieties."],
  ["Which languages do you support?","We support 30+ global languages across European, Asian and Middle Eastern markets. Our specialist advantage is comprehensive coverage across India's regional languages, accents, dialects and code-switched speech."],
  ["How do you handle overlap and inaudible speech?","The style guide defines whether all overlapping speakers or only the dominant speaker are captured. Inaudible sections are flagged with duration and never invented."],
  ["What output formats do you deliver?","JSON, JSONL, RTTM, CTM, TextGrid, SRT, VTT, Kaldi directories, Hugging Face format, ELAN EAF, CSV, TSV, speaker-labeled text or a custom schema."],
  ["Do you use ASR to accelerate transcription?","Yes for suitable clean audio, with mandatory listening review. Accented, overlapping, noisy, code-switched and specialist audio returns to manual transcription when ASR degrades."],
  ["How much does audio annotation cost?","Cost depends on style, timing granularity, speakers and overlap, audio quality, accent, language, code-switching, domain vocabulary, additional layers, accuracy, security and turnaround."],
  ["How is our audio kept secure?","Voice is treated as biometric data using ISO 27001 processes, NDAs, vetted pools, role-based access, PII controls, restricted environments, audit trails and defined retention and deletion."],
  ["Can you also produce subtitles or captions?","Transcription and timing can continue into our subtitling and accessible-media services for formatting, styling and compliance delivery."],
  ["How do we start?","Share 30–60 minutes of representative difficult audio and your style requirements. We return annotated output with WER, diarization metrics and a planning ratio."],
].map(([question,answer])=>({question,answer}));
const offers=["Verbatim Transcription","Clean and Normalised Transcription","Timestamping and Segmentation","Forced Alignment","Speaker Diarization","Speaker Identification and Voice Matching","Language and Dialect Identification","Emotion and Tone Labeling","Acoustic Event Classification","Phonetic Transcription","Wake Word and Keyword Spotting","Voice Intent and Slot Labeling","Audio Quality Rating","TTS Data QC and Prosody Review"];
const schema={"@context":"https://schema.org","@graph":[{"@type":"Service","@id":`${canonical}#service`,name:"Audio & Speech Annotation Services",serviceType:"Audio and Speech Annotation",url:canonical,description:"Multilingual audio and speech annotation for ASR and voice AI across 30+ global languages, with comprehensive Indian regional-language, accent and code-switching coverage.",provider:{"@type":"Organization",name:"eQOURSE",url:"https://www.eqourse.com/",address:[{"@type":"PostalAddress",addressCountry:"IN"},{"@type":"PostalAddress",addressCountry:"SG"}]},areaServed:"Worldwide",availableLanguage:["en","es","fr","de","pt","ar","zh","ja","ko","id","ms","th","vi","hi","bn","ta","te","mr","gu","kn","ml","pa","or","as","ur"],isPartOf:{"@type":"Service","@id":"https://www.eqourse.com/ai-data-services/annotation-labeling#service",name:"Data Annotation & Labeling Services",url:"https://www.eqourse.com/ai-data-services/annotation-labeling"},hasOfferCatalog:{"@type":"OfferCatalog",name:"Audio and Speech Annotation Services",itemListElement:offers.map(name=>({"@type":"Offer",itemOffered:{"@type":"Service",name}}))}},{"@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"Home",item:"https://www.eqourse.com/"},{"@type":"ListItem",position:2,name:"AI Data Services",item:"https://www.eqourse.com/ai-data-services"},{"@type":"ListItem",position:3,name:"Data Annotation & Labeling",item:"https://www.eqourse.com/ai-data-services/annotation-labeling"},{"@type":"ListItem",position:4,name:"Audio & Speech Annotation",item:canonical}]},{"@type":"FAQPage",mainEntity:faqs.map(({question,answer})=>({"@type":"Question",name:question,acceptedAnswer:{"@type":"Answer",text:answer}}))}]};

const AudioSpeechAnnotationPage=()=> <AIDataServicesLayout breadcrumbs={[{label:"AI Data Services",href:"/ai-data-services"},{label:"Data Annotation & Labeling",href:"/ai-data-services/annotation-labeling"},{label:"Audio & Speech Annotation"}]}>
  <SEOHead title="Audio & Speech Annotation Services for Voice AI | eQOURSE" description="Speech annotation for ASR across 30+ global languages, with comprehensive Indian regional-language, accent, dialect and code-switching coverage." canonical={canonical} keywords="multilingual audio annotation services, global speech annotation services, speaker diarization services, ASR training data, voice AI training data, Indian regional language annotation, Indian accent speech annotation, code-switched speech annotation, WER, DER" ogImage="https://www.eqourse.com/assets/ai-data/annotation-labeling/audio-speech-annotation/audio-speech-annotation-og.webp"/>
  <Helmet><link rel="preload" as="image" href="/assets/ai-data/annotation-labeling/audio-speech-annotation/audio-speech-annotation-services-hero.avif" type="image/avif" fetchPriority="high"/><script type="application/ld+json">{JSON.stringify(schema)}</script></Helmet>
  <ServiceHero tone="dark" preHeadline="Native Listening for Real-World Speech" headline="Audio & Speech Annotation Services for" headlineAccent="Voice AI and ASR" subtext="Transcription, speaker diarization, timing, emotion, acoustic events and phonetic labeling across 30+ global languages—with comprehensive coverage of India's regional languages, accents, dialects and code-switched speech." ctaText="Start Free Pilot" ctaLink="/free-pilot" secondaryCtaText="Talk to a Data Specialist" secondaryCtaLink="/contact-us" imageSrc="/assets/ai-data/annotation-labeling/audio-speech-annotation/audio-speech-annotation-services-hero.webp" imageAvifSrc="/assets/ai-data/annotation-labeling/audio-speech-annotation/audio-speech-annotation-services-hero.avif" imageAlt="Transcriber annotating speech segments and speaker labels on an audio waveform with headphones on" imageWidth={1200} imageHeight={800} trustStats={[{value:"30+ languages",label:"Global delivery"},{value:"India-wide",label:"Regional language depth"},{value:"ISO 9001 + 27001",label:"Quality + security"}]} rotatingBadges={[{icon:Users,title:"Speaker-aware",subtitle:"Turns · Roles · Overlap",color:"hsl(170 82% 55%)"},{icon:AudioLines,title:"Time-aware",subtitle:"Words · Events · Boundaries",color:"hsl(35 92% 58%)"},{icon:Languages,title:"Language-aware",subtitle:"Global · Regional · Mixed",color:"hsl(205 78% 66%)"}]} bottomBadge={{iconText:"ASR",title:"Speech made measurable",subtitle:"Words → speakers → time → conditions"}}/>
  <AudioDefinition/><AudioAnnotationTypes/><VerbatimDecision/><AudioProcess/><SpeechQuality/><HardSpeechAndIndia/><DeliveryUseCases/><ASRSecurityAndCost/><AudioRelated/>
  <RelatedBlogs />
  <FAQSection faqs={faqs} label="Speech Annotation FAQs" title="Frequently Asked Questions About Audio & Speech Annotation"/>
  <ServiceCTA headline="Turn Your Audio Into Model-Ready Speech Data" subtext="Send your most difficult audio, not your cleanest—we’ll return a pilot with real error rates and a throughput estimate you can budget against." ctaText="Start Free Pilot" ctaLink="/free-pilot" secondaryCtaText="Talk to a Data Specialist" secondaryCtaLink="/contact-us" note="Pilot includes WER, diarization metrics and a planning ratio"/>
</AIDataServicesLayout>;
export default AudioSpeechAnnotationPage;
