import { Link } from "react-router-dom";
import { ArrowRight, BadgeCheck, CheckCircle2, EyeOff, FileCheck2, FileWarning, Fingerprint, Languages, ListChecks, LockKeyhole, Radar, ScanSearch, ShieldAlert, ShieldCheck, UserCheck } from "lucide-react";
import SectionHeader from "../../shared/SectionHeader";
import { useScrollReveal } from "@/hooks/use-scroll-reveal";
import { piiFaqs, piiModalities, piiProcess, redactionMethods } from "./PiiRedactionContent";
import RelatedBlogs from "@/components/blog/RelatedBlogs";

const Reveal=({children,className=""}:{children:React.ReactNode;className?:string})=>{const{ref,isVisible}=useScrollReveal();return <div ref={ref} className={`reveal-up ${isVisible?"visible":""} ${className}`}>{children}</div>};

export const PiiMotionStyles=()=> <style>{`
  @keyframes pii-redact{0%,18%{transform:scaleX(.08);opacity:.25}48%,100%{transform:scaleX(1);opacity:1}}
  @keyframes pii-scan{0%{transform:translateY(-150%);opacity:0}15%,78%{opacity:.7}100%{transform:translateY(650%);opacity:0}}
  @keyframes pii-loop{to{stroke-dashoffset:-48}}
  .pii-redaction-bar{transform-origin:left;animation:pii-redact 4.8s ease-in-out infinite alternate}
  .pii-redaction-bar:nth-child(2){animation-delay:.45s}.pii-redaction-bar:nth-child(3){animation-delay:.9s}
  .pii-scan{animation:pii-scan 5.6s ease-in-out infinite}.pii-loop{animation:pii-loop 4.8s linear infinite}
  @media(prefers-reduced-motion:reduce){.pii-redaction-bar,.pii-scan,.pii-loop{animation:none!important}}
`}</style>;

export const PiiTrustStrip=()=>{const items=[["Recall measured","Against verified reference"],["Beyond names","Quasi-identifiers assessed"],["Output verified","Independent second pass"],["Risk stated","No false perfection claim"]];return <section aria-label="PII redaction service assurances" className="overflow-hidden border-y border-border bg-white"><div className="flex w-max animate-marquee">{[...items,...items, ...items].map(([a,b],i)=><div key={`${a}-${i}`} className="flex min-w-[260px] shrink-0 flex-col items-center justify-center border-r border-border bg-white px-8 py-5 text-center"><strong className="text-sm text-foreground">{a}</strong><p className="mt-1 text-xs text-muted-foreground">{b}</p></div>)}</div></section>;};

export const PiiDefinitionAndIdentifiers=()=> <>
  <section className="bg-background py-20 md:py-24"><div className="container mx-auto px-4"><Reveal className="mx-auto grid max-w-6xl gap-14 lg:grid-cols-[.86fr_1.14fr]"><div><span className="font-mono text-xs font-bold uppercase tracking-[.2em] text-primary">Detection is the hard half</span><h2 className="mt-5 font-heading text-4xl font-bold leading-tight md:text-5xl">What Is PII Detection <span className="text-primary">and Redaction?</span></h2><p className="mt-6 leading-8 text-muted-foreground">It is the work of finding personal data and removing, masking or replacing it so data can be used, shared or trained on without exposing the people in it.</p><p className="mt-4 leading-8 text-muted-foreground">Personal data does not announce itself. It appears in narrative text, a corner of a photograph, file metadata, a voice or a combination of otherwise ordinary fields.</p></div><div className="overflow-hidden rounded-[2rem] border border-border bg-[#f5faf8] p-7 md:p-9"><ScanSearch className="h-8 w-8 text-primary"/><h3 className="mt-5 font-heading text-2xl font-bold">An honest statement about completeness</h3><p className="mt-4 text-base font-semibold leading-7 text-foreground">No detection process finds 100% of personal data in unstructured content.</p><p className="mt-4 text-sm leading-7 text-muted-foreground">We measure recall against a human-verified reference set, tune toward the errors that matter, independently verify the output and report residual risk so you can decide what the data is safe for.</p><div className="relative mt-7 overflow-hidden rounded-xl border border-border bg-white p-5"><div className="space-y-3">{["Direct identifier candidate","Narrative quasi-identifier","Embedded metadata field"].map((x,i)=><div key={x} className="grid grid-cols-[1fr_110px] items-center gap-3"><span className="h-2 rounded-full bg-slate-200"/><span className={`pii-redaction-bar h-5 rounded ${i===1?"bg-amber-400":"bg-primary"}`}/></div>)}</div><div className="pii-scan pointer-events-none absolute inset-x-0 top-0 h-16 bg-gradient-to-b from-transparent via-primary/10 to-transparent"/></div></div></Reveal></div></section>
  <section className="bg-[#f3f7f6] py-20 md:py-24"><div className="container mx-auto px-4"><SectionHeader label="Agree the definition at scoping" title="What Counts as" gradientText="Personal Data" subtitle="The applicable definition depends on jurisdiction, sector and use case. We work to the standard agreed with you and your counsel."/><div className="mx-auto mt-12 grid max-w-6xl gap-px overflow-hidden rounded-[2rem] border border-border bg-border md:grid-cols-3">{[[Fingerprint,"Direct identifiers","Names, email, phone, national identifiers, account numbers, addresses, biometrics, device identifiers and vehicle registration."],[Radar,"Quasi-identifiers","Postcode, birth date, gender, employer, job title, rare conditions, precise locations and timestamps that identify in combination."],[ShieldAlert,"Sensitive data","Health, biometric, genetic, ethnicity, belief, political opinion, sexual orientation, criminal, financial and children's data."]].map(([Icon,a,b])=>{const C=Icon as typeof Fingerprint;return <article key={a as string} className="bg-card p-7"><C className="h-7 w-7 text-primary"/><h3 className="mt-6 font-heading text-xl font-bold">{a as string}</h3><p className="mt-4 text-sm leading-7 text-muted-foreground">{b as string}</p></article>})}</div><div className="mx-auto mt-8 max-w-6xl border-l-4 border-amber-400 bg-amber-50 p-5 text-sm leading-7 text-amber-950"><strong>This page is not legal advice.</strong> Definitions and obligations differ across GDPR, India's DPDP Act, HIPAA, CCPA and sector rules, and they change. Agree the applicable standard with your legal team.</div></div></section>
</>;

export const QuasiIdentifierRisk=()=> <section className="overflow-hidden bg-[radial-gradient(circle_at_78%_25%,hsl(174_52%_18%),transparent_33%),linear-gradient(135deg,hsl(225_47%_13%),hsl(226_43%_17%))] py-20 text-white md:py-28"><div className="container mx-auto px-4"><Reveal className="mx-auto grid max-w-6xl items-center gap-14 lg:grid-cols-[.86fr_1.14fr]"><div><span className="font-mono text-xs font-bold uppercase tracking-[.2em] text-teal-300">Removing names is not anonymisation</span><h2 className="mt-5 font-heading text-4xl font-bold leading-tight md:text-5xl">The Quasi-Identifier <span className="text-teal-300">Problem</span></h2><p className="mt-6 leading-8 text-white/70">A postcode, exact birth date and gender may identify nobody alone and one person together. Re-identification risk lives in combinations, rarity, free-text leakage, cross-record linkage and longitudinal patterns.</p><p className="mt-5 text-sm font-semibold leading-7 text-white/90">We assess the combination—not just each field in isolation.</p></div><div><div className="grid gap-3 sm:grid-cols-[1fr_auto_1fr_auto_1fr]"><div className="rounded-2xl border border-white/15 bg-white/[.06] p-5"><span className="text-[10px] uppercase tracking-wider text-white/45">Field A</span><div className="mt-5 h-3 w-4/5 rounded bg-white/25"/><p className="mt-4 text-xs text-white/55">Not identifying alone</p></div><span className="hidden self-center text-2xl text-teal-300 sm:block">+</span><div className="rounded-2xl border border-white/15 bg-white/[.06] p-5"><span className="text-[10px] uppercase tracking-wider text-white/45">Field B</span><div className="mt-5 h-3 w-3/5 rounded bg-white/25"/><p className="mt-4 text-xs text-white/55">Not identifying alone</p></div><span className="hidden self-center text-2xl text-teal-300 sm:block">→</span><div className="rounded-2xl border border-amber-300/45 bg-amber-300/10 p-5"><Fingerprint className="h-8 w-8 text-amber-300"/><p className="mt-4 text-sm font-bold text-amber-100">Unique in combination</p></div></div><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4">{["Generalise","Suppress rare values","Aggregate","Add measured noise"].map(x=><span key={x} className="rounded-xl border border-white/10 px-3 py-3 text-center text-xs text-white/65">{x}</span>)}</div><p className="mt-6 text-sm leading-7 text-white/60">Every mitigation costs analytical utility. We report how much risk reduction each option buys and document the decision rather than choosing it for you.</p></div></Reveal></div></section>;

export const ModalityAndMethods=()=> <>
  <section className="bg-background py-20 md:py-24"><div className="container mx-auto px-4"><SectionHeader label="Multimodal discovery" title="PII Across Every" gradientText="Data Type" subtitle="Visible content is only one layer. Metadata, embedded text and cross-field combinations are part of the same review."/><Reveal className="mx-auto mt-12 max-w-6xl overflow-hidden rounded-[2rem] border border-border bg-[#f8faf9] shadow-soft"><img src="/assets/ai-data/cleaning-validation/pii-detection-redaction/pii-redaction-modalities-and-metadata.webp" alt="Examples of text redaction, abstract figure masking, hidden document text and quasi-identifier combination risk" width="1200" height="800" loading="lazy" decoding="async" className="w-full"/></Reveal><p className="mx-auto mb-3 mt-10 max-w-6xl text-center text-xs text-muted-foreground md:hidden">Swipe horizontally to compare modalities</p><Reveal className="mx-auto max-w-6xl overflow-x-auto rounded-[2rem] border border-border"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-[#111a2d] text-white"><tr><th className="px-6 py-5">Modality</th><th className="px-6 py-5">What we find and handle</th></tr></thead><tbody>{piiModalities.map(([a,b],i)=><tr key={a} className={i%2?"bg-muted/30":"bg-card"}><th className="border-t border-border px-6 py-5 font-heading font-bold">{a}</th><td className="border-t border-border px-6 py-5 leading-7 text-muted-foreground">{b}</td></tr>)}</tbody></table></Reveal></div></section>
  <section className="bg-[#f3f7f6] py-20 md:py-24"><div className="container mx-auto px-4"><SectionHeader label="Preserve only what the use case needs" title="Four Ways to Remove" gradientText="Personal Data"/><p className="mx-auto mb-3 mt-12 max-w-6xl text-center text-xs text-muted-foreground md:hidden">Swipe horizontally to compare methods</p><Reveal className="mx-auto max-w-6xl overflow-x-auto rounded-[2rem] border border-border"><table className="w-full min-w-[920px] text-left text-sm"><thead className="bg-white"><tr>{["Method","What happens","Reversible","Use when"].map(x=><th key={x} className="border-b border-border px-6 py-5 font-heading">{x}</th>)}</tr></thead><tbody>{redactionMethods.map((r,i)=><tr key={r[0]} className={i===2?"bg-amber-50":"bg-white"}>{r.map((c,j)=><td key={c} className={`border-t border-border px-6 py-5 leading-7 ${j===0?"font-bold text-foreground":"text-muted-foreground"}`}>{c}</td>)}</tr>)}</tbody></table></Reveal><Reveal className="mx-auto mt-10 grid max-w-6xl gap-6 md:grid-cols-2"><div className="border-l-4 border-primary bg-white p-6"><h3 className="font-heading text-xl font-bold">Consistency preserves relationships</h3><p className="mt-3 text-sm leading-7 text-muted-foreground">The same individual must map to the same surrogate across records and batches. Unstable mappings split one person; reused mappings merge different people.</p></div><div className="border-l-4 border-amber-400 bg-white p-6"><h3 className="font-heading text-xl font-bold">Pseudonymisation is not anonymisation</h3><p className="mt-3 text-sm leading-7 text-muted-foreground">Where a mapping exists and re-identification remains possible, pseudonymised data is generally still personal data. Your counsel determines the applicable treatment.</p></div></Reveal></div></section>
</>;

const failures=["PDF black boxes can leave selectable text underneath","EXIF can retain location, device and timestamp metadata","Document properties can retain authors, comments and revision history","Reflections, background crowds and screen-within-screen faces can be missed","Video identifiers can reappear after occlusion for a handful of frames","Removing spoken names does not remove the biometric voiceprint","Free-text columns can defeat schema-level redaction","Cross-field combinations can reconstruct identity","Backups, caches, logs and derived copies can preserve pre-redaction data"];

export const FailureModesAndVerification=()=> <>
  <section className="bg-[#fff7e9] py-20 md:py-24"><div className="container mx-auto px-4"><Reveal className="mx-auto grid max-w-6xl gap-12 lg:grid-cols-[.72fr_1.28fr]"><div><FileWarning className="h-9 w-9 text-amber-600"/><span className="mt-6 block font-mono text-xs font-bold uppercase tracking-[.2em] text-amber-700">Where redaction silently fails</span><h2 className="mt-4 font-heading text-4xl font-bold leading-tight md:text-5xl">The Failure Modes That <span className="text-amber-700">Look Like Success</span></h2><p className="mt-6 leading-8 text-foreground/65">Visible coverage is not proof of removal. These checks are built into discovery and verification because output can look protected while the underlying identifier remains.</p></div><div className="grid gap-px overflow-hidden rounded-[2rem] border border-amber-200 bg-amber-200 sm:grid-cols-2">{failures.map((x,i)=><div key={x} className="bg-white p-5"><span className="font-mono text-[10px] font-bold text-amber-700">{String(i+1).padStart(2,"0")}</span><p className="mt-3 text-sm font-semibold leading-6">{x}</p></div>)}</div></Reveal></div></section>
  <section className="bg-background py-20 md:py-24"><div className="container mx-auto px-4"><Reveal className="mx-auto grid max-w-6xl items-center gap-14 lg:grid-cols-[1.04fr_.96fr]"><div className="relative overflow-hidden rounded-[2rem] border border-border shadow-elevated"><img src="/assets/ai-data/cleaning-validation/pii-detection-redaction/pii-redaction-verification-review.webp" alt="Reviewer independently verifying abstract redaction output with recall and residual-risk indicators" width="1000" height="600" loading="lazy" decoding="async" className="w-full"/><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-[#111a2d] to-transparent p-7 pt-20 text-white"><p className="text-sm font-bold">Independent verification</p><p className="mt-1 text-xs text-white/65">Recall · second pass · adversarial review · residual risk</p></div></div><div><span className="font-mono text-xs font-bold uppercase tracking-[.2em] text-primary">The two errors are not equal</span><h2 className="mt-5 font-heading text-4xl font-bold leading-tight md:text-5xl">Unverified Redaction Is <span className="text-primary">an Assumption</span></h2><p className="mt-6 leading-8 text-muted-foreground">A missed identifier can be a breach and trust failure. An over-redaction usually creates a less useful record. The process is deliberately tuned toward recall, then verified to quantify what remains.</p><div className="mt-7 space-y-3">{["Recall against a human-verified reference set","Independent second-pass review","Adversarial re-identification attempt","Metadata and document text-layer sweeps","Frame sampling across video sequences","Explicit residual risk statement"].map(x=><div key={x} className="flex gap-3 border-b border-border pb-3 text-sm"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-primary"/>{x}</div>)}</div><p className="mt-6 rounded-xl bg-[#edf7f4] p-4 text-sm font-semibold leading-6 text-foreground/75">We report residual risk rather than declaring a dataset completely anonymised.</p></div></Reveal></div></section>
</>;

export const PiiProcessAndDeliverables=()=> <>
  <section className="bg-[#f3f7f6] py-20 md:py-24"><div className="container mx-auto px-4"><SectionHeader label="Discovery before transformation" title="How a Redaction" gradientText="Engagement Runs" subtitle="Verification is a gate, not a closing ceremony. Failed checks return to pilot tuning before delivery."/><Reveal className="mx-auto mt-12 max-w-7xl"><div className="relative hidden h-28 lg:block" aria-hidden="true"><svg viewBox="0 0 1200 105" className="h-full w-full" preserveAspectRatio="none"><title>Seven-step eQOURSE PII redaction process from scoping and discovery through quasi-identifier assessment and pilot to verification and residual risk reporting</title><path d="M52 35H1142c34 0 34 54 0 54H822c-30 0-30-28 0-28h92" fill="none" stroke="hsl(var(--primary))" strokeWidth="2" strokeDasharray="8 8" className="pii-loop"/></svg><div className="absolute inset-x-0 top-3 grid grid-cols-7 gap-3">{piiProcess.map(([n],i)=><div key={n} className="flex justify-center"><span className={`grid h-12 w-12 place-items-center rounded-full border-2 font-mono text-xs font-bold ${i===2||i===6?"border-amber-400 bg-amber-50 text-amber-800":"border-primary bg-white text-primary"}`}>{n}</span></div>)}</div></div><ol className="grid gap-px overflow-hidden rounded-[2rem] border border-border bg-border sm:grid-cols-2 lg:grid-cols-7">{piiProcess.map(([n,a,b],i)=><li key={n} className={`bg-white p-5 ${i===2||i===6?"lg:border-t-4 lg:border-amber-400":""}`}><span className="font-mono text-xs font-bold text-primary lg:hidden">{n}</span><h3 className="mt-4 font-heading text-sm font-bold lg:mt-1">{a}</h3><p className="mt-3 text-xs leading-5 text-muted-foreground">{b}</p></li>)}</ol></Reveal></div></section>
  <section className="bg-background py-20 md:py-24"><div className="container mx-auto px-4"><Reveal className="mx-auto grid max-w-6xl gap-12 lg:grid-cols-[.74fr_1.26fr]"><div><ListChecks className="h-9 w-9 text-primary"/><h2 className="mt-6 font-heading text-4xl font-bold md:text-5xl">What You <span className="text-primary">Get Back</span></h2><p className="mt-5 leading-7 text-muted-foreground">The redacted files are only one deliverable. The evidence around them makes the work reviewable and defensible.</p></div><div className="grid gap-x-8 sm:grid-cols-2">{["Redacted dataset in the original format","Discovery report by category and modality","Re-identification risk assessment","Method register and decision rationale","Measured recall on a verified reference set","Independent verification report","Explicit residual risk statement","Secure pseudonymisation mapping where used","Processing record and audit trail"].map((x,i)=><div key={x} className="flex gap-3 border-b border-border py-4 text-sm"><span className="font-mono text-[10px] text-primary">{String(i+1).padStart(2,"0")}</span><span className="font-medium">{x}</span></div>)}</div></Reveal></div></section>
</>;

export const IndicComplianceSecurity=()=> <>
  <section className="bg-[linear-gradient(135deg,hsl(226_45%_14%),hsl(174_47%_13%))] py-20 text-white md:py-24"><div className="container mx-auto px-4"><Reveal className="mx-auto grid max-w-6xl gap-14 lg:grid-cols-[.82fr_1.18fr]"><div><Languages className="h-9 w-9 text-teal-300"/><h2 className="mt-6 font-heading text-4xl font-bold leading-tight md:text-5xl">Global Language Coverage, With <span className="text-teal-300">Indian Name Depth</span></h2><p className="mt-6 leading-8 text-white/70">Western-name distributions, Western address parsers and monolingual assumptions miss regional names, transliteration variants, code-mixed text and Indian identifier formats.</p></div><div className="grid gap-px overflow-hidden rounded-2xl border border-white/10 bg-white/10 sm:grid-cols-2">{[["Indian name distributions","Regional and less-common surnames need tuned detection"],["Script + transliteration","The same person may appear in multiple scripts and spellings"],["Name-word ambiguity","Given names can also be ordinary words"],["Indian address formats","Structures differ from Western parser assumptions"],["Identifier patterns","Aadhaar, PAN, voter ID, GSTIN and vehicle registration"],["Code-mixed language","Hinglish and other mixed text need native review"]].map(([a,b])=><div key={a} className="bg-white/[.045] p-5"><h3 className="font-heading font-bold text-white">{a}</h3><p className="mt-2 text-xs leading-6 text-white/55">{b}</p></div>)}</div></Reveal><p className="mx-auto mt-8 max-w-6xl text-sm leading-7 text-white/65">Native-speaker review covers Hindi, Bengali, Tamil, Telugu, Marathi, Gujarati, Kannada, Malayalam, Punjabi, Odia, Assamese and Urdu, alongside broader global-language programmes.</p></div></section>
  <section className="bg-background py-20 md:py-24"><div className="container mx-auto px-4"><Reveal className="mx-auto grid max-w-6xl gap-12 lg:grid-cols-2"><div><ShieldCheck className="h-9 w-9 text-primary"/><h2 className="mt-6 font-heading text-3xl font-bold md:text-4xl">How This Supports Compliance Obligations</h2><p className="mt-5 leading-7 text-muted-foreground">Redaction is one control within a compliance programme. It does not make an organisation compliant by itself. We provide controlled processing, documented methodology, measured recall, a processing record and residual-risk evidence.</p><div className="mt-6 border-l-4 border-amber-400 bg-amber-50 p-5 text-sm leading-7"><strong>Legal boundary:</strong> we do not determine what a regulation requires, guarantee compliance or declare data anonymised under a particular regime. Those determinations remain with your counsel.</div></div><div><LockKeyhole className="h-9 w-9 text-primary"/><h2 className="mt-6 font-heading text-3xl font-bold md:text-4xl">Security and Handling</h2><div className="mt-6 grid gap-3 text-sm">{["ISO 9001 and ISO 27001 certified processes","DPA in place before transfer where required","Named, vetted reviewers under NDA","Role-based access and complete audit trails","Restricted or client-perimeter processing","Encrypted transfer and storage","Mappings stored under separate access control","Contract-defined retention and deletion","Sub-processor disclosure where used"].map(x=><div key={x} className="flex gap-3 border-b border-border pb-3"><ShieldCheck className="mt-0.5 h-4 w-4 shrink-0 text-primary"/>{x}</div>)}</div></div></Reveal></div></section>
</>;

export const EngagementRelatedWhy=()=> {const cost=["Modality and volume","PII density","Quasi-identifier analysis depth","Verification intensity","Language and script coverage","Removal versus stable pseudonymisation","Security environment","Turnaround"];return <>
  <section className="bg-[#f3f7f6] py-20 md:py-24"><div className="container mx-auto px-4"><SectionHeader label="Flexible operating model" title="Engagements and" gradientText="Transparent Scoping"/><div className="mx-auto mt-12 grid max-w-6xl gap-px overflow-hidden rounded-[2rem] border border-border bg-border md:grid-cols-2"><div className="bg-white p-7"><h3 className="font-heading text-2xl font-bold">Engagement models</h3><div className="mt-6 space-y-4">{[["Discovery assessment","Find what is present and measure re-identification risk before changing anything"],["One-time redaction","Process and verify a defined dataset"],["Continuous redaction","Protect incoming data before training or analytics"],["Verification only","Independently test an in-house redaction process"],["Method design + handover","Design and tune the method for your team to operate"]].map(([a,b])=><div key={a} className="border-b border-border pb-4"><strong className="text-sm">{a}</strong><p className="mt-1 text-xs leading-5 text-muted-foreground">{b}</p></div>)}</div></div><div className="bg-white p-7"><h3 className="font-heading text-2xl font-bold">What determines cost</h3><div className="mt-6 grid gap-x-8 sm:grid-cols-2">{cost.map((x,i)=><div key={x} className="flex gap-3 border-b border-border py-4 text-sm"><span className="font-mono text-[10px] text-primary">0{i+1}</span>{x}</div>)}</div><p className="mt-6 rounded-xl bg-[#edf7f4] p-4 text-sm leading-6 text-foreground/75"><strong>Start with discovery.</strong> What is actually present is the only sound basis for deciding how much redaction you need.</p></div></div></div></section>
  <section className="bg-background py-20 md:py-24"><div className="container mx-auto px-4"><SectionHeader label="Connected data quality" title="Related Services and" gradientText="Proof"/><div className="mx-auto mt-12 grid max-w-6xl gap-px overflow-hidden rounded-[2rem] border border-border bg-border sm:grid-cols-2 lg:grid-cols-3">{[["Data Cleaning & Preparation","/ai-data-services/cleaning-validation/data-cleaning-preparation"],["LLM Training Data Curation","/ai-data-services/cleaning-validation/llm-data-curation"],["Dataset QA & Label Audit","/ai-data-services/cleaning-validation/dataset-qa-label-audit"],["Document & OCR Annotation","/ai-data-services/annotation-labeling/document-ocr-annotation"],["AI Data Collection","/ai-data-services/data-collection"],["All Cleaning & Validation Services","/ai-data-services/cleaning-validation"],["Cleaned dataset samples","/ai-data-samples/cleaned-datasets"],["Case studies","/casestudy"],["Client testimonials","/clients-testimonials"]].map(([a,b])=><Link key={a} to={b} className="group flex items-center justify-between bg-white p-6 font-heading font-bold transition-colors hover:bg-primary/[.05]">{a}<ArrowRight className="h-4 w-4 text-primary transition-transform group-hover:translate-x-1"/></Link>)}</div><div className="mx-auto mt-10 grid max-w-6xl gap-x-10 sm:grid-cols-2">{["Quasi-identifiers assessed, not ignored","PDF, metadata, reflection and re-entry checks","Recall measured against verified reference","Adversarial re-identification attempt","Residual risk stated honestly","Indian name and identifier depth","Named reviewers and restricted environments","ISO 9001 and ISO 27001 processes"].map(x=><div key={x} className="flex gap-3 border-b border-border py-4 text-sm font-medium"><BadgeCheck className="mt-0.5 h-4 w-4 shrink-0 text-primary"/>{x}</div>)}</div><div className="mx-auto mt-8 max-w-6xl rounded-xl border border-border bg-muted/30 p-5 text-sm"><strong>Planned sibling pages:</strong> Metadata Enrichment · Data Validation &amp; Verification</div></div></section>
  </>};

export const PiiFAQ=()=> <><RelatedBlogs/><section className="bg-[#f3f7f6] py-20 md:py-24"><div className="container mx-auto px-4"><SectionHeader label="Questions answered precisely" title="PII Detection & Redaction" gradientText="FAQ"/><div className="mx-auto mt-12 max-w-4xl divide-y divide-border border-y border-border">{piiFaqs.map(([q,a],i)=><details key={q} className="group py-1"><summary className="flex cursor-pointer list-none items-center justify-between gap-6 py-5 font-heading font-bold"><span><span className="mr-4 font-mono text-xs text-primary">{String(i+1).padStart(2,"0")}</span>{q}</span><span className="text-2xl font-light text-primary transition-transform group-open:rotate-45">+</span></summary><p className="max-w-3xl pb-6 pl-10 text-sm leading-7 text-muted-foreground">{a}</p></details>)}</div></div></section></>;
