import { Helmet } from "react-helmet-async";
import RelatedBlogs from "@/components/blog/RelatedBlogs";
import { Clock3, ScanLine, Waypoints } from "lucide-react";
import AIDataServicesLayout from "../../shared/AIDataServicesLayout";
import SEOHead from "../../shared/SEOHead";
import ServiceHero from "../../shared/ServiceHero";
import FAQSection from "../../shared/FAQSection";
import ServiceCTA from "../../shared/ServiceCTA";
import { DeliveryCommercial, FrequencyGuide, SecurityRelatedWhy, TrackingQuality, VideoDefinition, VideoMethods, VideoProcess } from "./VideoAnnotationCoreSections";

const canonical="https://www.eqourse.com/ai-data-services/annotation-labeling/video-annotation";
const faqs=[
 ["What is video annotation?","Video annotation labels objects, actions and events across video frames so a model learns how things move and change over time. Each tracked object keeps a consistent identity across every frame it appears in."],
 ["What is the difference between video annotation and image annotation?","Image annotation labels independent frames. Video annotation adds identity persistence, temporal consistency and an annotation-frequency decision across a continuous sequence."],
 ["What types of video annotation does eQOURSE provide?","Persistent-ID object tracking, frame-by-frame boxes, keyframe interpolation, video instance segmentation, action recognition, temporal event segmentation, trajectories, pose tracking, multi-camera re-identification and video classification."],
 ["Do you annotate every frame?","Usually not. Most production work uses keyframes with interpolation and human review. During the pilot we compare two frequencies so you can choose from a measured accuracy and cost trade-off."],
 ["How do you handle objects that are occluded or leave the frame?","Guidelines define whether tracks continue through occlusion, the re-entry threshold for a new ID and how unresolved identity ambiguity is handled. Every new case receives a versioned ruling."],
 ["How do you measure video annotation quality?","We report ID switch rate and track fragmentation, plus temporal consistency, interpolation checks, IoU on sampled keyframes, completeness audits, hidden gold clips and full-sequence second-pass review."],
 ["What is an ID switch?","An ID switch happens when a tracked object wrongly changes identity mid-sequence, such as two people crossing and receiving each other's IDs afterward."],
 ["What output formats do you deliver?","MOT Challenge, COCO-Video or COCO with track IDs, CVAT XML, per-frame YOLO or Pascal VOC, JSON, JSONL, CSV, PNG masks, SRT or VTT temporal ranges and custom schemas."],
 ["Can you work in our annotation tool?","Yes. Projects can run in your platform with your licences and access controls, or on tooling provided by eQOURSE."],
 ["Do you use AI to pre-generate tracks?","Where a suitable tracker exists, it can generate starting tracks for human correction. Every track is reviewed across the full sequence and measured against the same ground truth as manual work."],
 ["How much does video annotation cost?","Video is normally priced per footage minute or annotated frame. Cost depends on frequency, method, objects, frame rate, motion, occlusion, QA, turnaround and security. Share 2–5 representative minutes for a scoped estimate."],
 ["How is our footage kept secure?","Work runs under ISO 27001 certified processes with NDAs, role-based access, audit trails, secure delivery, redaction where required and contract-defined retention and deletion."],
 ["Can you annotate the audio in our video too?","Transcription, diarization and audio-event labels belong to the separate Audio & Speech Annotation service and can be coordinated on the same timeline once that dedicated page is live."],
 ["Can you fix a tracked dataset we already have?","Yes. We audit existing tracks, measure ID switches and fragmentation against a corrected guideline, then repair or re-annotate affected sequences."],
 ["How do we start?","Share 2–5 minutes of representative footage, the class list and accuracy target for a free pilot with track-level QA metrics and a recommended frequency."],
].map(([question,answer])=>({question,answer}));
const offers=["Object Tracking with Persistent IDs","Frame-by-Frame Bounding Box Annotation","Keyframe Annotation with Interpolation","Video Instance Segmentation","Action and Activity Recognition","Temporal Event Segmentation","Trajectory and Motion Path Annotation","Pose and Skeletal Tracking","Multi-Camera Re-Identification","Video Classification and Scene Tagging"];
const schema={"@context":"https://schema.org","@graph":[{"@type":"Service","@id":`${canonical}#service`,name:"Video Annotation Services",serviceType:"Video Annotation and Labeling",url:canonical,description:"Frame-accurate video annotation including persistent-ID tracking, keyframe interpolation, action recognition, event segmentation and pose tracking, delivered with track-level QA in MOT, COCO-Video, CVAT or custom formats.",provider:{"@type":"Organization",name:"eQOURSE",url:"https://www.eqourse.com/"},areaServed:"Worldwide",isPartOf:{"@type":"Service","@id":"https://www.eqourse.com/ai-data-services/annotation-labeling#service"},hasOfferCatalog:{"@type":"OfferCatalog",name:"Video Annotation Services",itemListElement:offers.map(name=>({"@type":"Offer",itemOffered:{"@type":"Service",name}}))}},{"@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"Home",item:"https://www.eqourse.com/"},{"@type":"ListItem",position:2,name:"AI Data Services",item:"https://www.eqourse.com/ai-data-services"},{"@type":"ListItem",position:3,name:"Data Annotation & Labeling",item:"https://www.eqourse.com/ai-data-services/annotation-labeling"},{"@type":"ListItem",position:4,name:"Video Annotation",item:canonical}]},{"@type":"FAQPage",mainEntity:faqs.map(({question,answer})=>({"@type":"Question",name:question,acceptedAnswer:{"@type":"Answer",text:answer}}))}]};

const VideoAnnotationPage=()=> <AIDataServicesLayout breadcrumbs={[{label:"AI Data Services",href:"/ai-data-services"},{label:"Data Annotation & Labeling",href:"/ai-data-services/annotation-labeling"},{label:"Video Annotation"}]}>
 <SEOHead title="Video Annotation Services for Computer Vision | eQOURSE" description="Frame-accurate video annotation with persistent-ID tracking, action recognition, event segmentation and pose tracking. Track-level QA, MOT and COCO delivery." canonical={canonical} keywords="video annotation services, video labeling services, video annotation company, video data annotation, video object tracking annotation, action recognition annotation, frame by frame annotation, video segmentation annotation, multi object tracking dataset" ogImage="https://www.eqourse.com/assets/ai-data/annotation-labeling/video-annotation/video-annotation-og.webp"/>
 <Helmet><link rel="preload" as="image" href="/assets/ai-data/annotation-labeling/video-annotation/video-annotation-services-object-tracking-hero.avif" type="image/avif" fetchPriority="high"/><script type="application/ld+json">{JSON.stringify(schema)}</script></Helmet>
 <ServiceHero tone="dark" preHeadline="Identity-Persistent Ground Truth" headline="Video Annotation Services for Object Tracking and" headlineAccent="Video AI" subtext="Frame-accurate tracks with persistent identities through occlusion and re-entry, precise action boundaries, and an annotation frequency measured for your model." ctaText="Start Free Pilot" ctaLink="/free-pilot" secondaryCtaText="Talk to a Data Specialist" secondaryCtaLink="/contact-us" imageSrc="/assets/ai-data/annotation-labeling/video-annotation/video-annotation-services-object-tracking-hero.webp" imageAvifSrc="/assets/ai-data/annotation-labeling/video-annotation/video-annotation-services-object-tracking-hero.avif" imageAlt="Annotation specialist tracking objects across video frames with a timeline scrubber and persistent ID labels" imageWidth={1200} imageHeight={800} trustStats={[{value:"Persistent IDs",label:"Through occlusion and re-entry"},{value:"Keyframe + interpolation",label:"Label only what your model needs"},{value:"ISO",label:"9001 & 27001 certified processes"}]} rotatingBadges={[{icon:Waypoints,title:"Identity held",subtitle:"Track · Occlusion · Re-entry",color:"hsl(170 82% 55%)"},{icon:Clock3,title:"Frequency measured",subtitle:"Dense · Sparse · Adaptive",color:"hsl(190 80% 58%)"},{icon:ScanLine,title:"Temporal QA",subtitle:"ID switch · Fragmentation",color:"hsl(35 92% 58%)"}]} bottomBadge={{iconText:"MOT",title:"Sequence-level ground truth",subtitle:"Tracks · Events · Motion"}}/>
 <VideoDefinition/><VideoMethods/><FrequencyGuide/><VideoProcess/><TrackingQuality/><DeliveryCommercial/><SecurityRelatedWhy/>
 <RelatedBlogs />
 <FAQSection faqs={faqs} label="Video Annotation FAQs" title="Frequently Asked Questions About Video Annotation"/>
 <ServiceCTA headline="Get Your Video Annotated for Production" subtext="Send a few representative minutes with the class list and accuracy target—we'll recommend a frequency, measure the trade-off and run a pilot." ctaText="Start Free Pilot" ctaLink="/free-pilot" secondaryCtaText="Talk to a Data Specialist" secondaryCtaLink="/contact-us" note="Pilot includes track-level QA metrics"/>
</AIDataServicesLayout>;
export default VideoAnnotationPage;
